/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ADBannerViewDelegate <NSObject>
@optional
-(void)bannerViewActionDidFinish:(id)bannerViewAction;
-(BOOL)bannerViewActionShouldBegin:(id)bannerViewAction willLeaveApplication:(BOOL)application;
-(void)bannerView:(id)view didFailToReceiveAdWithError:(id)error;
-(void)bannerViewDidLoadAd:(id)bannerView;
-(void)bannerViewWillLoadAd:(id)bannerView;
@end

