/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSMutableDictionary;

@interface ADCAssetManager : NSObject {
	NSMutableDictionary* assets;
	BOOL _dirty;
	NSMutableArray* _download_queue;
	NSMutableArray* _download_data_events;
	int _media_pool_size;
}
@property(assign, nonatomic) int media_pool_size;
-(void).cxx_destruct;
-(int)getMediaPoolCount;
-(int)getMediaPoolSize;
-(void)reportDataDownload:(int)download;
-(double)getDownloadMegabitsPerSec;
-(int)getDownloadQueueSize;
-(void)saveAssets;
-(void)redownloadAssets;
-(void)update;
-(void)onAssetChanged:(id)changed;
-(id)getAsset:(id)asset withLastModified:(id)lastModified;
-(id)addAsset:(id)asset withLastModified:(id)lastModified;
-(id)init;
@end

