//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary, NSString;

@interface ADCConfiguration : NSObject
{
    _Bool _active;
    _Bool _downloading;
    _Bool _needs_initial_configuration_request;
    unsigned long long _cache_filter;
    NSMutableDictionary *_zones;
    NSMutableDictionary *_currency_list;
    _Bool _currency_dirty;
    _Bool _enabled;
    _Bool _publisher_logging_wanted;
    _Bool _has_zones;
    id <AdColonyDelegate> _delegate;
    NSString *_app_id;
    NSDate *_last_ad_update;
}

@property(nonatomic) _Bool has_zones; // @synthesize has_zones=_has_zones;
@property(nonatomic) _Bool publisher_logging_wanted; // @synthesize publisher_logging_wanted=_publisher_logging_wanted;
@property(readonly, nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) NSDate *last_ad_update; // @synthesize last_ad_update=_last_ad_update;
@property(readonly, nonatomic) NSString *app_id; // @synthesize app_id=_app_id;
@property(readonly, nonatomic) id <AdColonyDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)appTransportSecurityDisabled;
- (_Bool)areAdsDisabled;
- (_Bool)cacheAllowed;
- (void)disableAd:(id)arg1 inBackupConfigForZone:(id)arg2;
- (void)saveZoneConfigToBackup:(id)arg1;
- (void)saveConfigBackup:(id)arg1;
- (void)loadConfigBackupForInitialRequest:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)parseConfiguration:(id)arg1;
- (id)parseConfigData:(id)arg1 options:(unsigned long long)arg2;
- (void)onConfigRequestError;
- (void)onSuccessfulConfigDownload:(id)arg1;
- (void)runBlock:(CDUnknownBlockType)arg1;
- (void)sendConfigRequest:(id)arg1 payload:(id)arg2;
- (id)getCurrentAdQueueForZones:(id)arg1;
- (void)downloadConfigurationWithZones:(id)arg1;
- (void)onDirtyCurrencyList;
- (id)getCurrencies;
- (id)getCurrency:(id)arg1;
- (id)updateCurrencyType:(id)arg1;
- (void)reloadAppInfo:(id)arg1;
- (void)externalReloadAppInfo:(id)arg1;
- (id)getZonesEligibleForReconfig;
- (id)getZones;
- (id)getZone:(id)arg1;
- (void)applicationWillEnterForeground;
- (void)update;
- (id)init:(id)arg1;

@end

