//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ADCViewElement.h"

@class NSString, UIButton, UILabel;

@interface ADCCompanionAdButton : ADCViewElement
{
    UIButton *_button;
    UILabel *_label_view;
    _Bool _enabled;
    int _position;
    NSString *_label;
    NSString *_label_rgba;
    NSString *_clickAction;
    NSString *_clickActionType;
    NSString *_event;
    id _ad;
}

@property(nonatomic) id ad; // @synthesize ad=_ad;
- (void).cxx_destruct;
- (void)reset;
- (void)setAlpha:(double)arg1;
- (_Bool)show:(id)arg1;
- (void)layout:(id)arg1;
- (void)buttonPushed;
- (id)init:(id)arg1 withPosition:(int)arg2 inAd:(id)arg3;

@end

