//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ADCAd, ADCAssetManager, ADCConfiguration, ADCDeviceData, ADCEventManager, ADCRootViewController, ADCSession, NSString, NSThread, UIView;

@interface ADCCore : NSObject
{
    _Bool _network_timeout_expired;
    NSString *_app_id;
    ADCDeviceData *_device;
    ADCAssetManager *_asset_manager;
    ADCEventManager *_event_manager;
    UIView *_video_container;
    UIView *_other_container;
    UIView *_cover_screen;
    ADCRootViewController *_adc_view_controller;
    ADCConfiguration *_configuration;
    ADCAd *_active_ad;
    NSThread *_work_thread;
    ADCSession *_session;
}

+ (void)log:(int)arg1 withCodeLocation:(const char *)arg2 withCodeLocationLine:(int)arg3 withLevelDesc:(id)arg4 withFormat:(id)arg5;
+ (void)logPublic:(int)arg1 forceIt:(_Bool)arg2 withLevelDesc:(id)arg3 withFormat:(id)arg4;
+ (void)togglePublisherLogging:(_Bool)arg1;
+ (void)toggleLogging:(_Bool)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) ADCSession *session; // @synthesize session=_session;
@property(nonatomic) _Bool network_timeout_expired; // @synthesize network_timeout_expired=_network_timeout_expired;
@property(readonly, nonatomic) NSThread *work_thread; // @synthesize work_thread=_work_thread;
@property(retain, nonatomic) ADCAd *active_ad; // @synthesize active_ad=_active_ad;
@property(readonly, nonatomic) ADCConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) ADCRootViewController *adc_view_controller; // @synthesize adc_view_controller=_adc_view_controller;
@property(readonly, nonatomic) UIView *cover_screen; // @synthesize cover_screen=_cover_screen;
@property(readonly, nonatomic) UIView *other_container; // @synthesize other_container=_other_container;
@property(readonly, nonatomic) UIView *video_container; // @synthesize video_container=_video_container;
@property(readonly, nonatomic) ADCEventManager *event_manager; // @synthesize event_manager=_event_manager;
@property(readonly, nonatomic) ADCAssetManager *asset_manager; // @synthesize asset_manager=_asset_manager;
@property(readonly) ADCDeviceData *device; // @synthesize device=_device;
@property(retain) NSString *app_id; // @synthesize app_id=_app_id;
- (void).cxx_destruct;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (void)onNetworkTimeoutExpired;
- (_Bool)applicationIsActive;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (void)didRotate:(id)arg1;
- (void)willRotate:(id)arg1;
- (void)hideAndUnloadViews;
- (void)work;
- (void)update;
- (void)prepare:(id)arg1;
- (id)init;

@end

