/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSDate, NSMutableDictionary, NSString;
@protocol AdColonyDelegate;

@interface ADCConfiguration : NSObject {
	BOOL _active;
	BOOL _downloading;
	BOOL _needs_initial_configuration_request;
	unsigned _cache_filter;
	NSMutableDictionary* _zones;
	NSMutableDictionary* _currency_list;
	BOOL _currency_dirty;
	BOOL _enabled;
	BOOL _publisher_logging_wanted;
	BOOL _has_zones;
	id<AdColonyDelegate> _delegate;
	NSString* _app_id;
	NSDate* _last_ad_update;
}
@property(assign, nonatomic) BOOL has_zones;
@property(assign, nonatomic) BOOL publisher_logging_wanted;
@property(readonly, assign, nonatomic) BOOL enabled;
@property(readonly, assign, nonatomic) NSDate* last_ad_update;
@property(readonly, assign, nonatomic) NSString* app_id;
@property(readonly, assign, nonatomic) id<AdColonyDelegate> delegate;
-(void).cxx_destruct;
-(BOOL)appTransportSecurityDisabled;
-(BOOL)areAdsDisabled;
-(BOOL)cacheAllowed;
-(void)disableAd:(id)ad inBackupConfigForZone:(id)zone;
-(void)saveZoneConfigToBackup:(id)backup;
-(void)saveConfigBackup:(id)backup;
-(void)loadConfigBackupForInitialRequest:(BOOL)initialRequest completion:(id)completion;
-(void)parseConfiguration:(id)configuration;
-(id)parseConfigData:(id)data options:(unsigned)options;
-(void)onConfigRequestError;
-(void)onSuccessfulConfigDownload:(id)download;
-(void)runBlock:(id)block;
-(void)sendConfigRequest:(id)request payload:(id)payload;
-(id)getCurrentAdQueueForZones:(id)zones;
-(void)downloadConfigurationWithZones:(id)zones;
-(void)onDirtyCurrencyList;
-(id)getCurrencies;
-(id)getCurrency:(id)currency;
-(id)updateCurrencyType:(id)type;
-(void)reloadAppInfo:(id)info;
-(void)externalReloadAppInfo:(id)info;
-(id)getZonesEligibleForReconfig;
-(id)getZones;
-(id)getZone:(id)zone;
-(void)applicationWillEnterForeground;
-(void)update;
-(id)init:(id)init;
@end

