/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSDictionary;

@interface ADCEventManager : NSObject {
	NSMutableArray* events;
	NSMutableArray* dispatch_queue;
	BOOL queue_session_start_event;
	BOOL queue_install_event;
	BOOL queue_update_event;
	BOOL read_iap_events;
	BOOL dirty_;
	BOOL dirty_meta_data;
	BOOL dirty_dynamic_interests;
	long last_meta_data_update;
	long last_dynamic_interest_update;
	NSDictionary* _app_tracking_info;
	NSDictionary* _third_party_app_tracking_info;
}
@property(retain, nonatomic) NSDictionary* third_party_app_tracking_info;
@property(retain, nonatomic) NSDictionary* app_tracking_info;
-(void).cxx_destruct;
-(void)onDynamicInterestsChanged;
-(void)onUserMetaDataChanged;
-(BOOL)notifyIAPComplete:(id)complete productID:(id)anId quantity:(int)quantity price:(id)price currencyCode:(id)code;
-(void)saveEvents;
-(void)reportAppUpdate;
-(void)reportInstall;
-(void)update;
-(void)queueArray:(id)array withType:(id)type isThirdParty:(BOOL)party isReplay:(BOOL)replay;
-(void)queueCustomURL:(id)url type:(id)type isThirdParty:(BOOL)party payload:(id)payload V4VCHolding:(id)holding adSessionID:(id)anId;
-(void)queueURL:(id)url type:(id)type isThirdParty:(BOOL)party isReplay:(BOOL)replay isReward:(BOOL)reward V4VCHolding:(id)holding adSessionID:(id)anId;
-(void)applicationWillEnterForeground;
-(id)init;
@end

