//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ADCEvent;

@interface ADCEventPusher : NSObject
{
    ADCEvent *event;
    _Bool executing_;
    _Bool finished_;
    int reference_count_;
}

@property(readonly, nonatomic) _Bool executing; // @synthesize executing=executing_;
@property(readonly, nonatomic) _Bool finished; // @synthesize finished=finished_;
- (void).cxx_destruct;
- (void)onSuccessfulEventPushResponse:(id)arg1;
- (void)runBlock:(CDUnknownBlockType)arg1;
- (void)pushEvent:(id)arg1;
- (void)start;
- (void)cancel;
- (void)done;
- (id)init:(id)arg1;

@end

