/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import "ADCViewElement.h"

@class NSString, UIButton, UIWebView, UIColor;

@interface ADCInVideoEngagementButton : ADCViewElement <UIWebViewDelegate> {
	UIButton* _button;
	UIWebView* _webview_label;
	BOOL _webview_label_ready;
	BOOL _enabled;
	double _delay;
	NSString* _label;
	NSString* _label_html;
	UIColor* _label_color;
	NSString* _click_action;
	NSString* _click_action_type;
	NSString* _event;
	id _ad;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) id ad;
-(void).cxx_destruct;
-(void)reset;
-(void)freePlaybackResources;
-(void)buttonPushed;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)show:(id)show;
-(void)layout:(id)layout;
-(void)update:(id)update;
-(id)init:(id)init inAd:(id)ad;
@end

