/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface ADCLocalEventManager : NSObject {
}
+(void)onAdsNotFilled:(id)filled;
+(void)onAdsNotReady:(id)ready;
+(void)onAdsReady:(id)ready;
+(void)onV4VCNotRewarded:(id)rewarded;
+(void)onV4VCRewarded:(id)rewarded;
+(void)onAdEnded:(id)ended forZone:(id)zone forAd:(id)ad didReward:(BOOL)reward;
+(void)onAdStarted:(id)started forZone:(id)zone forAd:(id)ad wantedReward:(BOOL)reward;
+(void)onAdCouldNotPlay:(id)play forZone:(id)zone wantedReward:(BOOL)reward;
+(void)onAdStartAttempt:(id)attempt forZone:(id)zone wantedReward:(BOOL)reward;
@end

