/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSString;

@interface ADCNetwork : NSObject {
	NSString* _host_name;
	SCNetworkReachabilityRef _reachability_ref;
	NSString* _host;
	unsigned _currentReachabilityStatus;
}
@property(assign, nonatomic) unsigned currentReachabilityStatus;
@property(retain, nonatomic) NSString* host;
+(id)sharedNetwork;
-(void).cxx_destruct;
-(void)dealloc;
-(unsigned)networkStatusForFlags:(unsigned)flags;
-(void)stopMonitoring;
-(BOOL)startMonitoringWithReachabilityChangeHandler:(id)reachabilityChangeHandler;
@end

