/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>
#import "AdColonyAdDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "AdColonyNativeAdEngagementDelegate.h"

@class ADCZone, ADCAd, NSDictionary, UIImage, UIImageView, UIButton, ADCAVPlayerPlaybackView, UIViewController, NSString;
@protocol AdColonyNativeAdDelegate;

@interface AdColonyNativeAdView : UIView <SKStoreProductViewControllerDelegate, AdColonyAdDelegate, AdColonyNativeAdEngagementDelegate> {
	ADCAd* _ad;
	id<AdColonyNativeAdDelegate> _delegate;
	NSString* _adSessionGUID;
	NSDictionary* _tracking;
	NSDictionary* _thirdPartyTracking;
	BOOL sentFirstQuartile;
	BOOL sentMidPoint;
	BOOL sentThirdQuartile;
	float _aspectRatio;
	UIImage* _advertiserIcon;
	NSString* _advertiserName;
	NSString* _adTitle;
	NSString* _adDescription;
	float _volume;
	BOOL _muted;
	unsigned _state;
	id _videoTimeObserver;
	double _videoDuration;
	ADCZone* _zone;
	int _ad_slot;
	UIViewController* _viewController;
	UIView* _videoContainer;
	ADCAVPlayerPlaybackView* _videoView;
	UIImageView* _posterView;
	UIButton* _muteButton;
	UIButton* _playButton;
	BOOL _userMutable;
	float _muteWidth;
	float _muteHeight;
	float _unmuteWidth;
	float _unmuteHeight;
	BOOL _engagementEnabled;
	UIButton* _engagementButton;
	NSString* _engagementType;
	NSString* _engagementData;
	NSString* _engagementProductID;
	BOOL _posterClickActionInApp;
	NSString* _posterClickActionType;
	NSString* _posterClickActionProductID;
}
@property(assign, nonatomic) BOOL muted;
@property(assign, nonatomic) float volume;
@property(retain, nonatomic) UIButton* engagementButton;
@property(readonly, assign, nonatomic) NSString* adDescription;
@property(readonly, assign, nonatomic) NSString* adTitle;
@property(readonly, assign, nonatomic) UIImage* advertiserIcon;
@property(readonly, assign, nonatomic) NSString* advertiserName;
@property(assign, nonatomic) __weak id<AdColonyNativeAdDelegate> delegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(id)init;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(void)resume;
-(void)pause;
-(void)updateMuteButtonState;
-(void)reportMuteEvents:(BOOL)events;
-(void)mutePressed;
-(float)recommendedHeightForWidth:(float)width;
-(void)onAdColonyAdAttemptFinished:(BOOL)finished inZone:(id)zone;
-(void)productViewControllerDidFinish:(id)productViewController;
-(void)onInVideoEngagementPressed:(BOOL)videoEngagementPressed;
-(void)showAppStoreWithURL:(id)url;
-(void)showInAppAppStoreWithProductID:(id)productID;
-(void)showAppStoreWithProductID:(id)productID;
-(void)onVideoTimeChanged:(id)changed;
-(void)onEngagementTapped;
-(void)showFullscreen;
-(void)onVideoContainerTapped;
-(void)onVideoFinished;
-(void)onBecomeActive;
-(void)onResignActive;
-(void)updateCurrentAdInfo:(BOOL)info;
-(void)onBackgrounded;
-(void)layoutSubviews;
-(id)initWithAd:(id)ad aspectRatio:(float)ratio config:(id)config tracking:(id)tracking thirdPartyTracking:(id)tracking5 inZone:(id)zone adSlot:(int)slot viewController:(id)controller;
@end

