//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdColonyNativeAdView.h"

#import "AdColonyAdDelegate.h"
#import "AdColonyNativeAdEngagementDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"

@class NSString;

@interface AdColonyNativeAdView (Private) <SKStoreProductViewControllerDelegate, AdColonyAdDelegate, AdColonyNativeAdEngagementDelegate>
- (void)onAdColonyAdAttemptFinished:(_Bool)arg1 inZone:(id)arg2;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)onInVideoEngagementPressed:(_Bool)arg1;
- (void)showAppStoreWithURL:(id)arg1;
- (void)showInAppAppStoreWithProductID:(id)arg1;
- (void)showAppStoreWithProductID:(id)arg1;
- (void)onVideoTimeChanged:(id)arg1;
- (void)onEngagementTapped;
- (void)showFullscreen;
- (void)onVideoContainerTapped;
- (void)onVideoFinished;
- (void)onBecomeActive;
- (void)onResignActive;
- (void)updateCurrentAdInfo:(_Bool)arg1;
- (void)onBackgrounded;
- (void)layoutSubviews;
- (id)initWithAd:(id)arg1 aspectRatio:(double)arg2 config:(id)arg3 tracking:(id)arg4 thirdPartyTracking:(id)arg5 inZone:(id)arg6 adSlot:(int)arg7 viewController:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

