//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ADCAVPlayerPlaybackView, ADCAd, ADCZone, NSDictionary, NSString, UIButton, UIImage, UIImageView, UIViewController;

@interface AdColonyNativeAdView : UIView
{
    ADCAd *_ad;
    id <AdColonyNativeAdDelegate> _delegate;
    NSString *_adSessionGUID;
    NSDictionary *_tracking;
    NSDictionary *_thirdPartyTracking;
    _Bool sentFirstQuartile;
    _Bool sentMidPoint;
    _Bool sentThirdQuartile;
    double _aspectRatio;
    UIImage *_advertiserIcon;
    NSString *_advertiserName;
    NSString *_adTitle;
    NSString *_adDescription;
    float _volume;
    _Bool _muted;
    unsigned long long _state;
    id _videoTimeObserver;
    double _videoDuration;
    ADCZone *_zone;
    int _ad_slot;
    UIViewController *_viewController;
    UIView *_videoContainer;
    ADCAVPlayerPlaybackView *_videoView;
    UIImageView *_posterView;
    UIButton *_muteButton;
    UIButton *_playButton;
    _Bool _userMutable;
    double _muteWidth;
    double _muteHeight;
    double _unmuteWidth;
    double _unmuteHeight;
    _Bool _engagementEnabled;
    UIButton *_engagementButton;
    NSString *_engagementType;
    NSString *_engagementData;
    NSString *_engagementProductID;
    _Bool _posterClickActionInApp;
    NSString *_posterClickActionType;
    NSString *_posterClickActionProductID;
}

@property(retain, nonatomic) UIButton *engagementButton; // @synthesize engagementButton=_engagementButton;
@property(readonly, nonatomic) NSString *adDescription; // @synthesize adDescription=_adDescription;
@property(readonly, nonatomic) NSString *adTitle; // @synthesize adTitle=_adTitle;
@property(readonly, nonatomic) UIImage *advertiserIcon; // @synthesize advertiserIcon=_advertiserIcon;
@property(readonly, nonatomic) NSString *advertiserName; // @synthesize advertiserName=_advertiserName;
@property(nonatomic) __weak id <AdColonyNativeAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)resume;
- (void)pause;
- (void)updateMuteButtonState;
- (void)reportMuteEvents:(_Bool)arg1;
- (void)mutePressed;
@property(nonatomic) _Bool muted;
@property(nonatomic) float volume;
- (double)recommendedHeightForWidth:(double)arg1;

@end

