/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AdColonyDelegate <NSObject>
@optional
-(void)onAdColonyV4VCReward:(BOOL)reward currencyName:(id)name currencyAmount:(int)amount inZone:(id)zone;
-(void)onAdColonyAdAvailabilityChange:(BOOL)change inZone:(id)zone;
@end

