/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>
#import "AdColonyDelegate.h"
#import "AdColonyAdDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface AdColonyDelegateAdapter : NSObject <AdColonyDelegate, AdColonyAdDelegate> {
	Delegate* _delegateImpl;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign) Delegate* delegateImpl;
-(void)onAdColonyAdFinishedWithInfo:(id)info;
-(void)onAdColonyAdStartedInZone:(id)zone;
-(void)onAdColonyV4VCReward:(BOOL)reward currencyName:(id)name currencyAmount:(int)amount inZone:(id)zone;
-(void)onAdColonyAdAvailabilityChange:(BOOL)change inZone:(id)zone;
-(id)initWithUniversalDelegate:(Delegate*)universalDelegate;
@end

