//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface ADCRotatingViewController : UIViewController
{
    _Bool _statusBarHidden;
    unsigned long long _supportedOrientations;
}

- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (id)initWithStatusBarHidden:(_Bool)arg1 supportedOrientations:(unsigned long long)arg2;

@end

