/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>


@interface ADCRotatingViewController : UIViewController {
	BOOL _statusBarHidden;
	unsigned _supportedOrientations;
}
-(BOOL)prefersStatusBarHidden;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)initWithStatusBarHidden:(BOOL)statusBarHidden supportedOrientations:(unsigned)orientations;
@end

