//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ADCViewElement.h"

@class ADCVideoTimer, AVPlayer, UIView;

@interface ADCVideo : ADCViewElement
{
    AVPlayer *_player;
    _Bool _enabled;
    _Bool _replaying;
    _Bool _lock_pause;
    double _duration;
    int _duration_seconds;
    double _last_playback_position;
    long long _desired_playback_state;
    long long _actual_playback_state;
    ADCVideoTimer *_video_timer;
    UIView *_parent_container;
    int _attempts_to_rebuild_player;
    _Bool _event_first_quartile_dispatched;
    _Bool _event_mid_point_dispatched;
    _Bool _event_third_quartile_dispatched;
    _Bool _event_ninety_percent_reported;
    _Bool _event_complete_dispatched;
    int _watchdog_trigger;
    id _ad;
}

@property(readonly, nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool replaying; // @synthesize replaying=_replaying;
@property(nonatomic) id ad; // @synthesize ad=_ad;
- (void).cxx_destruct;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setPlaybackPosition:(double)arg1;
- (void)unlockPause;
- (void)resume;
- (void)pause:(_Bool)arg1;
- (void)replay;
- (_Bool)setupPlayer;
- (void)reset;
- (void)update:(id)arg1;
- (void)layout:(id)arg1;
- (_Bool)show:(id)arg1;
- (id)init:(id)arg1 inAd:(id)arg2;

@end

