//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary;

@interface ADCViewElement : NSObject
{
    NSMutableDictionary *children_;
    NSMutableDictionary *assets_;
    _Bool user_interaction_enabled;
    int width;
    int height;
    int scale;
}

- (void).cxx_destruct;
- (void)reset;
- (void)dereference;
- (void)setChildrenUserInteractionEnabled:(_Bool)arg1;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)setVisible:(_Bool)arg1;
- (void)setAlpha:(double)arg1;
- (void)setAsset:(id)arg1 forKey:(long long)arg2;
- (id)getAsset:(long long)arg1;
@property(readonly, nonatomic) NSArray *assets;
- (void)updateChildren:(id)arg1;
- (void)layoutChildren:(id)arg1;
- (_Bool)showChildren:(id)arg1;
- (void)setChildrenAlpha:(double)arg1;
- (void)setChild:(id)arg1 forKey:(long long)arg2;
- (id)getChild:(long long)arg1;
@property(readonly, nonatomic) NSArray *children;
- (void)update:(id)arg1;
- (_Bool)show:(id)arg1;
- (void)layout:(id)arg1;
@property(readonly, nonatomic) _Bool ready;
- (id)init;

@end

