/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface ADCV4VCHolding : NSObject {
	BOOL ad_finished;
	BOOL callback_successful;
	BOOL callback_finished;
	NSString* zone;
}
@property(retain, nonatomic) NSString* zone;
@property(assign, nonatomic) BOOL callback_successful;
@property(assign, nonatomic) BOOL callback_finished;
@property(assign, nonatomic) BOOL ad_finished;
-(void).cxx_destruct;
-(id)init;
@end

