/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADCViewElement.h"

@class NSString, UIButton;

@interface ADCV4VCButton : ADCViewElement {
	UIButton* _button;
	BOOL _enabled;
	int _position;
	NSString* _label;
	NSString* _label_rgba;
	NSString* _label_shadow_rgba;
	NSString* _click_action;
	NSString* _click_action_type;
	id _ad;
}
@property(assign, nonatomic) id ad;
-(void).cxx_destruct;
-(void)buttonPushed;
-(void)reset;
-(BOOL)show:(id)show;
-(void)layout:(id)layout;
-(id)init:(id)init withPosition:(int)position inAd:(id)ad;
@end

