/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSDate, NSArray, NSString, ADCV4VCCurrency, NSDictionary;

@interface ADCZone : NSObject {
	int _ad_position;
	int _play_attempts;
	int _session_plays;
	int _play_interval;
	int _zone_state;
	NSDictionary* _tracking;
	NSArray* _play_order;
	BOOL _initialized;
	int _min_config_window;
	int _max_config_window;
	int _min_ad_threshold;
	BOOL _disabling;
	BOOL _enabled;
	BOOL _v4vc;
	BOOL _eligible_for_reconfig;
	NSString* _uuid;
	NSArray* _ads;
	ADCV4VCCurrency* _currency;
	NSDate* _last_config;
}
@property(retain, nonatomic) NSDate* last_config;
@property(assign, nonatomic) BOOL eligible_for_reconfig;
@property(readonly, assign, nonatomic) BOOL v4vc;
@property(readonly, assign, nonatomic) BOOL enabled;
@property(readonly, assign, nonatomic) ADCV4VCCurrency* currency;
@property(retain, nonatomic) NSArray* ads;
@property(retain, nonatomic) NSString* uuid;
-(void).cxx_destruct;
-(void)onAdSuccessfullyPlayed;
-(id)playNextAd:(id)ad withV4VCPrePopup:(BOOL)v4VCPrePopup andV4VCPostPopup:(BOOL)popup;
-(int)getReadyAdCount;
-(int)getTotalAdCount;
-(BOOL)hasAdsOfType:(int)type;
-(id)getAdByUUID:(id)uuid;
-(id)getNativeAdViewWithViewController:(id)viewController delegate:(id)delegate;
-(void)onEventRequest:(int)request;
-(id)getNextAd:(BOOL)ad ofType:(int)type;
-(unsigned)zoneStatus;
-(void)updateZoneState;
-(BOOL)doV4VCReward;
-(void)onNewSession;
-(void)dereference;
-(void)update:(id)update;
-(id)init:(id)init;
@end

