/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface AdmobSettings : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) BOOL collectAdvertisingIdentifiers;
@property(assign, nonatomic) BOOL hasCollectAdvertisingIdentifiers;
@property(assign, nonatomic) BOOL enableAutoEventTracking;
@property(assign, nonatomic) BOOL hasEnableAutoEventTracking;
@property(assign, nonatomic) BOOL enableAutoScreenViewTracking;
@property(assign, nonatomic) BOOL hasEnableAutoScreenViewTracking;
@property(retain, nonatomic) NSString* uaTrackingId;
@property(assign, nonatomic) BOOL hasUaTrackingId;
+(id)descriptor;
@end

