/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface BackgroundView : UIView {
	NativeViewPool<UIWebView> webViewPool;
	NativeViewPool<UITextFieldHolder> textFieldPool;
}
-(id).cxx_construct;
-(void).cxx_destruct;
-(void)ReleaseTextField:(id)field;
-(void)ReleaseWebView:(id)view;
-(id)CreateTextField;
-(id)CreateWebView;
-(id)PrepareView:(id)view;
@end

