/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SKPaymentTransactionObserver.h"
#import "wotblitz-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface BlitzSKObserver : NSObject <SKPaymentTransactionObserver> {
	ShopApple* myShop;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)paymentQueue:(id)queue updatedTransactions:(id)transactions;
-(void)processTransactions:(id)transactions;
-(void)deferredTransaction:(id)transaction;
-(void)failedTransaction:(id)transaction;
-(void)restoreTransaction:(id)transaction;
-(void)completeTransaction:(id)transaction;
-(void)setShop:(ShopApple*)shop;
@end

