/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface CBActionWrapper : NSObject {
	id _callback;
}
@property(copy, nonatomic) id callback;
+(id)actionWrapperWithCallback:(id)callback;
-(void).cxx_destruct;
-(void)action:(id)action;
-(id)initWithCallback:(id)callback;
-(id)init;
@end

