//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface CBAdUnitFileData : NSObject
{
    NSString *_ID;
    NSString *_type;
    NSString *_folder;
    NSString *_URLString;
    unsigned long long _state;
    unsigned long long _failures;
    long long _priority;
    unsigned long long _bytes;
    NSDate *_lastModified;
}

@property(retain, nonatomic) NSDate *lastModified; // @synthesize lastModified=_lastModified;
@property(nonatomic) unsigned long long bytes; // @synthesize bytes=_bytes;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
@property(nonatomic) unsigned long long failures; // @synthesize failures=_failures;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
@property(retain, nonatomic) NSString *folder; // @synthesize folder=_folder;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (void)downloadFail;
- (void)downloadSuccess;
- (_Bool)failed;
- (_Bool)exists;
- (void)setAgeToNow;
- (void)setAgeToLastModified;
- (void)setSize;
- (id)initWithExistingFile:(id)arg1 type:(id)arg2;
- (id)initWithCategoryResponse:(id)arg1 category:(id)arg2;
- (id)initWithResponse:(id)arg1;

@end

