/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface CBAnimationManager : NSObject {
}
+(void)transitionWithAnimationType:(int)animationType layer:(id)layer duration:(float)duration animationConfigurationBlock:(id)block;
+(void)transitionWithAnimationType:(int)animationType layer:(id)layer;
+(void)transitionOutWithAnimationType:(int)animationType layer:(id)layer duration:(float)duration animationConfigurationBlock:(id)block;
+(void)transitionOutWithAnimationType:(int)animationType layer:(id)layer;
+(void)transitionInWithAnimationType:(int)animationType layer:(id)layer duration:(float)duration animationConfigurationBlock:(id)block;
+(void)transitionInWithAnimationType:(int)animationType layer:(id)layer;
@end

