/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"


@interface CBAnalytics : NSObject {
}
+(void)trackLevelInfo:(id)info eventField:(unsigned)field mainLevel:(unsigned)level subLevel:(unsigned)level4 description:(id)description;
+(void)trackLevelInfo:(id)info eventField:(unsigned)field mainLevel:(unsigned)level description:(id)description;
+(void)trackInAppPurchaseEvent:(id)appPurchaseEvent product:(id)product;
+(void)trackInAppPurchaseEventWithString:(id)string productTitle:(id)title productDescription:(id)description productPrice:(id)price productCurrency:(id)currency productIdentifier:(id)identifier;
+(void)trackInAppPurchaseEvent:(id)appPurchaseEvent productTitle:(id)title productDescription:(id)description productPrice:(id)price productCurrency:(id)currency productIdentifier:(id)identifier;
+(id)allocWithZone:(NSZone*)zone;
+(id)shared;
-(id)customEventTypeToString:(int)string;
-(id)miscRevenueGeneratingEventTypeToString:(int)string;
-(void)sendTrackingRequest:(id)request withEvent:(id)event ofType:(id)type;
-(void)trackPlayerCurrencyBalance:(float)balance ofCurrency:(id)currency atIndex:(int)index;
-(void)trackPlayerCurrencyBalance:(float)balance ofCurrency:(id)currency;
-(void)trackInGameScore:(float)gameScore atIndex:(int)index;
-(void)trackInGameScore:(float)gameScore;
-(void)trackCustomEventOfType:(int)type atIndex:(int)index withKey:(id)key;
-(void)trackCustomEventOfType:(int)type atIndex:(int)index;
-(void)trackMiscRevenueGeneratingEventOfType:(int)type amount:(float)amount currency:(id)currency fromSource:(id)source;
-(void)trackInAppPurchaseEventWithString:(id)string productTitle:(id)title productDescription:(id)description productPrice:(id)price productCurrency:(id)currency productIdentifier:(id)identifier;
-(void)trackInAppPurchaseEvent:(id)appPurchaseEvent productTitle:(id)title productDescription:(id)description productPrice:(id)price productCurrency:(id)currency productIdentifier:(id)identifier;
-(void)trackInAppPurchaseEvent:(id)appPurchaseEvent product:(id)product;
-(void)trackInAppPurchaseEventWithString:(id)string product:(id)product;
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
@end

