/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface CBAppCall : NSObject {
}
+(id)parseQueryString:(id)string;
+(id)parsePath:(id)path;
+(BOOL)handleUrl:(id)url;
+(BOOL)handleOpenURL:(id)url sourceApplication:(id)application annotation:(id)annotation;
+(BOOL)handleOpenURL:(id)url sourceApplication:(id)application;
+(void)handleShowMoreApplicationsURL:(id)url queryDict:(id)dict;
+(void)handleShowInterstitialURL:(id)url queryDict:(id)dict;
+(id)deepLinkPatterns;
-(id)init;
@end

