//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBAFJSONResponseSerializer.h"

@class CBHTTPAPIRequest;

@interface CBAPIJSONResponseSerializer : CBAFJSONResponseSerializer
{
    CBHTTPAPIRequest *_request;
}

+ (id)serializerForRequest:(id)arg1;
@property(retain, nonatomic) CBHTTPAPIRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)validateResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;
- (id)init;

@end

