//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBAppCall : NSObject
{
}

+ (id)parseQueryString:(id)arg1;
+ (id)parsePath:(id)arg1;
+ (_Bool)handleUrl:(id)arg1;
+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;
+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2;
+ (void)handleShowMoreApplicationsURL:(id)arg1 queryDict:(id)arg2;
+ (void)handleShowInterstitialURL:(id)arg1 queryDict:(id)arg2;
+ (id)deepLinkPatterns;
- (id)init;

@end

