/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface CBCommonCache : NSObject {
	NSString* _defaultCache;
}
@property(retain, nonatomic) NSString* defaultCache;
-(void).cxx_destruct;
-(id)commonCachePathWithFileName:(id)fileName;
-(id)loadCacheFromJsonFilePath:(id)jsonFilePath;
-(id)loadMostRecentCacheForName:(id)name;
-(void)createNewCacheWith:(id)with cacheDictionary:(id)dictionary;
-(void)fetchContentFor:(id)aFor withFetcher:(id)fetcher fetchedCallback:(id)callback;
-(id)initWithDefaultCache:(id)defaultCache;
-(id)init;
-(void)dealloc;
@end

