//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBCrypto : NSObject
{
}

+ (id)hexRepresentationOfData:(id)arg1;
+ (char *)SHA1WithData:(id)arg1;
+ (id)SHA1DataWithData:(id)arg1;
+ (id)SHA1StringWithData:(id)arg1;

@end

