//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBlockOperation.h"

@interface CBDelayOperation : NSBlockOperation
{
    long long _seconds;
    struct dispatch_semaphore_s *_semaphore;
}

+ (id)operationWithDelayInSeconds:(long long)arg1;
@property(nonatomic) struct dispatch_semaphore_s *semaphore; // @synthesize semaphore=_semaphore;
@property(nonatomic) long long seconds; // @synthesize seconds=_seconds;
- (void)cancel;
- (id)initWithDelayInSeconds:(long long)arg1;

@end

