/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableURLRequest.h>

@class NSString, NSMutableDictionary, NSDictionary, CBVPredicate;

@interface CBHTTPAPIRequest : NSMutableURLRequest {
	BOOL _shouldRetry;
	unsigned _retries;
	NSDictionary* _responseMask;
	CBVPredicate* _responsePredicate;
	NSMutableDictionary* _body;
	NSString* _tag;
	unsigned _retryCount;
	unsigned _currentRetryCount;
}
@property(assign, nonatomic) unsigned currentRetryCount;
@property(assign, nonatomic) unsigned retryCount;
@property(retain, nonatomic) NSString* tag;
@property(retain, nonatomic) NSMutableDictionary* body;
@property(retain, nonatomic) CBVPredicate* responsePredicate;
@property(retain, nonatomic) NSDictionary* responseMask;
@property(assign, nonatomic) unsigned retries;
@property(assign, nonatomic) BOOL shouldRetry;
+(id)getTelephonyNetworkInfo;
+(int)getNetworkStatus;
+(int)networkStatusToCBNetworkStatus:(int)cbnetworkStatus;
+(id)getRadioAccessTechnology;
+(id)localTimezone;
+(void)initMainBundle;
+(void)initModelParameters;
+(void)initEndpointOverride;
+(void)initCoreTelephony;
+(void)initialize;
-(void).cxx_destruct;
-(id)description;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)serializedBody;
-(id)uniqueTag;
-(id)uniqueSignature;
-(id)getCustomId;
-(id)getUserInterface;
-(id)getDeviceType;
-(id)getDeviceFamily;
-(id)getBundleVersion;
-(id)getBundleId;
-(id)getSessionId;
-(id)getAppId;
-(id)getRetryCount;
-(id)getAmount;
-(id)getSessionCount;
-(id)getDeviceDimensions;
-(id)getScreenScale;
-(id)getApplicationHeight;
-(id)getApplicationWidth;
-(id)getDeviceHeight;
-(id)getDeviceWidth;
-(id)getCountry;
-(id)getIdentity;
-(id)getDeviceModel;
-(id)getSystemVersion;
-(id)getIsTrackingEnabled;
-(id)getLanguage;
-(id)getTimestamp;
-(id)getIsRetina;
-(id)getIsJailBroken;
-(id)getIsPortrait;
-(id)getTimezone;
-(id)getNetworkType;
-(id)getCarrierInfo;
-(id)getSDKVersion;
-(id)getMediationLibrary;
-(id)getFrameworkVersion;
-(id)getWrapperVersion;
-(id)getIsTestModeEnabled;
-(id)getNetworkStatus;
-(id)getAPIVersion;
-(id)getContentType;
-(id)getUserAgent;
-(void)appendDeviceInfoParameters;
-(void)appendCached;
-(void)appendShouldCache;
-(id)responseMaskForPath:(id)path;
-(id)responsePredicateForPath:(id)path;
-(BOOL)retryForResponse:(id)response error:(id)error;
-(void)incrementRetryCount;
-(void)signRequest;
-(void)appendBodyArgumentKey:(id)key value:(id)value;
-(void)serializeBody;
-(void)appendHeaderKey:(id)key value:(id)value;
-(id)keyPathWithKeys:(id)keys;
-(void)initRequestBody;
-(id)initWithPath:(id)path;
@end

