/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CBImpressionProtocol <NSObject>
-(void)playbackCompleted:(id)completed;
-(void)impressionClickTriggered:(id)triggered forURL:(id)url moreData:(id)data deepLinkActive:(BOOL)active withClickCoordinates:(id)clickCoordinates;
-(void)impressionCloseTriggered:(id)triggered isDeveloperTriggered:(BOOL)triggered2;
-(void)impressionCloseTriggered:(id)triggered;
-(void)impressionFailedToInitialize:(id)initialize withError:(unsigned)error;
-(void)impressionDisplayed:(id)displayed moreData:(id)data;
-(void)impressionReadyToBeDisplayed:(id)beDisplayed moreData:(id)data;
@end

