//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBLog : NSObject
{
}

+ (void)printLogMessage:(id)arg1;
+ (id)formatLogMessage:(id)arg1 flag:(int)arg2;
+ (void)flush;
+ (void)log:(id)arg1;
+ (void)flushLog;
+ (void)applicationWillTerminate:(id)arg1;
+ (void)queueLogMessage:(id)arg1 asynchronously:(_Bool)arg2;
+ (void)log:(_Bool)arg1 level:(int)arg2 flag:(int)arg3 context:(int)arg4 file:(const char *)arg5 function:(const char *)arg6 line:(int)arg7 tag:(id)arg8 format:(id)arg9;
+ (void)setLogLevel:(int)arg1;
+ (void)initialize;

@end

