/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface CBLog : NSObject {
}
+(void)printLogMessage:(id)message;
+(id)formatLogMessage:(id)message flag:(int)flag;
+(void)flush;
+(void)log:(id)log;
+(void)flushLog;
+(void)applicationWillTerminate:(id)application;
+(void)queueLogMessage:(id)message asynchronously:(BOOL)asynchronously;
+(void)log:(BOOL)log level:(int)level flag:(int)flag context:(int)context file:(const char*)file function:(const char*)function line:(int)line tag:(id)tag format:(id)format;
+(void)setLogLevel:(int)level;
+(void)initialize;
@end

