/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import <UIKit/UIView.h>
#import "wotblitz-Structs.h"

@class CBUnderfinedProgressBar, UILabel, CBCloseButton, NSString, UITapGestureRecognizer, UIViewController;

@interface CBLoadingView : UIView <UIGestureRecognizerDelegate> {
	CBCloseButton* _closeButton;
	UIView* _transparentView;
	UILabel* _label;
	CBUnderfinedProgressBar* _progressBar;
	UITapGestureRecognizer* _closeButtonTapRecognizer;
	UIViewController* _viewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIViewController* viewController;
@property(retain, nonatomic) UITapGestureRecognizer* closeButtonTapRecognizer;
@property(retain, nonatomic) CBUnderfinedProgressBar* progressBar;
@property(retain, nonatomic) UILabel* label;
@property(retain, nonatomic) UIView* transparentView;
@property(retain, nonatomic) CBCloseButton* closeButton;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)handleCloseButtonTap:(id)tap;
-(id)initWithFrame:(CGRect)frame;
@end

