/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>
#import "wotblitz-Structs.h"
#import "CBNativeMoreAppsTableViewCellProtocol.h"

@class UILabel, UIImage, UIImageView, UIButton, NSString;

@interface CBNativeMoreAppsRegularCell : UITableViewCell <CBNativeMoreAppsTableViewCellProtocol> {
	id _clickCallback;
	UILabel* _nameLabel;
	UILabel* _publisherLabel;
	UILabel* _descriptionLabel;
	UIButton* _clickButton;
	UIImageView* _iconView;
	UIImage* _playImage;
	UIImage* _installImage;
	NSString* _iconBorderColor;
	CGPoint _buttonOffset;
}
@property(copy) id clickCallback;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign) CGPoint buttonOffset;
@property(retain, nonatomic) NSString* iconBorderColor;
@property(retain, nonatomic) UIImage* installImage;
@property(retain, nonatomic) UIImage* playImage;
@property(retain, nonatomic) UIImageView* iconView;
@property(retain, nonatomic) UIButton* clickButton;
@property(retain, nonatomic) UILabel* descriptionLabel;
@property(retain, nonatomic) UILabel* publisherLabel;
@property(retain, nonatomic) UILabel* nameLabel;
+(float)height;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)cellTextLayout:(float)layout;
-(void)cellButtonLayoutHeight:(float)height width:(float)width;
-(void)cellIconLayout;
-(void)layoutSubviews;
-(void)click:(id)click forEvent:(id)event;
-(id)element:(id)element forEvent:(id)event;
-(void)prepareWithCellMeta:(id)cellMeta;
-(void)configureLayoutForIPad;
-(void)configureLayoutForIPhone;
-(void)configureConstantLayoutItems;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

