/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "CBImpressionProtocol.h"
#import "wotblitz-Structs.h"

@class NSString, NSMutableDictionary, Chartboost, NSMutableSet;

@interface CBRewarded : NSObject <CBImpressionProtocol> {
	BOOL _pendingVideo;
	BOOL _adDataWasCached;
	Chartboost* _cb;
	NSMutableDictionary* _pendingRequests;
	NSMutableDictionary* _cachedInterstitials;
	NSMutableSet* _retryCacheLocations;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableSet* retryCacheLocations;
@property(assign, nonatomic) BOOL adDataWasCached;
@property(assign, nonatomic) BOOL pendingVideo;
@property(retain) NSMutableDictionary* cachedInterstitials;
@property(retain) NSMutableDictionary* pendingRequests;
@property(assign, nonatomic) __weak Chartboost* cb;
+(id)allocWithZone:(NSZone*)zone;
+(id)shared;
-(void).cxx_destruct;
-(void)playbackCompleted:(id)completed;
-(void)impressionDisplayed:(id)displayed moreData:(id)data;
-(void)showPlayAnotherPopup:(id)popup;
-(void)showPostInterstitialConfirmationPopup:(id)popup;
-(void)impressionReadyToBeDisplayed:(id)beDisplayed moreData:(id)data;
-(void)impressionReady:(id)ready;
-(void)impressionFailedToInitialize:(id)initialize withError:(unsigned)error;
-(void)impressionCloseTriggered:(id)triggered isDeveloperTriggered:(BOOL)triggered2;
-(void)impressionCloseTriggered:(id)triggered;
-(void)impressionClickTriggered:(id)triggered forURL:(id)url moreData:(id)data deepLinkActive:(BOOL)active withClickCoordinates:(id)clickCoordinates;
-(void)attemptShowingVideo:(id)video;
-(id)removePendingRequest:(id)request;
-(BOOL)hasPendingRequest:(id)request request:(id)request2;
-(void)loadRewardedVideo:(id)video shouldCache:(BOOL)cache skipConfirmation:(BOOL)confirmation forVC:(id)vc sendNow:(BOOL)now;
-(void)loadRewardedVideo:(id)video shouldCache:(BOOL)cache skipConfirmation:(BOOL)confirmation forVC:(id)vc;
-(void)loadRewardedVideo:(id)video shouldCache:(BOOL)cache skipConfirmation:(BOOL)confirmation;
-(void)removeRewardedVideoFromCache:(id)cache;
-(BOOL)hasRewardedVideo:(id)video;
-(void)showRewardedVideo:(id)video location:(id)location skipConfirmation:(BOOL)confirmation;
-(void)showRewardedVideo:(id)video location:(id)location;
-(void)cacheRewardedVideo:(id)video sendNow:(BOOL)now withDelay:(float)delay;
-(void)cacheRewardedVideo:(id)video sendNow:(BOOL)now;
-(void)cacheRewardedVideo:(id)video;
-(void)retryCacheLocationRequests;
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
@end

