//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CBBorderedInsideView;

@interface CBToasterView : UIView
{
    _Bool _visible;
    int _position;
    CBBorderedInsideView *_borderedInsideView;
}

@property(retain, nonatomic) CBBorderedInsideView *borderedInsideView; // @synthesize borderedInsideView=_borderedInsideView;
@property int position; // @synthesize position=_position;
@property(nonatomic) _Bool visible; // @synthesize visible=_visible;
- (void).cxx_destruct;
@property(readonly) UIView *contentView;
- (struct CGPoint)hiddenCenter;
- (struct CGPoint)boundsCenter;
- (void)layoutSubviews;
- (void)hideAnimated:(_Bool)arg1;
- (void)showAnimated:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 inPosition:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

