/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSString, NSNumber, NSMutableArray, NSTimer;

@interface CBTrack : NSObject {
	BOOL _active;
	NSString* _sessionID;
	NSString* _currentFileCacheName;
	NSMutableArray* _events;
	NSNumber* _sessionStartTime;
	NSNumber* _sessionLastTime;
	NSNumber* _sessionCurrentTime;
	NSTimer* _flushTimer;
}
@property(retain, nonatomic) NSTimer* flushTimer;
@property(retain, nonatomic) NSNumber* sessionCurrentTime;
@property(retain, nonatomic) NSNumber* sessionLastTime;
@property(retain, nonatomic) NSNumber* sessionStartTime;
@property(assign, nonatomic) BOOL active;
@property(retain) NSMutableArray* events;
@property(retain) NSString* currentFileCacheName;
@property(retain) NSString* sessionID;
+(id)getSessionID;
+(void)trackRequestEvent:(id)event withKingdom:(id)kingdom withPhylum:(id)phylum withClass:(id)aClass withFamily:(id)family withGenus:(id)genus withMeta:(id)meta;
+(void)trackVideoPlayerControlsToggle:(id)toggle withAdId:(id)adId withValue:(BOOL)value;
+(void)trackVideoPlayerStop:(id)stop withAdId:(id)adId;
+(void)trackVideoPlayerStart:(id)start withAdId:(id)adId withPlayCount:(int)playCount;
+(void)trackVideoPlayerReplay:(id)replay withAdId:(id)adId;
+(void)trackVideoPlayerCloseShow:(id)show withAdId:(id)adId withDelay:(int)delay;
+(void)trackVideoInstallClick:(id)click withVideo:(id)video withAdId:(id)adId withX:(int)x withY:(int)y;
+(void)trackVideoPlayAnotherDismiss:(id)dismiss withAdId:(id)adId withAccept:(BOOL)accept skipConfirmation:(BOOL)confirmation;
+(void)trackVideoConfirmationDismiss:(id)dismiss withAdId:(id)adId withAccept:(BOOL)accept;
+(void)trackVideoConfirmationShow:(id)show withAdId:(id)adId;
+(void)trackVideoPrefetchComplete;
+(void)trackVideoPrefetchDownloadSuccess:(id)success withFilename:(id)filename withTime:(id)time;
+(void)trackVideoPrefetchDownloadFailure:(id)failure withFilename:(id)filename withTime:(id)time withError:(id)error;
+(void)trackVideoPrefetchDownloadStart:(id)start withFilename:(id)filename;
+(void)trackVideoPrefetchSynchronize:(int)synchronize filesAdded:(int)added filesDeleted:(int)deleted;
+(void)trackVideoPrefetchCacheEvent:(id)event withStatus:(id)status withFileId:(id)fileId;
+(void)trackVideoPrefetchBegin;
+(void)trackWebviewEvent:(id)event withEvent:(id)event2 withData:(id)data withMeta:(id)meta forAdUnit:(id)adUnit;
+(void)trackWebviewWarning:(id)warning withEvent:(id)event withData:(id)data withMeta:(id)meta forAdUnit:(id)adUnit;
+(void)trackWebviewError:(id)error withEvent:(id)event withData:(id)data withMeta:(id)meta forAdUnit:(id)adUnit;
+(void)trackAppSheetEvent:(id)event withiTunesId:(id)anId;
+(void)trackClickError:(id)error withLocation:(id)location withErrorId:(unsigned)errorId;
+(void)trackLoadError:(id)error withLocation:(id)location withErrorId:(unsigned)errorId;
+(void)trackAdLoaded:(id)loaded withAdId:(id)adId withCaching:(BOOL)caching;
+(void)trackAdClose:(id)close withLocation:(id)location withAdId:(id)adId;
+(void)trackAdVideoClick:(id)click withLocation:(id)location withAdId:(id)adId withClickType:(id)clickType;
+(void)trackAdMoreAppsClick:(id)click withLocation:(id)location withAdId:(id)adId withRow:(int)row;
+(void)trackAdClick:(id)click withLocation:(id)location withAdId:(id)adId;
+(void)trackAdShow:(id)show withLocation:(id)location withAdId:(id)adId;
+(void)trackAdHas:(id)has withLocation:(id)location withValue:(BOOL)value;
+(void)trackAdGetBatch:(id)batch withLocation:(id)location;
+(void)trackAdGet:(id)get withLocation:(id)location withCaching:(BOOL)caching;
+(void)trackSessionEvent:(id)event;
+(void)trackSessionEnd;
+(void)trackSessionStart;
+(id)allocWithZone:(NSZone*)zone;
+(id)shared;
-(void).cxx_destruct;
-(id)createUUID;
-(id)generateSessionID;
-(id)dictionaryRepresentation;
-(id)generateFileCacheName;
-(void)saveSessionInfo:(id)info currentTime:(id)time;
-(void)saveLatestSessionInfo;
-(void)startNewSession;
-(void)endSession:(BOOL)session;
-(void)endCurrentSession;
-(void)loadOrCreateSessionID;
-(void)appDidEnterBackground;
-(void)appDidBecomeActive;
-(BOOL)skipFile:(id)file;
-(void)flushAllFiles;
-(void)flushFile:(id)file;
-(void)flushNow;
-(void)flush;
-(void)timerFired;
-(id)valueOrString:(id)string;
-(void)trackEventInternal:(id)internal withKingdom:(id)kingdom withPhylum:(id)phylum withClass:(id)aClass withFamily:(id)family withGenus:(id)genus withMeta:(id)meta trackingLevel:(id)level;
-(void)trackEventInternal:(id)internal withKingdom:(id)kingdom withPhylum:(id)phylum withClass:(id)aClass withFamily:(id)family withGenus:(id)genus trackingLevel:(id)level;
-(void)listenForSystemEvents;
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
@end

