//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSNumber, NSString, NSTimer;

@interface CBTrack : NSObject
{
    _Bool _active;
    NSString *_sessionID;
    NSString *_currentFileCacheName;
    NSMutableArray *_events;
    NSNumber *_sessionStartTime;
    NSNumber *_sessionLastTime;
    NSNumber *_sessionCurrentTime;
    NSTimer *_flushTimer;
}

+ (id)getSessionID;
+ (void)trackRequestEvent:(id)arg1 withKingdom:(id)arg2 withPhylum:(id)arg3 withClass:(id)arg4 withFamily:(id)arg5 withGenus:(id)arg6 withMeta:(id)arg7;
+ (void)trackVideoPlayerControlsToggle:(id)arg1 withAdId:(id)arg2 withValue:(_Bool)arg3;
+ (void)trackVideoPlayerStop:(id)arg1 withAdId:(id)arg2;
+ (void)trackVideoPlayerStart:(id)arg1 withAdId:(id)arg2 withPlayCount:(int)arg3;
+ (void)trackVideoPlayerReplay:(id)arg1 withAdId:(id)arg2;
+ (void)trackVideoPlayerCloseShow:(id)arg1 withAdId:(id)arg2 withDelay:(int)arg3;
+ (void)trackVideoInstallClick:(id)arg1 withVideo:(id)arg2 withAdId:(id)arg3 withX:(int)arg4 withY:(int)arg5;
+ (void)trackVideoPlayAnotherDismiss:(id)arg1 withAdId:(id)arg2 withAccept:(_Bool)arg3 skipConfirmation:(_Bool)arg4;
+ (void)trackVideoConfirmationDismiss:(id)arg1 withAdId:(id)arg2 withAccept:(_Bool)arg3;
+ (void)trackVideoConfirmationShow:(id)arg1 withAdId:(id)arg2;
+ (void)trackVideoPrefetchComplete;
+ (void)trackVideoPrefetchDownloadSuccess:(id)arg1 withFilename:(id)arg2 withTime:(id)arg3;
+ (void)trackVideoPrefetchDownloadFailure:(id)arg1 withFilename:(id)arg2 withTime:(id)arg3 withError:(id)arg4;
+ (void)trackVideoPrefetchDownloadStart:(id)arg1 withFilename:(id)arg2;
+ (void)trackVideoPrefetchSynchronize:(int)arg1 filesAdded:(int)arg2 filesDeleted:(int)arg3;
+ (void)trackVideoPrefetchCacheEvent:(id)arg1 withStatus:(id)arg2 withFileId:(id)arg3;
+ (void)trackVideoPrefetchBegin;
+ (void)trackWebviewEvent:(id)arg1 withEvent:(id)arg2 withData:(id)arg3 withMeta:(id)arg4 forAdUnit:(id)arg5;
+ (void)trackWebviewWarning:(id)arg1 withEvent:(id)arg2 withData:(id)arg3 withMeta:(id)arg4 forAdUnit:(id)arg5;
+ (void)trackWebviewError:(id)arg1 withEvent:(id)arg2 withData:(id)arg3 withMeta:(id)arg4 forAdUnit:(id)arg5;
+ (void)trackAppSheetEvent:(id)arg1 withiTunesId:(id)arg2;
+ (void)trackClickError:(id)arg1 withLocation:(id)arg2 withErrorId:(unsigned long long)arg3;
+ (void)trackLoadError:(id)arg1 withLocation:(id)arg2 withErrorId:(unsigned long long)arg3;
+ (void)trackAdLoaded:(id)arg1 withAdId:(id)arg2 withCaching:(_Bool)arg3;
+ (void)trackAdClose:(id)arg1 withLocation:(id)arg2 withAdId:(id)arg3;
+ (void)trackAdVideoClick:(id)arg1 withLocation:(id)arg2 withAdId:(id)arg3 withClickType:(id)arg4;
+ (void)trackAdMoreAppsClick:(id)arg1 withLocation:(id)arg2 withAdId:(id)arg3 withRow:(int)arg4;
+ (void)trackAdClick:(id)arg1 withLocation:(id)arg2 withAdId:(id)arg3;
+ (void)trackAdShow:(id)arg1 withLocation:(id)arg2 withAdId:(id)arg3;
+ (void)trackAdHas:(id)arg1 withLocation:(id)arg2 withValue:(_Bool)arg3;
+ (void)trackAdGetBatch:(id)arg1 withLocation:(id)arg2;
+ (void)trackAdGet:(id)arg1 withLocation:(id)arg2 withCaching:(_Bool)arg3;
+ (void)trackSessionEvent:(id)arg1;
+ (void)trackSessionEnd;
+ (void)trackSessionStart;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
@property(retain, nonatomic) NSTimer *flushTimer; // @synthesize flushTimer=_flushTimer;
@property(retain, nonatomic) NSNumber *sessionCurrentTime; // @synthesize sessionCurrentTime=_sessionCurrentTime;
@property(retain, nonatomic) NSNumber *sessionLastTime; // @synthesize sessionLastTime=_sessionLastTime;
@property(retain, nonatomic) NSNumber *sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(retain) NSMutableArray *events; // @synthesize events=_events;
@property(retain) NSString *currentFileCacheName; // @synthesize currentFileCacheName=_currentFileCacheName;
@property(retain) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;
- (id)createUUID;
- (id)generateSessionID;
- (id)dictionaryRepresentation;
- (id)generateFileCacheName;
- (void)saveSessionInfo:(id)arg1 currentTime:(id)arg2;
- (void)saveLatestSessionInfo;
- (void)startNewSession;
- (void)endSession:(_Bool)arg1;
- (void)endCurrentSession;
- (void)loadOrCreateSessionID;
- (void)appDidEnterBackground;
- (void)appDidBecomeActive;
- (_Bool)skipFile:(id)arg1;
- (void)flushAllFiles;
- (void)flushFile:(id)arg1;
- (void)flushNow;
- (void)flush;
- (void)timerFired;
- (id)valueOrString:(id)arg1;
- (void)trackEventInternal:(id)arg1 withKingdom:(id)arg2 withPhylum:(id)arg3 withClass:(id)arg4 withFamily:(id)arg5 withGenus:(id)arg6 withMeta:(id)arg7 trackingLevel:(id)arg8;
- (void)trackEventInternal:(id)arg1 withKingdom:(id)arg2 withPhylum:(id)arg3 withClass:(id)arg4 withFamily:(id)arg5 withGenus:(id)arg6 trackingLevel:(id)arg7;
- (void)listenForSystemEvents;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

