/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>

@class NSTimer;

@interface CBUnderfinedProgressBar : UIView {
	NSTimer* _timer;
	float _offset;
}
@property(assign, nonatomic) float offset;
@property(retain, nonatomic) NSTimer* timer;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)step:(id)step;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

