//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer;

@interface CBUnderfinedProgressBar : UIView
{
    NSTimer *_timer;
    double _offset;
}

@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)step:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

