/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSURLRequest, NSURL;
@protocol CBUrlOpenerDelegate;

@interface CBURLOpener : NSObject {
	NSURL* lastUrl;
	id<CBUrlOpenerDelegate> delegate;
	NSURLRequest* originalRequest;
}
@property(retain) NSURLRequest* originalRequest;
@property(retain) NSURL* lastUrl;
@property(assign) id<CBUrlOpenerDelegate> delegate;
+(id)openerWithDelegate:(id)delegate;
-(void).cxx_destruct;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(BOOL)open:(id)open;
@end

