/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CBViewProtocol <NSObject>
@property(readonly, assign) unsigned supportedOrientations;
@property(assign) int orientation;
@property(copy) id failCallback;
@property(copy) id playbackCompletedCallback;
@property(copy) id displayCallback;
@property(copy) id readyToDisplayCallback;
@property(copy) id clickCallback;
@property(copy) id closeCallback;
-(void)audioRouteHeadphones;
-(void)audioRoutePhoneCall;
-(void)audioInterruptShouldResume;
-(BOOL)shouldAdjustFrameForStatusBar;
-(void)destroy;
-(id)prepareWithResponse:(id)response;
-(BOOL)canDisplay;
@end

