//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Chartboost, NSMutableArray, NSMutableDictionary;

@interface CBVideoPrefetcher : NSObject
{
    _Bool _complete;
    unsigned long long _state;
    unsigned long long _completedDownloads;
    unsigned long long _failedDownloads;
    unsigned long long _totalDownloads;
    unsigned long long _initialDelayIntervalInSeconds;
    unsigned long long _maxDelayIntervalInSeconds;
    unsigned long long _backoffFactor;
    unsigned long long _currentDelay;
    Chartboost *_cb;
    NSMutableDictionary *_templateMap;
    NSMutableDictionary *_cacheFileMap;
    NSMutableArray *_cacheFileArray;
    NSMutableDictionary *_pendingDownloads;
}

+ (id)cacheFolder:(id)arg1;
+ (id)cacheFolder;
+ (id)temporaryFolder;
+ (void)cleanFolder:(id)arg1;
+ (void)cleanFolders;
+ (void)createFolder:(id)arg1;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
@property(retain, nonatomic) NSMutableDictionary *pendingDownloads; // @synthesize pendingDownloads=_pendingDownloads;
@property(retain, nonatomic) NSMutableArray *cacheFileArray; // @synthesize cacheFileArray=_cacheFileArray;
@property(retain, nonatomic) NSMutableDictionary *cacheFileMap; // @synthesize cacheFileMap=_cacheFileMap;
@property(retain, nonatomic) NSMutableDictionary *templateMap; // @synthesize templateMap=_templateMap;
@property(nonatomic) __weak Chartboost *cb; // @synthesize cb=_cb;
@property(nonatomic) unsigned long long currentDelay; // @synthesize currentDelay=_currentDelay;
@property(nonatomic) unsigned long long backoffFactor; // @synthesize backoffFactor=_backoffFactor;
@property(nonatomic) unsigned long long maxDelayIntervalInSeconds; // @synthesize maxDelayIntervalInSeconds=_maxDelayIntervalInSeconds;
@property(nonatomic) unsigned long long initialDelayIntervalInSeconds; // @synthesize initialDelayIntervalInSeconds=_initialDelayIntervalInSeconds;
@property(nonatomic) unsigned long long totalDownloads; // @synthesize totalDownloads=_totalDownloads;
@property(nonatomic) unsigned long long failedDownloads; // @synthesize failedDownloads=_failedDownloads;
@property(nonatomic) unsigned long long completedDownloads; // @synthesize completedDownloads=_completedDownloads;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic, getter=isComplete) _Bool complete; // @synthesize complete=_complete;
- (void).cxx_destruct;
- (unsigned long long)folderSize:(id)arg1;
- (long long)getVideoCacheSize;
- (id)getBaseURL;
- (id)getTemplateHTML:(id)arg1;
- (_Bool)isTemplateFailed:(id)arg1;
- (_Bool)isTemplateReady:(id)arg1;
- (id)localAssets:(_Bool)arg1;
- (id)localVideos;
- (id)videoURLWithID:(id)arg1 localFile:(id)arg2;
- (void)trackFileDownloadTime:(double)arg1 filename:(id)arg2 URL:(id)arg3 success:(_Bool)arg4 error:(id)arg5;
- (void)updateStateForDownload;
- (void)fileDownloadFail:(id)arg1 toPath:(id)arg2;
- (void)downloadSuccess:(id)arg1 toPath:(id)arg2;
- (void)fileDownloadSuccess:(id)arg1 toPath:(id)arg2;
- (id)getNetworkStatus;
- (void)downloadDataFromURL:(id)arg1 toFilename:(id)arg2 toPath:(id)arg3 priority:(long long)arg4;
- (void)downloadVideo:(id)arg1;
- (void)downloadFile:(id)arg1 priority:(long long)arg2;
- (void)synchronizeLocalVideosWithNewList:(id)arg1 keepVideos:(id)arg2;
- (id)readDictionary:(id)arg1 path:(id)arg2;
- (void)writeDictionary:(id)arg1 toFile:(id)arg2 path:(id)arg3;
- (void)removeFile:(id)arg1 path:(id)arg2;
- (void)checkComplete;
- (void)updateLocalAssetsWithNewDict:(id)arg1;
- (unsigned long long)updateLocalAssetsCategory:(id)arg1 data:(id)arg2;
- (unsigned long long)updateLocalAssetsTemplates:(id)arg1;
- (id)createTemplateForAd:(id)arg1 adId:(id)arg2 data:(id)arg3;
- (_Bool)copyTemplateFiles:(id)arg1 toPath:(id)arg2;
- (unsigned long long)markTemplateRequired:(id)arg1;
- (unsigned long long)markAssetRequired:(id)arg1;
- (void)deleteTemplates;
- (void)removeAdTemplate:(id)arg1;
- (void)cleanupAssets;
- (void)doPrefetch;
- (void)prefetchVideos:(_Bool)arg1;
- (void)prefetchVideos;
- (unsigned long long)processTemplateElements:(id)arg1 forTemplate:(id)arg2;
- (void)sortAssets;
- (void)createAssetsFromDisk;
- (void)createAssetsForDirectory:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

