/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSMutableDictionary, Chartboost, NSMutableArray;

@interface CBVideoPrefetcher : NSObject {
	BOOL _complete;
	unsigned _state;
	unsigned _completedDownloads;
	unsigned _failedDownloads;
	unsigned _totalDownloads;
	unsigned _initialDelayIntervalInSeconds;
	unsigned _maxDelayIntervalInSeconds;
	unsigned _backoffFactor;
	unsigned _currentDelay;
	Chartboost* _cb;
	NSMutableDictionary* _templateMap;
	NSMutableDictionary* _cacheFileMap;
	NSMutableArray* _cacheFileArray;
	NSMutableDictionary* _pendingDownloads;
}
@property(retain, nonatomic) NSMutableDictionary* pendingDownloads;
@property(retain, nonatomic) NSMutableArray* cacheFileArray;
@property(retain, nonatomic) NSMutableDictionary* cacheFileMap;
@property(retain, nonatomic) NSMutableDictionary* templateMap;
@property(assign, nonatomic) __weak Chartboost* cb;
@property(assign, nonatomic) unsigned currentDelay;
@property(assign, nonatomic) unsigned backoffFactor;
@property(assign, nonatomic) unsigned maxDelayIntervalInSeconds;
@property(assign, nonatomic) unsigned initialDelayIntervalInSeconds;
@property(assign, nonatomic) unsigned totalDownloads;
@property(assign, nonatomic) unsigned failedDownloads;
@property(assign, nonatomic) unsigned completedDownloads;
@property(assign, nonatomic) unsigned state;
@property(assign, nonatomic, getter=isComplete) BOOL complete;
+(id)cacheFolder:(id)folder;
+(id)cacheFolder;
+(id)temporaryFolder;
+(void)cleanFolder:(id)folder;
+(void)cleanFolders;
+(void)createFolder:(id)folder;
+(void)initialize;
+(id)allocWithZone:(NSZone*)zone;
+(id)shared;
-(void).cxx_destruct;
-(unsigned long long)folderSize:(id)size;
-(long long)getVideoCacheSize;
-(id)getBaseURL;
-(id)getTemplateHTML:(id)html;
-(BOOL)isTemplateFailed:(id)failed;
-(BOOL)isTemplateReady:(id)ready;
-(id)localAssets:(BOOL)assets;
-(id)localVideos;
-(id)videoURLWithID:(id)anId localFile:(id)file;
-(void)trackFileDownloadTime:(double)time filename:(id)filename URL:(id)url success:(BOOL)success error:(id)error;
-(void)updateStateForDownload;
-(void)fileDownloadFail:(id)fail toPath:(id)path;
-(void)downloadSuccess:(id)success toPath:(id)path;
-(void)fileDownloadSuccess:(id)success toPath:(id)path;
-(id)getNetworkStatus;
-(void)downloadDataFromURL:(id)url toFilename:(id)filename toPath:(id)path priority:(int)priority;
-(void)downloadVideo:(id)video;
-(void)downloadFile:(id)file priority:(int)priority;
-(void)synchronizeLocalVideosWithNewList:(id)newList keepVideos:(id)videos;
-(id)readDictionary:(id)dictionary path:(id)path;
-(void)writeDictionary:(id)dictionary toFile:(id)file path:(id)path;
-(void)removeFile:(id)file path:(id)path;
-(void)checkComplete;
-(void)updateLocalAssetsWithNewDict:(id)newDict;
-(unsigned)updateLocalAssetsCategory:(id)category data:(id)data;
-(unsigned)updateLocalAssetsTemplates:(id)templates;
-(id)createTemplateForAd:(id)ad adId:(id)anId data:(id)data;
-(BOOL)copyTemplateFiles:(id)files toPath:(id)path;
-(unsigned)markTemplateRequired:(id)required;
-(unsigned)markAssetRequired:(id)required;
-(void)deleteTemplates;
-(void)removeAdTemplate:(id)aTemplate;
-(void)cleanupAssets;
-(void)doPrefetch;
-(void)prefetchVideos:(BOOL)videos;
-(void)prefetchVideos;
-(unsigned)processTemplateElements:(id)elements forTemplate:(id)aTemplate;
-(void)sortAssets;
-(void)createAssetsFromDisk;
-(void)createAssetsForDirectory:(id)directory;
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
@end

