/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CLSEventLogEvent.h"

@class NSDictionary;

@interface CLSAnalyticsMetadataEvent : CLSEventLogEvent {
}
@property(readonly, copy, nonatomic) NSDictionary* metadataJSONData;
-(id)initWithPriority:(unsigned)priority timestamp:(unsigned long long)timestamp key:(id)key payload:(id)payload;
-(id)initWithPriority:(unsigned)priority timestamp:(unsigned long long)timestamp metadataJSONData:(id)data;
@end

