/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CLSAnswersEvent.h"


@interface CLSAnswersPredefinedEvent : CLSAnswersEvent {
}
+(id)serializeNSNumberAsInteger:(id)integer;
+(id)serializePriceToMicros:(id)micros;
+(id)serializeSuccess:(id)success;
-(id)description;
-(void)addPredefinedString:(id)string forKey:(id)key;
-(void)addPredefinedNumber:(id)number forKey:(id)key;
-(void)addPredefinedAttribute:(id)attribute forKey:(id)key;
-(id)initWithPredefinedEventType:(id)predefinedEventType customAttributes:(id)attributes;
@end

