/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CLSAnalyticsEvent.h"


@interface CLSAnalyticsViewControllerEvent : CLSAnalyticsEvent {
}
-(id)initWithDisappearedEventForViewController:(id)viewController timestamp:(unsigned long long)timestamp eventIdentifier:(id)identifier;
-(id)initWithAppearedEventForViewController:(id)viewController timestamp:(unsigned long long)timestamp eventIdentifier:(id)identifier;
-(id)initWithEventForViewController:(id)viewController eventKey:(id)key timestamp:(unsigned long long)timestamp eventIdentifier:(id)identifier;
@end

