/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSURL;

@interface CLSBetaUpdate : NSObject {
	NSURL* _url;
	NSString* _version;
}
@property(readonly, copy, nonatomic) NSString* installLabel;
@property(readonly, copy, nonatomic) NSString* cancelLabel;
@property(readonly, copy, nonatomic) NSString* promptMessage;
@property(readonly, copy, nonatomic) NSString* promptTitle;
@property(readonly, copy, nonatomic) NSString* version;
@property(readonly, assign, nonatomic) NSURL* url;
+(id)betaUpdateWithDictionary:(id)dictionary error:(id*)error;
-(void).cxx_destruct;
-(id)initWithDictionary:(id)dictionary;
@end

