/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSData;

@interface CLSEventLogEvent : NSObject {
	unsigned _priority;
	unsigned long long _timestamp;
	NSString* _key;
	NSData* _payload;
}
@property(readonly, copy, nonatomic) NSData* payload;
@property(readonly, copy, nonatomic) NSString* key;
@property(readonly, assign, nonatomic) unsigned long long timestamp;
@property(readonly, assign, nonatomic) unsigned priority;
-(id)eventData;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)initWithPriority:(unsigned)priority timestamp:(unsigned long long)timestamp key:(id)key;
-(id)initWithPriority:(unsigned)priority timestamp:(unsigned long long)timestamp key:(id)key payload:(id)payload;
-(void)dealloc;
@end

