/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>

@class NSMutableArray;

@interface CLSSymbolResolver : NSObject {
	NSMutableArray* _binaryImages;
}
-(void).cxx_destruct;
-(BOOL)updateStackFrame:(id)frame;
-(id)frameForAddress:(unsigned long long)address;
-(BOOL)fillInImageDetails:(XXStruct_sUoPdA*)imageDetails forUUID:(id)uuid;
-(id)loadedBinaryImageForPC:(unsigned long)pc;
-(BOOL)loadBinaryImagesFromFile:(id)file;
-(id)init;
@end

