/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSURLRequest, NSError, NSURLResponse;
@protocol OS_dispatch_queue, CLSURLSessionTaskDelegate;

@interface CLSURLSessionTask : NSObject {
	id<CLSURLSessionTaskDelegate> _delegate;
	NSURLRequest* _originalRequest;
	NSURLRequest* _currentRequest;
	NSURLResponse* _response;
	NSError* _error;
	NSObject<OS_dispatch_queue>* _queue;
	BOOL _invokesDelegate;
}
@property(assign, nonatomic) BOOL invokesDelegate;
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* queue;
@property(assign, nonatomic) id<CLSURLSessionTaskDelegate> delegate;
@property(copy, nonatomic) NSError* error;
@property(copy, nonatomic) NSURLResponse* response;
@property(copy, nonatomic) NSURLRequest* currentRequest;
@property(copy, nonatomic) NSURLRequest* originalRequest;
+(id)task;
-(void).cxx_destruct;
-(void)cleanup;
-(void)resume;
-(void)cancel;
-(void)start;
-(id)init;
@end

