/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FABAsyncOperation.h"

@class NSArray, NSObject, NSOperationQueue, NSMutableArray;
@protocol OS_dispatch_queue;

@interface FABCompoundOperation : FABAsyncOperation {
	NSArray* _operations;
	NSOperationQueue* _compoundQueue;
	unsigned _completedOperations;
	NSMutableArray* _errors;
	NSObject<OS_dispatch_queue>* _countingQueue;
}
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* countingQueue;
@property(retain, nonatomic) NSMutableArray* errors;
@property(assign, nonatomic) unsigned completedOperations;
@property(retain, nonatomic) NSOperationQueue* compoundQueue;
@property(copy, nonatomic) NSArray* operations;
-(void).cxx_destruct;
-(void)attemptCompoundCompletionWithCompletedOperations:(unsigned)completedOperations;
-(unsigned)updateCompletionCountsWithError:(id)error;
-(void)addCompoundCompletionCheckToOriginalCompletion:(id)originalCompletion operation:(id)operation;
-(void)cancel;
-(void)main;
-(id)init;
@end

