/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FABObfuscator : NSObject {
}
+(id)dictionaryWithObfuscatedData:(id)obfuscatedData;
+(id)obfuscatedDataFromDictionary:(id)dictionary;
@end

