/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSNumber, NSFileManager, NSDictionary;

@interface FABSettings : NSObject {
	BOOL _reportingEnabled;
	BOOL _errorReportingEnabled;
	NSDictionary* _settingsDictionary;
	NSNumber* _logBufferSize;
	NSNumber* _maxErrors;
	NSNumber* _maxCustomKeys;
	NSString* _settingsPath;
	NSFileManager* _fileManager;
}
@property(retain, nonatomic) NSFileManager* fileManager;
@property(retain, nonatomic) NSString* settingsPath;
@property(readonly, assign, nonatomic) NSNumber* maxCustomKeys;
@property(readonly, assign, nonatomic) NSNumber* maxErrors;
@property(readonly, assign, nonatomic) NSNumber* logBufferSize;
@property(readonly, assign, nonatomic) BOOL errorReportingEnabled;
@property(readonly, assign, nonatomic) BOOL reportingEnabled;
@property(readonly, assign, nonatomic) BOOL appUpdateRequired;
@property(readonly, assign, nonatomic) BOOL appNeedsOnboarding;
@property(retain, nonatomic) NSDictionary* settingsDictionary;
-(void).cxx_destruct;
-(id)settingsURLForEndpoint:(id)endpoint appInstanceIdentifer:(id)identifer appIconHash:(id)hash;
-(void)clearSettingsDictionary;
-(id)appStatus;
-(id)appSettings;
-(id)appSource;
-(id)appDisplayVersion;
-(id)appBuildVersion;
-(id)appPlatform;
-(id)appBundleIdentifier;
-(id)initWithSettingsPath:(id)settingsPath fileManager:(id)manager;
@end

