/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>

@class UIColor;

@interface FBAdStarRatingView : UIView {
	UIColor* _primaryColor;
	UIColor* _secondaryColor;
	float _xCenter;
	float _yCenter;
	float _xIncrement;
	float _width;
	FBAdStarRating _rating;
	CGPoint _farthestPoint;
}
@property(assign, nonatomic) float width;
@property(assign, nonatomic) float xIncrement;
@property(assign, nonatomic) float yCenter;
@property(assign, nonatomic) float xCenter;
@property(assign, nonatomic) CGPoint farthestPoint;
@property(retain, nonatomic) UIColor* secondaryColor;
@property(retain, nonatomic) UIColor* primaryColor;
@property(assign, nonatomic) FBAdStarRating rating;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)updateDrawingAttributesFromSize:(CGSize)size;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame withStarRating:(FBAdStarRating)starRating;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
@end

