/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "wotblitz-Structs.h"
#import "FBAdUpdatableView.h"

@class UILabel, FBNativeAd, FBAdTimer, FBNativeAdViewAttributes, NSString, FBCombinedSecondaryView;

@interface FBAdBodyView : UIView <FBAdUpdatableView> {
	BOOL _ratingEnabled;
	BOOL _socialContextEnabled;
	BOOL _animationEnabled;
	BOOL _fullRatingView;
	BOOL _rotated;
	FBNativeAd* _nativeAd;
	UILabel* _titleLabel;
	UILabel* _descriptionLabel;
	UILabel* _socialContextLabel;
	float _additionalYSpacing;
	FBAdTimer* _rotationTimer;
	UIView* _firstContainerView;
	UIView* _secondContainerView;
	float _miscMargin;
	float _titleHeight;
	FBNativeAdViewAttributes* _attributes;
	FBCombinedSecondaryView* _secondaryCombinedView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak FBCombinedSecondaryView* secondaryCombinedView;
@property(assign, nonatomic) __weak FBNativeAdViewAttributes* attributes;
@property(assign, nonatomic) float titleHeight;
@property(assign, nonatomic) float miscMargin;
@property(assign, nonatomic) __weak UIView* secondContainerView;
@property(assign, nonatomic) __weak UIView* firstContainerView;
@property(assign, nonatomic, getter=isRotated) BOOL rotated;
@property(retain, nonatomic) FBAdTimer* rotationTimer;
@property(assign, nonatomic, getter=isFullRatingView) BOOL fullRatingView;
@property(assign, nonatomic) float additionalYSpacing;
@property(assign, nonatomic, getter=isAnimationEnabled) BOOL animationEnabled;
@property(assign, nonatomic, getter=isSocialContextEnabled) BOOL socialContextEnabled;
@property(assign, nonatomic, getter=isRatingEnabled) BOOL ratingEnabled;
@property(assign, nonatomic) __weak UILabel* socialContextLabel;
@property(assign, nonatomic) __weak UILabel* descriptionLabel;
@property(assign, nonatomic) __weak UILabel* titleLabel;
@property(assign, nonatomic) __weak FBNativeAd* nativeAd;
-(void).cxx_destruct;
-(CGRect)spareSpace;
-(void)sizeToFit;
-(void)dealloc;
-(void)updateBodyTitle:(id)title;
-(BOOL)socialContextEnabled;
-(BOOL)ratingEnabled;
-(void)animateRotationWithCurrentView:(id)currentView otherView:(id)view;
-(void)rotate;
-(void)willMoveToWindow:(id)window;
-(CGRect)offscreenFrame;
-(CGRect)animationFrame;
-(CGRect)normalFrame;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)updateView:(BOOL)view;
-(void)calculateValues;
-(id)initWithFrame:(CGRect)frame nativeAd:(id)ad attributes:(id)attributes;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
@end

