//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBAdUtility.h"

@interface FBAdUtility (FBAdQueryUtility)
+ (id)attemptRecoveryOfObject:(id)arg1 ofClass:(Class)arg2;
+ (void)checkAppTransportSecuritySettings;
+ (id)getJSONStringFromObject:(id)arg1;
+ (id)urlDecode:(id)arg1;
+ (id)urlEncode:(id)arg1;
+ (id)cleanUserAgentString:(id)arg1;
+ (id)generateUserAgentStringFromRawString:(id)arg1;
+ (void)currentUserAgentWithBlock:(CDUnknownBlockType)arg1;
+ (id)currentLocale;
+ (id)createQueryStringFromParameters:(id)arg1;
+ (id)createQueryParameterFromKey:(id)arg1 object:(id)arg2;
+ (id)parseQueryString:(id)arg1;
@end

