/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIViewController.h>

@class UIButton, FBAdVideoView, NSString, UINavigationBar, FBAdTimer;
@protocol FBAdFullscreenVideoControllerDelegate;

@interface FBAdFullscreenVideoController : UIViewController {
	id<FBAdFullscreenVideoControllerDelegate> _delegate;
	NSString* _callToAction;
	id _callToActionBlock;
	FBAdVideoView* _videoView;
	UIButton* _dismissButton;
	UIButton* _callToActionButton;
	UINavigationBar* _videoNavigationBar;
	FBAdTimer* _disappearanceTimer;
}
@property(retain, nonatomic) FBAdTimer* disappearanceTimer;
@property(assign, nonatomic) __weak UINavigationBar* videoNavigationBar;
@property(assign, nonatomic) __weak UIButton* callToActionButton;
@property(assign, nonatomic) __weak UIButton* dismissButton;
@property(assign, nonatomic) __weak FBAdVideoView* videoView;
@property(readonly, assign, nonatomic) XXStruct_pwHToB currentTime;
@property(copy, nonatomic) id callToActionBlock;
@property(retain, nonatomic) NSString* callToAction;
@property(assign, nonatomic) __weak id<FBAdFullscreenVideoControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)viewDidLayoutSubviews;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)callToActionHit:(id)actionHit withEvent:(id)event;
-(void)dismiss:(id)dismiss;
-(void)generateDisappearanceTimer;
-(void)gestureRecognizerDidTap:(id)gestureRecognizer;
-(void)playMovieWithURL:(id)url;
-(void)viewDidLoad;
@end

