/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import "FBNativeAdTemplateView.h"


@interface FBAdGenericHeight300View : FBNativeAdTemplateView {
}
-(id)fixedHeight;
-(void)updateView:(BOOL)view;
@end

