/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SKStoreProductViewControllerDelegate.h"
#import "FBAdSafariViewControllerDelegate.h"
#import </libobjc.A.h>
#import "FBInterstitialAdDelegate.h"

@class NSDate, FBAdDataModel, FBInterstitialAdInternal, SKStoreProductViewController, NSString;
@protocol FBAdCommandProcessorDelegate;

@interface FBAdCommandProcessor : NSObject <SKStoreProductViewControllerDelegate, FBAdSafariViewControllerDelegate, FBInterstitialAdDelegate> {
	BOOL _hideStatusBarOnStoreViewController;
	id<FBAdCommandProcessorDelegate> _delegate;
	FBAdDataModel* _adDataModel;
	id _completionHandler;
	FBInterstitialAdInternal* _interstitialAd;
	NSDate* _lastActionStartTime;
	int _lastAdAction;
	SKStoreProductViewController* _productViewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak SKStoreProductViewController* productViewController;
@property(assign, nonatomic) int lastAdAction;
@property(retain, nonatomic) NSDate* lastActionStartTime;
@property(retain, nonatomic) FBInterstitialAdInternal* interstitialAd;
@property(copy, nonatomic) id completionHandler;
@property(retain, nonatomic) FBAdDataModel* adDataModel;
@property(assign, nonatomic) BOOL hideStatusBarOnStoreViewController;
@property(assign, nonatomic) __weak id<FBAdCommandProcessorDelegate> delegate;
+(void)sendBouncebackInfo:(id)info withAdAction:(int)adAction withRequestId:(id)requestId;
+(BOOL)shouldInvalidate:(id)invalidate;
-(void).cxx_destruct;
-(void)interstitialAdDidClose:(id)interstitialAd;
-(BOOL)showInterstitialAd;
-(void)viewControllerDismissed:(id)dismissed;
-(void)viewControllerCompleted:(id)completed;
-(void)productViewControllerDidFinish:(id)productViewController;
-(BOOL)isValidViewController:(id)controller;
-(void)doneCommandProcessing;
-(void)callCompletionHandlerForCommand:(int)command withAdAction:(int)adAction;
-(BOOL)launchURLOutOfApp:(id)app withAdAction:(int)adAction;
-(BOOL)openLinkInApp:(id)app;
-(BOOL)preloadProductViewControllerIfAvailable:(id)available;
-(BOOL)launchAppForEngagement:(id)engagement;
-(BOOL)processCommand:(id)command adDataModel:(id)model completionHandler:(id)handler;
-(void)dealloc;
@end

