/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"
#import "wotblitz-Structs.h"
#import </libobjc.A.h>
#import "FBAdContentContainer.h"

@class FBAdViewInternal, FBAdDataModel, NSString;
@protocol FBAdContentContainerDelegate;

@protocol FBAdContentContainer <NSObject>
@property(assign, nonatomic) CGSize maximumSize;
@property(assign, nonatomic) CGSize minimumSize;
@property(retain, nonatomic) FBAdDataModel* offsiteAd;
@property(assign, nonatomic) FBAdSize adSizeType;
@property(assign, nonatomic) CGSize actualAdSize;
@property(assign, nonatomic) __weak FBAdViewInternal* parent;
@property(assign, nonatomic) __weak NSObject<FBAdContentContainerDelegate>* delegate;
-(BOOL)logClickWithExtraData:(id)extraData;
-(BOOL)logImpression;
-(BOOL)loadAdData:(id)data minViewability:(int)viewability;
-(id)getView;
-(void)setFrame:(CGRect)frame;
-(id)initWithAdView:(id)adView actualAdSize:(CGSize)size adSizeType:(FBAdSize)type;
@optional
-(BOOL)loadAdMarkup:(id)markup activationCommand:(id)command;
@end

@interface FBAdContentContainer : NSObject <FBAdContentContainer> {
	FBAdViewInternal* _parent;
	NSObject<FBAdContentContainerDelegate>* _delegate;
	FBAdDataModel* _offsiteAd;
	CGSize _actualAdSize;
	FBAdSize _adSizeType;
	CGSize _minimumSize;
	CGSize _maximumSize;
}
@property(assign, nonatomic) CGSize maximumSize;
@property(assign, nonatomic) CGSize minimumSize;
@property(retain, nonatomic) FBAdDataModel* offsiteAd;
@property(assign, nonatomic) FBAdSize adSizeType;
@property(assign, nonatomic) CGSize actualAdSize;
@property(assign, nonatomic) __weak FBAdViewInternal* parent;
@property(assign, nonatomic) __weak NSObject<FBAdContentContainerDelegate>* delegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)logClickWithExtraData:(id)extraData;
-(BOOL)logImpression;
-(BOOL)loadAdData:(id)data minViewability:(int)viewability;
-(id)getView;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithAdView:(id)adView actualAdSize:(CGSize)size adSizeType:(FBAdSize)type;
@end

