/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UISlider.h>

@class UIView;

@interface FBAdVideoScrubber : UISlider {
	UIView* _trackView;
	UIView* _trackMinView;
	UIView* _trackLoadingView;
	UIView* _trackMaxView;
	float _currentScrubberHeight;
	float _currentInset;
	float _playableDuration;
	float _trackInsetWhileScrubbing;
	float _hitAreaBelowScrubber;
}
@property(assign, nonatomic) float hitAreaBelowScrubber;
@property(assign, nonatomic) float trackInsetWhileScrubbing;
@property(assign, nonatomic) float playableDuration;
-(void).cxx_destruct;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)_scrubberIsNotBeingUsed:(id)used;
-(void)_scrubberIsBeingUsed:(id)used;
-(id)_imageWithColor:(id)color;
-(id)_imageWithColor:(id)color andSize:(CGRect)size;
-(void)_updateTrackLoadingViewFrame;
-(void)setPlayableDuration:(float)duration animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

