/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBAdViewDelegate <NSObject>
@optional
-(id)viewControllerForPresentingModalView;
-(void)adViewWillLogImpression:(id)adView;
-(void)adView:(id)view didFailWithError:(id)error;
-(void)adViewDidLoad:(id)adView;
-(void)adViewDidFinishHandlingClick:(id)adView;
-(void)adViewDidClick:(id)adView;
@end

