/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSURLSessionTask, NSDate;

@interface FBAdURLSessionTaskContainer : NSObject {
	NSURLSessionTask* _task;
	NSDate* _requestStart;
}
@property(retain, nonatomic) NSDate* requestStart;
@property(readonly, assign) int state;
@property(retain, nonatomic) NSURLSessionTask* task;
-(void).cxx_destruct;
-(void)cancel;
-(id)init;
@end

