/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBAdContentContainer.h"
#import "wotblitz-Structs.h"
#import "UIWebViewDelegate.h"

@class UIWebView, FBHTMLAdDataModel, NSString, NSURL;

@interface FBAdWebContentContainer : FBAdContentContainer <UIWebViewDelegate> {
	BOOL _isJavascriptAdControlInitialized;
	BOOL _isInterstitial;
	UIWebView* _webView;
	NSString* _activationCommand;
	NSURL* _requestURL;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL isInterstitial;
@property(copy, nonatomic) NSURL* requestURL;
@property(assign, nonatomic) BOOL isJavascriptAdControlInitialized;
@property(retain, nonatomic) FBHTMLAdDataModel* offsiteAd;
@property(copy, nonatomic) NSString* activationCommand;
@property(retain, nonatomic) UIWebView* webView;
-(void).cxx_destruct;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(BOOL)logClickWithExtraData:(id)extraData;
-(BOOL)logImpression;
-(void)initializeJavascriptAdControl;
-(BOOL)loadAdMarkup:(id)markup activationCommand:(id)command;
-(BOOL)loadAdData:(id)data minViewability:(int)viewability;
-(id)getView;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithAdView:(id)adView actualAdSize:(CGSize)size adSizeType:(FBAdSize)type;
@end

