//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdAdapterManager : NSObject
{
}

+ (id)adapterInstanceForId:(id)arg1 placementType:(long long)arg2;
+ (id)availableAdaptersForPlacementType:(long long)arg1;
+ (Class)classForId:(id)arg1 placementType:(long long)arg2;
+ (id)builtInClassesForPlacementType:(long long)arg1;
+ (id)classNameForId:(id)arg1 placementType:(long long)arg2;
+ (id)registeredAdapters;

@end

