//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdScreen : NSObject
{
}

+ (struct CGRect)statusBarFrameInOrientation;
+ (struct CGRect)statusBarFrame;
+ (struct CGSize)sizeInOrientation;
+ (struct CGRect)boundsInOrientation;
+ (long long)orientation;
+ (struct CGSize)size;
+ (double)nativeScale;
+ (double)scale;
+ (void)recomputeCachedState;
+ (void)initialize;

@end

