//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBAdVideoView, NSString, UIButton, UIEvent;

@protocol FBAdVideoViewDelegate <NSObject>
- (void)videoViewDidTapCallToAction:(FBAdVideoView *)arg1 withButton:(UIButton *)arg2 withEvent:(UIEvent *)arg3;
- (NSString *)videoViewCallToActionText:(FBAdVideoView *)arg1;
- (void)videoViewTapped:(FBAdVideoView *)arg1;
- (void)videoViewDidLoad:(FBAdVideoView *)arg1;
@end

