//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@class UIViewController;

@interface FBAdViewControllerProxy : NSProxy
{
    UIViewController *_viewController;
}

+ (id)viewController;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)currentViewController;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)initWithViewController:(id)arg1;

@end

