/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBAdError : NSObject {
}
+(id)getNSError:(int)error description:(id)description detail:(id)detail;
+(id)getErrorFromJSON:(id)json withCode:(int)code description:(id)description detail:(id)detail;
+(id)getNSError:(int)error detail:(id)detail;
+(id)getNSError:(int)error description:(id)description;
+(id)getNSError:(int)error;
+(id)defaultDescriptions;
@end

