/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import "NSObject.h"


@protocol FBAdFullscreenVideoControllerDelegate <NSObject>
-(void)videoControllerDismissed:(id)dismissed;
-(void)videoController:(id)controller videoTimeCheckTriggered:(XXStruct_pwHToB)triggered;
-(void)videoController:(id)controller periodicTimerTriggered:(XXStruct_pwHToB)triggered;
@end

