/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBAdAnalogInfo : NSObject {
}
+(void)updateMotionData;
+(id)getMotionDataInfo;
+(id)getInfo;
+(void)initialize;
@end

