//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdSafariViewController : NSObject
{
}

+ (void)presentSafariViewControllerWithURL:(id)arg1 withRootViewController:(id)arg2 withDelegate:(id)arg3;
+ (_Bool)supportsWebKit;
+ (_Bool)supportsSafariServices;

@end

