/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBAdAdapterManager : NSObject {
}
+(id)adapterInstanceForId:(id)anId placementType:(int)type;
+(id)availableAdaptersForPlacementType:(int)placementType;
+(Class)classForId:(id)anId placementType:(int)type;
+(id)builtInClassesForPlacementType:(int)placementType;
+(id)classNameForId:(id)anId placementType:(int)type;
+(id)registeredAdapters;
@end

