/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>


@interface FBAdPerformanceMetrics : NSObject {
}
+(BOOL)getNetworkUsage:(FBNetworkUsage*)usage;
+(BOOL)lastWakeTime:(double*)time;
+(BOOL)absoluteStartTime:(double*)time;
+(BOOL)getCPUTimeSeconds:(id)seconds terminatedThreads:(FBAdDeviceCPUTime*)threads;
+(unsigned long long)freeDiskCount;
+(unsigned long long)virtualMemoryCount;
+(unsigned long long)residentMemoryCount;
+(unsigned long long)totalMemoryCount;
+(unsigned long long)freeMemoryCount;
+(id)batteryStateWithDeviceBatteryState:(int)deviceBatteryState;
+(FBAdDeviceBatteryInfo)batteryInfo;
+(id)loadAvgWithPrecision:(double)precision;
+(unsigned)coreCount;
@end

