//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdPlacementDefinition : NSObject
{
    _Bool _cacheable;
    long long _type;
    long long _minViewabilityPercentage;
    long long _refreshInterval;
    long long _refreshThreshold;
    long long _requestTimeout;
    struct FBAdSize _placementSize;
}

@property(nonatomic, getter=isCacheable) _Bool cacheable; // @synthesize cacheable=_cacheable;
@property(nonatomic) struct FBAdSize placementSize; // @synthesize placementSize=_placementSize;
@property(nonatomic) long long requestTimeout; // @synthesize requestTimeout=_requestTimeout;
@property(nonatomic) long long refreshThreshold; // @synthesize refreshThreshold=_refreshThreshold;
@property(nonatomic) long long refreshInterval; // @synthesize refreshInterval=_refreshInterval;
@property(nonatomic) long long minViewabilityPercentage; // @synthesize minViewabilityPercentage=_minViewabilityPercentage;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void)ingestPlacementData:(id)arg1;
- (id)initWithPlacementData:(id)arg1;
- (id)init;

@end

