//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdSafariDelegateTranslator : NSObject
{
    id _safariViewController;
    id <FBAdSafariViewControllerDelegate> _delegate;
}

+ (void)setNotificationCenter:(id)arg1 forObject:(id)arg2;
+ (id)translatorForObject:(id)arg1 update:(_Bool)arg2;
+ (id)translatorForObject:(id)arg1;
@property(nonatomic) __weak id <FBAdSafariViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id safariViewController; // @synthesize safariViewController=_safariViewController;
- (void).cxx_destruct;
- (void)safariViewControllerDidFinish:(id)arg1;

@end

