/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBAdSettings : NSObject {
}
+(void)resetSessionID;
+(id)sessionID;
+(void)setLogLevel:(int)level;
+(int)getLogLevel;
+(id)getBaseURL;
+(id)getWebviewBaseURL;
+(id)getDeliveryEndpoint;
+(void)setUrlPrefix:(id)prefix;
+(id)getMediationService;
+(void)setMediationService:(id)service;
+(BOOL)shouldUseLiveRailEndpoint;
+(BOOL)isChildDirected;
+(BOOL)isTestMode;
+(void)setIsChildDirected:(BOOL)directed;
+(void)clearTestDevices;
+(void)addTestDevices:(id)devices;
+(void)addTestDevice:(id)device;
+(id)testDevices;
+(id)testDeviceHash;
@end

