/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "NSURLSessionDelegate.h"
#import "NSURLSessionDataDelegate.h"

@class NSString, FBAdConcurrentQueue, NSURLSession, FBAdTimer;

@interface FBAdURLSession : NSObject <NSURLSessionDelegate, NSURLSessionDataDelegate> {
	BOOL _SSLValidationDisabled;
	NSURLSession* _session;
	FBAdConcurrentQueue* _queue;
	FBAdTimer* _userAgentTimer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBAdTimer* userAgentTimer;
@property(retain, nonatomic) FBAdConcurrentQueue* queue;
@property(retain, nonatomic) NSURLSession* session;
@property(assign, nonatomic, getter=isSSLValidationDisabled) BOOL SSLValidationDisabled;
+(void)updateSession:(id)session;
+(id)defaultConfiguration;
+(id)sharedSession;
-(void).cxx_destruct;
-(void)URLSession:(id)session didReceiveChallenge:(id)challenge completionHandler:(id)handler;
-(BOOL)isSandboxHost:(id)host;
-(id)urlRequestWithURL:(id)url HTTPMethod:(id)method queryParameters:(id)parameters;
-(BOOL)isEmptyURL:(id)url;
-(id)requestWithURL:(id)url HTTPMethod:(id)method queryParameters:(id)parameters responseHandler:(id)handler;
-(void)emptyQueue;
-(void)enqueueOrExecuteRequest:(id)request;
-(BOOL)valid;
-(id)init;
@end

