//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdPerformanceMetrics : NSObject
{
}

+ (_Bool)getNetworkUsage:(struct FBNetworkUsage *)arg1;
+ (_Bool)lastWakeTime:(double *)arg1;
+ (_Bool)absoluteStartTime:(double *)arg1;
+ (_Bool)getCPUTimeSeconds:(CDUnknownBlockType)arg1 terminatedThreads:(struct FBAdDeviceCPUTime *)arg2;
+ (unsigned long long)freeDiskCount;
+ (unsigned long long)virtualMemoryCount;
+ (unsigned long long)residentMemoryCount;
+ (unsigned long long)totalMemoryCount;
+ (unsigned long long)freeMemoryCount;
+ (id)batteryStateWithDeviceBatteryState:(long long)arg1;
+ (struct FBAdDeviceBatteryInfo)batteryInfo;
+ (id)loadAvgWithPrecision:(double)arg1;
+ (unsigned int)coreCount;

@end

