/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBAdVideoViewDelegate <NSObject>
-(void)videoViewDidTapCallToAction:(id)videoView withButton:(id)button withEvent:(id)event;
-(id)videoViewCallToActionText:(id)actionText;
-(void)videoViewTapped:(id)tapped;
-(void)videoViewDidLoad:(id)videoView;
@end

