/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class UIView, FBAdTimer;
@protocol FBAdViewabilityValidatorDelegate;

@interface FBAdViewabilityValidator : NSObject {
	BOOL _viewOnScreenNotificationSent;
	BOOL _observingNotifications;
	NSObject<FBAdViewabilityValidatorDelegate>* _delegate;
	FBAdTimer* _checkViewabilityTimer;
	UIView* _view;
	int _minViewabilityPercentage;
}
@property(assign, nonatomic) int minViewabilityPercentage;
@property(assign, nonatomic, getter=isObservingNotifications) BOOL observingNotifications;
@property(assign, nonatomic, getter=isViewOnScreenNotificationSent) BOOL viewOnScreenNotificationSent;
@property(assign, nonatomic) __weak UIView* view;
@property(retain, nonatomic) FBAdTimer* checkViewabilityTimer;
@property(assign, nonatomic) __weak NSObject<FBAdViewabilityValidatorDelegate>* delegate;
-(void).cxx_destruct;
-(void)stopObservingNotifications;
-(void)onApplicationForegrounded;
-(void)onApplicationBackgrounded;
-(void)startObservingNotifications;
-(void)resumeTimer;
-(void)invalidateTimer;
-(void)stopViewabilityCheck;
-(void)scheduleViewabilityCheck:(double)check;
-(void)scheduleViewabilityCheck;
-(void)sendViewOffScreenNotification;
-(void)sendViewOnScreenNotification;
-(void)checkViewability;
-(void)isViewOnScreenWithBlock:(id)block;
-(id)logSuccess:(BOOL)success withReason:(id)reason;
-(void)dealloc;
-(id)initWithView:(id)view minViewability:(int)viewability shouldObserveNotifications:(BOOL)notifications;
-(id)init;
@end

