/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBAdCachedObject : NSObject {
	id _object;
	double _expiration;
}
@property(retain, nonatomic) id object;
@property(assign, nonatomic) double expiration;
-(void).cxx_destruct;
-(id)initWithObject:(id)object withExpiration:(id)expiration;
@end

