//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBANAdRenderer : NSObject
{
}

+ (id)renderAdWithdata:(id)arg1 width:(long long)arg2 height:(long long)arg3 minViewablePercentage:(int)arg4 rootViewController:(id)arg5 delegate:(id)arg6;
+ (long long)getTemplateID:(long long)arg1 height:(long long)arg2;
+ (id)getSupportedCapabilities;

@end

