/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import "FBAdCommandProcessorDelegate.h"
#import "FBDisplayAdAdapter.h"

@class NSString, FBAdCommandProcessor, FBAdTimer, UIViewController;

@interface FBANNativeAdAdapter : FBDisplayAdAdapter <FBAdCommandProcessorDelegate> {
	BOOL _hasLoggedClick;
	BOOL _hasLoggedImpression;
	BOOL _hasLoggedVideoPlay;
	FBAdCommandProcessor* _commandProcessor;
	UIViewController* _viewController;
	FBAdTimer* _snapshotTimer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBAdTimer* snapshotTimer;
@property(retain, nonatomic) UIViewController* viewController;
@property(retain, nonatomic) FBAdCommandProcessor* commandProcessor;
@property(assign, nonatomic) BOOL hasLoggedVideoPlay;
@property(assign, nonatomic) BOOL hasLoggedImpression;
@property(assign, nonatomic) BOOL hasLoggedClick;
-(void).cxx_destruct;
-(void)viewControllerDismissed:(id)dismissed;
-(id)viewControllerForPresentingModalView;
-(void)onVideoTimeWithExtraData:(id)extraData;
-(void)onVideoPlayWithExtraData:(id)extraData;
-(void)onClickForViewController:(id)viewController withExtraData:(id)extraData;
-(void)onImpressionWithExtraData:(id)extraData withPostData:(id)postData;
-(BOOL)startAdFromRootViewController:(id)rootViewController;
-(void)loadAdData:(id)data forSize:(FBAdSize)size forOrientation:(int)orientation forPlacement:(id)placement minViewability:(int)viewability;
@end

