/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import "FBDisplayAdAdapter.h"
#import "FBInterstitialAdDelegate.h"

@class NSString, FBInterstitialAdInternal;

@interface FBANInterstitialAdAdapter : FBDisplayAdAdapter <FBInterstitialAdDelegate> {
	FBInterstitialAdInternal* _target;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FBInterstitialAdInternal* target;
-(void).cxx_destruct;
-(void)interstitialAdWillLogImpression:(id)interstitialAd;
-(void)interstitialAd:(id)ad didFailWithError:(id)error;
-(void)interstitialAdDidLoad:(id)interstitialAd;
-(void)interstitialAdWillClose:(id)interstitialAd;
-(void)interstitialAdDidClose:(id)interstitialAd;
-(void)interstitialAdDidClick:(id)interstitialAd;
-(id)adView;
-(BOOL)startAdFromRootViewController:(id)rootViewController;
-(void)loadAdData:(id)data forSize:(FBAdSize)size forOrientation:(int)orientation forPlacement:(id)placement minViewability:(int)viewability;
@end

