/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBDisplayAdControllerDelegate <NSObject>
-(void)displayAdController:(id)controller didFailWithError:(id)error;
-(void)displayAdControllerStopped:(id)stopped;
-(void)displayAdControllerLoaded:(id)loaded;
@optional
-(void)displayAdControllerUserClosed:(id)closed;
-(void)displayAdController:(id)controller clickThruWithURL:(id)url;
-(void)displayAdControllerImpression:(id)impression;
-(void)displayAdController:(id)controller presentedData:(id)data onImpression:(id)impression onClick:(id)click onVideoPlay:(id)play onVideoTime:(id)time;
-(void)displayAdController:(id)controller presentedView:(id)view;
@end

