//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBDisplayAdController, FBNativeAdDataModel, NSError, NSURL, UIView;

@protocol FBDisplayAdControllerDelegate <NSObject>
- (void)displayAdController:(FBDisplayAdController *)arg1 didFailWithError:(NSError *)arg2;
- (void)displayAdControllerStopped:(FBDisplayAdController *)arg1;
- (void)displayAdControllerLoaded:(FBDisplayAdController *)arg1;

@optional
- (void)displayAdControllerUserClosed:(FBDisplayAdController *)arg1;
- (void)displayAdController:(FBDisplayAdController *)arg1 clickThruWithURL:(NSURL *)arg2;
- (void)displayAdControllerImpression:(FBDisplayAdController *)arg1;
- (void)displayAdController:(FBDisplayAdController *)arg1 presentedData:(FBNativeAdDataModel *)arg2 onImpression:(void (^)(NSDictionary *, NSDictionary *))arg3 onClick:(void (^)(UIViewController *, NSDictionary *))arg4 onVideoPlay:(void (^)(NSDictionary *))arg5 onVideoTime:(void (^)(NSDictionary *))arg6;
- (void)displayAdController:(FBDisplayAdController *)arg1 presentedView:(UIView *)arg2;
@end

