//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "FBAdBlurredImageViewDelegate.h"
#import "FBAdVideoViewDelegate.h"

@class FBAdBlurredImageView, FBAdVideoView, FBNativeAd, NSString;

@interface FBMediaView : UIView <FBAdBlurredImageViewDelegate, FBAdVideoViewDelegate>
{
    _Bool _autoplayEnabled;
    _Bool _videoFailedToLoad;
    _Bool _needsDelayedLoad;
    id <FBMediaViewDelegate> _delegate;
    FBNativeAd *_nativeAd;
    FBAdBlurredImageView *_imageView;
    FBAdVideoView *_videoView;
}

@property(nonatomic) _Bool needsDelayedLoad; // @synthesize needsDelayedLoad=_needsDelayedLoad;
@property(nonatomic) _Bool videoFailedToLoad; // @synthesize videoFailedToLoad=_videoFailedToLoad;
@property(nonatomic) __weak FBAdVideoView *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) __weak FBAdBlurredImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic, getter=isAutoplayEnabled) _Bool autoplayEnabled; // @synthesize autoplayEnabled=_autoplayEnabled;
@property(retain, nonatomic) FBNativeAd *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(nonatomic) __weak id <FBMediaViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)videoViewDidTapCallToAction:(id)arg1 withButton:(id)arg2 withEvent:(id)arg3;
- (id)videoViewCallToActionText:(id)arg1;
- (void)videoViewTapped:(id)arg1;
- (void)videoViewDidLoad:(id)arg1;
- (void)blurredImageViewDidLoad:(id)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)loadVideo;
- (void)loadImage;
- (void)loadNativeAd:(id)arg1;
- (_Bool)autoplayEnabled;
- (_Bool)isValidFrame;
- (_Bool)videoSupported;
- (void)setupView;
- (id)initWithNativeAd:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

