/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBNativeAdTableViewAdProvider.h"

@class NSString, FBNativeAdViewAttributes;

@interface FBNativeAdTableViewCellProvider : FBNativeAdTableViewAdProvider {
	int _type;
	FBNativeAdViewAttributes* _attributes;
	NSString* _uniqueTableCellIdentifier;
}
@property(retain, nonatomic) NSString* uniqueTableCellIdentifier;
@property(retain, nonatomic) FBNativeAdViewAttributes* attributes;
@property(assign, nonatomic) int type;
-(void).cxx_destruct;
-(id)tableCellIdentifier;
-(float)tableView:(id)view estimatedHeightForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)initWithManager:(id)manager forType:(int)type forAttributes:(id)attributes;
-(id)initWithManager:(id)manager forType:(int)type;
-(id)initWithManager:(id)manager;
@end

