/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import "FBNativeAdView.h"

@class FBNativeAdHeaderView, FBNativeAdDetailsView, UILabel, NSNumber;

@interface FBNativeAdTemplateView : FBNativeAdView {
	NSNumber* _headerSize;
	NSNumber* _coverImageSize;
	NSNumber* _detailsSize;
	UILabel* _headerTitleLabel;
	UILabel* _headerBodyLabel;
	FBNativeAdHeaderView* _headerView;
	FBNativeAdDetailsView* _detailsView;
}
@property(assign, nonatomic) __weak FBNativeAdDetailsView* detailsView;
@property(assign, nonatomic) __weak FBNativeAdHeaderView* headerView;
@property(assign, nonatomic) __weak UILabel* headerBodyLabel;
@property(assign, nonatomic) __weak UILabel* headerTitleLabel;
@property(assign, nonatomic, getter=isBodyTextEnabled) BOOL bodyTextEnabled;
@property(retain, nonatomic) NSNumber* detailsSize;
@property(retain, nonatomic) NSNumber* coverImageSize;
@property(retain, nonatomic) NSNumber* headerSize;
+(id)defaultAttributes;
-(void).cxx_destruct;
-(void)updateView:(BOOL)view;
-(void)constructCallToActionButton;
-(void)constructIconImageView;
-(void)constructBodyView;
@end

