/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>

@class UIButton, FBAdBodyView, FBNativeAdViewAttributes, UILabel, FBNativeAd, UIImageView;

@interface FBNativeAdDetailsView : UIView {
	BOOL _loaded;
	BOOL _bodyTextEnabled;
	FBNativeAd* _nativeAd;
	FBNativeAdViewAttributes* _attributes;
	FBAdBodyView* _bodyView;
	UIImageView* _iconImageView;
	UIButton* _callToActionButton;
	UILabel* _bodyLabel;
}
@property(assign, nonatomic, getter=isBodyTextEnabled) BOOL bodyTextEnabled;
@property(assign, nonatomic, getter=isLoaded) BOOL loaded;
@property(assign, nonatomic) __weak UILabel* bodyLabel;
@property(assign, nonatomic) __weak UIButton* callToActionButton;
@property(assign, nonatomic) __weak UIImageView* iconImageView;
@property(assign, nonatomic) __weak FBAdBodyView* bodyView;
@property(assign, nonatomic) __weak FBNativeAdViewAttributes* attributes;
@property(assign, nonatomic) __weak FBNativeAd* nativeAd;
-(void).cxx_destruct;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)resetView;
-(void)updateView:(BOOL)view;
-(void)createView;
-(void)reinitializeView;
-(id)initWithFrame:(CGRect)frame nativeAd:(id)ad attributes:(id)attributes;
@end

