//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBNativeAd.h"

@interface FBNativeAd (ManualLoggingHelper)
- (void)checkManualLoggingEligibility;
- (id)getManualLoggingExtraData;
- (void)handleClickWithViewController:(id)arg1;
- (void)logImpression;
@end

