/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>


@interface FBNativeAdContainerView : UIView {
	UIView* _passthroughView;
}
@property(assign, nonatomic) __weak UIView* passthroughView;
-(void).cxx_destruct;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

