/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"
#import "NSCopying.h"

@class UIFont, NSNumber, UIColor;

@interface FBNativeAdViewAttributes : NSObject <NSCopying> {
	BOOL _autoplayEnabled;
	UIColor* _backgroundColor;
	UIColor* _titleColor;
	UIFont* _titleFont;
	UIColor* _descriptionColor;
	UIFont* _descriptionFont;
	UIColor* _buttonColor;
	UIColor* _buttonTitleColor;
	UIFont* _buttonTitleFont;
	UIColor* _buttonBorderColor;
	NSNumber* _bypassAdLoad;
	NSNumber* _skipRegistration;
	NSNumber* _shouldClip;
	NSNumber* _borderRadius;
	NSNumber* _buttonBorderRadius;
	NSNumber* _iconBorderRadius;
	NSNumber* _adChoicesBackgroundShown;
	UIColor* _adChoicesTitleColor;
	UIColor* _adChoicesBackgroundColor;
	NSNumber* _ratingEnabled;
	NSNumber* _socialContextEnabled;
}
@property(retain, nonatomic) NSNumber* socialContextEnabled;
@property(retain, nonatomic) NSNumber* ratingEnabled;
@property(retain, nonatomic) UIColor* adChoicesBackgroundColor;
@property(retain, nonatomic) UIColor* adChoicesTitleColor;
@property(retain, nonatomic) NSNumber* adChoicesBackgroundShown;
@property(retain, nonatomic) NSNumber* iconBorderRadius;
@property(retain, nonatomic) NSNumber* buttonBorderRadius;
@property(retain, nonatomic) NSNumber* borderRadius;
@property(retain, nonatomic) NSNumber* shouldClip;
@property(retain, nonatomic) NSNumber* skipRegistration;
@property(retain, nonatomic) NSNumber* bypassAdLoad;
@property(assign, nonatomic, getter=isAutoplayEnabled) BOOL autoplayEnabled;
@property(copy, nonatomic) UIColor* buttonBorderColor;
@property(copy, nonatomic) UIFont* buttonTitleFont;
@property(copy, nonatomic) UIColor* buttonTitleColor;
@property(copy, nonatomic) UIColor* buttonColor;
@property(copy, nonatomic) UIFont* descriptionFont;
@property(copy, nonatomic) UIColor* descriptionColor;
@property(copy, nonatomic) UIFont* titleFont;
@property(copy, nonatomic) UIColor* titleColor;
@property(copy, nonatomic) UIColor* backgroundColor;
+(id)colorFromHexString:(id)hexString;
+(id)internalAttributesForAttributes:(id)attributes;
+(id)internalAttributesForType:(int)type;
+(id)defaultAttributesForType:(int)type;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDictionary:(id)dictionary;
-(id)init;
@end

