/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "FBSDKContainerViewControllerDelegate.h"

@class NSString, UIViewController, FBSDKBridgeAPIRequest;
@protocol FBSDKURLOpening;

@interface FBSDKApplicationDelegate : NSObject <FBSDKContainerViewControllerDelegate> {
	FBSDKBridgeAPIRequest* _pendingRequest;
	id _pendingRequestCompletionBlock;
	id<FBSDKURLOpening> _pendingURLOpen;
	BOOL _expectingBackground;
	UIViewController* _safariViewController;
	BOOL _active;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic, getter=isActive) BOOL active;
+(id)sharedInstance;
+(void)initializeWithLaunchData:(id)launchData;
+(void)load;
-(void).cxx_destruct;
-(void)_cancelBridgeRequest;
-(BOOL)_handleBridgeAPIResponseURL:(id)url sourceApplication:(id)application;
-(void)_logIfAppLinkEvent:(id)event;
-(void)viewControllerDidDisappear:(id)viewController animated:(BOOL)animated;
-(void)safariViewControllerDidFinish:(id)safariViewController;
-(void)openURLWithSafariViewController:(id)safariViewController sender:(id)sender fromViewController:(id)viewController handler:(id)handler;
-(void)openBridgeAPIRequest:(id)request useSafariViewController:(BOOL)controller fromViewController:(id)viewController completionBlock:(id)block;
-(void)openURL:(id)url sender:(id)sender handler:(id)handler;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(void)dealloc;
-(id)init;
-(id)_init;
@end

