/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "NSSecureCoding.h"
#import "FBSDKCopying.h"
#import "wotblitz-Structs.h"

@class FBSDKErrorConfiguration, NSDictionary, NSDate, NSString;

@interface FBSDKServerConfiguration : NSObject <FBSDKCopying, NSSecureCoding> {
	NSDictionary* _dialogConfigurations;
	NSDictionary* _dialogFlows;
	BOOL _advertisingIDEnabled;
	BOOL _defaults;
	BOOL _implicitLoggingEnabled;
	BOOL _implicitPurchaseLoggingEnabled;
	BOOL _loginTooltipEnabled;
	BOOL _nativeAuthFlowEnabled;
	BOOL _systemAuthenticationEnabled;
	NSString* _appID;
	NSString* _appName;
	NSString* _defaultShareMode;
	FBSDKErrorConfiguration* _errorConfiguration;
	NSString* _loginTooltipText;
	NSDate* _timestamp;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) NSDate* timestamp;
@property(readonly, copy, nonatomic) NSString* loginTooltipText;
@property(readonly, assign, nonatomic, getter=isSystemAuthenticationEnabled) BOOL systemAuthenticationEnabled;
@property(readonly, assign, nonatomic, getter=isNativeAuthFlowEnabled) BOOL nativeAuthFlowEnabled;
@property(readonly, assign, nonatomic, getter=isLoginTooltipEnabled) BOOL loginTooltipEnabled;
@property(readonly, assign, nonatomic, getter=isImplicitPurchaseLoggingSupported) BOOL implicitPurchaseLoggingEnabled;
@property(readonly, assign, nonatomic, getter=isImplicitLoggingSupported) BOOL implicitLoggingEnabled;
@property(readonly, assign, nonatomic) FBSDKErrorConfiguration* errorConfiguration;
@property(readonly, copy, nonatomic) NSString* defaultShareMode;
@property(readonly, assign, nonatomic, getter=isDefaults) BOOL defaults;
@property(readonly, copy, nonatomic) NSString* appName;
@property(readonly, copy, nonatomic) NSString* appID;
@property(readonly, assign, nonatomic, getter=isAdvertisingIDEnabled) BOOL advertisingIDEnabled;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(BOOL)_useFeatureWithKey:(id)key dialogName:(id)name;
-(BOOL)useSafariViewControllerForDialogName:(id)dialogName;
-(BOOL)useNativeDialogForDialogName:(id)dialogName;
-(id)dialogConfigurationForDialogName:(id)dialogName;
-(id)initWithAppID:(id)appID appName:(id)name loginTooltipEnabled:(BOOL)enabled loginTooltipText:(id)text defaultShareMode:(id)mode advertisingIDEnabled:(BOOL)enabled6 implicitLoggingEnabled:(BOOL)enabled7 implicitPurchaseLoggingEnabled:(BOOL)enabled8 systemAuthenticationEnabled:(BOOL)enabled9 nativeAuthFlowEnabled:(BOOL)enabled10 dialogConfigurations:(id)configurations dialogFlows:(id)flows timestamp:(id)timestamp errorConfiguration:(id)configuration defaults:(BOOL)defaults;
-(id)init;
@end

