/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "FBSDKSharing.h"
#import "FBSDKVideoUploaderDelegate.h"

@class NSString, ALAssetRepresentation, NSFileHandle;
@protocol FBSDKSharingDelegate, FBSDKSharingContent;

@interface FBSDKShareAPI : NSObject <FBSDKVideoUploaderDelegate, FBSDKSharing> {
	NSFileHandle* _fileHandle;
	ALAssetRepresentation* _assetRepresentation;
	BOOL _shouldFailOnDataError;
	id<FBSDKSharingDelegate> _delegate;
	id<FBSDKSharingContent> _shareContent;
	NSString* _message;
	NSString* _graphNode;
}
@property(assign, nonatomic) BOOL shouldFailOnDataError;
@property(copy, nonatomic) id<FBSDKSharingContent> shareContent;
@property(assign, nonatomic) __weak id<FBSDKSharingDelegate> delegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* graphNode;
@property(copy, nonatomic) NSString* message;
+(void)initialize;
+(id)defaultAssetsLibrary;
+(id)shareWithContent:(id)content delegate:(id)delegate;
-(void).cxx_destruct;
-(void)videoUploader:(id)uploader didFailWithError:(id)error;
-(void)videoUploader:(id)uploader didCompleteWithResults:(id)results;
-(id)videoChunkDataForVideoUploader:(id)videoUploader startOffset:(unsigned)offset endOffset:(unsigned)offset3;
-(void)_removeFromPendingShareAPI;
-(BOOL)_addToPendingShareAPI;
-(id)_connection:(id)connection addRequest:(id)request completionHandler:(id)handler;
-(BOOL)_stageValue:(id)value connection:(id)connection stagingHandler:(id)handler;
-(BOOL)_stagePhoto:(id)photo connection:(id)connection stagingHandler:(id)handler;
-(BOOL)_stageOpenGraphValueContainer:(id)container connection:(id)connection stagingHandler:(id)handler;
-(BOOL)_stageOpenGraphObject:(id)object connection:(id)connection stagingHandler:(id)handler completionHandler:(id)handler4;
-(BOOL)_stageArray:(id)array connection:(id)connection stagingHandler:(id)handler;
-(BOOL)_addEncodedParametersToDictionary:(id)dictionary key:(id)key value:(id)value error:(id*)error;
-(BOOL)_shareVideoContent:(id)content;
-(BOOL)_sharePhotoContent:(id)content;
-(BOOL)_shareOpenGraphContent:(id)content;
-(BOOL)_shareLinkContent:(id)content;
-(BOOL)_hasPublishActions;
-(void)_addCommonParameters:(id)parameters content:(id)content;
-(id)_graphPathWithSuffix:(id)suffix;
-(BOOL)validateWithError:(id*)error;
-(BOOL)share;
-(BOOL)createOpenGraphObject:(id)object;
-(BOOL)canShare;
-(id)init;
@end

