/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, FBSDKAccessToken, NSDictionary, NSSet;

@interface FBSDKLoginManagerLoginResult : NSObject {
	NSMutableDictionary* _mutableLoggingExtras;
	BOOL _isCancelled;
	BOOL _isSkipped;
	FBSDKAccessToken* _token;
	NSSet* _grantedPermissions;
	NSSet* _declinedPermissions;
}
@property(assign, nonatomic) BOOL isSkipped;
@property(readonly, assign, nonatomic) NSDictionary* loggingExtras;
@property(copy, nonatomic) NSSet* declinedPermissions;
@property(copy, nonatomic) NSSet* grantedPermissions;
@property(readonly, assign, nonatomic) BOOL isCancelled;
@property(copy, nonatomic) FBSDKAccessToken* token;
-(void).cxx_destruct;
-(void)addLoggingExtra:(id)extra forKey:(id)key;
-(id)initWithToken:(id)token isCancelled:(BOOL)cancelled grantedPermissions:(id)permissions declinedPermissions:(id)permissions4;
-(id)init;
@end

