/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class UIViewController, NSString;
@protocol FBSDKLikeDialogDelegate;

@interface FBSDKLikeDialog : NSObject {
	BOOL _shouldFailOnDataError;
	id<FBSDKLikeDialogDelegate> _delegate;
	NSString* _objectID;
	unsigned _objectType;
	UIViewController* _fromViewController;
}
@property(assign, nonatomic) __weak UIViewController* fromViewController;
@property(assign, nonatomic) BOOL shouldFailOnDataError;
@property(assign, nonatomic) unsigned objectType;
@property(copy, nonatomic) NSString* objectID;
@property(assign, nonatomic) __weak id<FBSDKLikeDialogDelegate> delegate;
+(id)likeWithObjectID:(id)objectID objectType:(unsigned)type delegate:(id)delegate;
+(void)initialize;
-(void).cxx_destruct;
-(void)_handleCompletionWithDialogResults:(id)dialogResults error:(id)error;
-(BOOL)_canLikeNative;
-(BOOL)validateWithError:(id*)error;
-(BOOL)like;
-(BOOL)canLike;
@end

