/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class FBSDKMessengerContext;

@interface FBSDKMessengerApplicationStateManager : NSObject {
	FBSDKMessengerContext* _currentContext;
}
@property(retain, nonatomic) FBSDKMessengerContext* currentContext;
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)applicationWillResignActive:(id)application;
-(id)_init;
@end

