//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSDKErrorRecoveryAttempter.h"

@interface FBSDKErrorRecoveryAttempter (Protected)
- (void)completeRecovery:(_Bool)arg1 delegate:(id)arg2 didRecoverSelector:(SEL)arg3 contextInfo:(void *)arg4;
@end

