/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>

@class NSString, NSArray, UITapGestureRecognizer, UILabel, UIColor;

@interface FBSDKTooltipView : UIView {
	CGPoint _positionInView;
	double _displayTime;
	double _minimumDisplayDuration;
	UILabel* _textLabel;
	UITapGestureRecognizer* _insideTapGestureRecognizer;
	float _leftWidth;
	float _rightWidth;
	float _arrowMidpoint;
	BOOL _pointingUp;
	BOOL _isFadingOut;
	UIColor* _innerStrokeColor;
	float _arrowHeight;
	float _textPadding;
	float _maximumTextWidth;
	float _verticalTextOffset;
	float _verticalCrossOffset;
	unsigned _colorStyle;
	NSArray* _gradientColors;
	UIColor* _crossCloseGlyphColor;
	NSString* _message;
	NSString* _tagline;
	double _displayDuration;
}
@property(copy, nonatomic) NSString* tagline;
@property(copy, nonatomic) NSString* message;
@property(assign, nonatomic) unsigned colorStyle;
@property(assign, nonatomic) double displayDuration;
-(void).cxx_destruct;
-(void)cancelAllScheduledFadeOutMethods;
-(void)scheduleFadeoutRespectingMinimumDisplayDuration;
-(void)scheduleAutomaticFadeout;
-(void)setMessage:(id)message tagline:(id)tagline;
-(CGRect)layoutSubviewsAndDetermineFrame;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(void)onTapInTooltip:(id)tooltip;
-(void)animateFadeOutWithCompletion:(id)completion;
-(void)animateFadeIn;
-(void)dismiss;
-(void)presentInView:(id)view withArrowPosition:(CGPoint)arrowPosition direction:(unsigned)direction;
-(void)presentFromView:(id)view;
-(void)dealloc;
-(id)initWithTagline:(id)tagline message:(id)message colorStyle:(unsigned)style;
@end

