/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "FBSDKWebDialogDelegate.h"

@class NSString, FBSDKAppGroupContent, FBSDKWebDialog;
@protocol FBSDKAppGroupAddDialogDelegate;

@interface FBSDKAppGroupAddDialog : NSObject <FBSDKWebDialogDelegate> {
	FBSDKWebDialog* _webDialog;
	id<FBSDKAppGroupAddDialogDelegate> _delegate;
	FBSDKAppGroupContent* _content;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) FBSDKAppGroupContent* content;
@property(assign, nonatomic) __weak id<FBSDKAppGroupAddDialogDelegate> delegate;
+(id)showWithContent:(id)content delegate:(id)delegate;
-(void).cxx_destruct;
-(void)_handleCompletionWithDialogResults:(id)dialogResults error:(id)error;
-(void)webDialogDidCancel:(id)webDialog;
-(void)webDialog:(id)dialog didFailWithError:(id)error;
-(void)webDialog:(id)dialog didCompleteWithResults:(id)results;
-(BOOL)validateWithError:(id*)error;
-(BOOL)show;
-(BOOL)canShow;
-(void)dealloc;
-(id)init;
@end

