/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBSDKMessengerSharer : NSObject {
}
+(void)shareAudio:(id)audio withOptions:(id)options;
+(void)shareAudio:(id)audio withMetadata:(id)metadata withContext:(id)context;
+(void)shareVideo:(id)video withOptions:(id)options;
+(void)shareVideo:(id)video withMetadata:(id)metadata withContext:(id)context;
+(void)shareAnimatedWebP:(id)p withOptions:(id)options;
+(void)shareAnimatedWebP:(id)p withMetadata:(id)metadata withContext:(id)context;
+(void)shareAnimatedGIF:(id)gif withOptions:(id)options;
+(void)shareAnimatedGIF:(id)gif withMetadata:(id)metadata withContext:(id)context;
+(void)shareImage:(id)image withOptions:(id)options;
+(void)shareImage:(id)image withMetadata:(id)metadata withContext:(id)context;
+(void)openMessenger;
+(unsigned)messengerPlatformCapabilities;
+(id)_minimumVersionToSupportCapability:(unsigned)supportCapability withOptions:(id)options;
+(id)_generateUrl:(id)url withOptions:(id)options messengerVersion:(id)version;
+(id)_parseQueryComponentsFromOptions:(id)options;
+(void)_launchUrl:(id)url withOptions:(id)options minimumRequiredVersion:(id)version;
+(id)sortedReleaseVersions;
+(id)messengerVersionCapabilities;
+(id)currentlyInstalledMessengerVersion;
@end

