/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface GAICoreDataUtil : NSObject {
}
+(id)oldModelDescription;
+(id)modelDescription;
+(id)modelWithDescription:(id)description;
+(id)entityWithDescription:(id)description;
+(id)oldModel;
+(id)model;
-(id)init;
@end

