/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSNumber, NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface GAIDataStore : NSObject {
	BOOL _setUpCoreData;
	NSString* _clientId;
	NSString* _hashedIdfa;
	NSNumber* _lastChangeTimeStamp;
	NSNumber* _idfaChangeCount;
	unsigned _maxHitCount;
	NSManagedObjectContext* _oldContext;
	NSManagedObjectContext* _context;
	NSManagedObjectContext* _currentContext;
}
@property(retain, nonatomic) NSManagedObjectContext* currentContext;
@property(retain, nonatomic) NSManagedObjectContext* context;
@property(retain, nonatomic) NSManagedObjectContext* oldContext;
@property(assign, nonatomic) unsigned maxHitCount;
@property(retain, nonatomic) NSNumber* lastChangeTimeStamp;
@property(retain, nonatomic) NSNumber* idfaChangeCount;
@property(retain, nonatomic) NSString* hashedIdfa;
@property(retain, nonatomic) NSString* clientId;
+(id)dataStore;
+(id)thread;
+(id)databaseFullURL:(id)url;
+(id)databaseFullPath:(id)path;
-(void).cxx_destruct;
-(void)dealloc;
-(void)onExit:(id)exit;
-(BOOL)setUpCoreData;
-(id)init;
-(BOOL)save:(id*)save;
-(BOOL)deleteAllHits:(id*)hits;
-(BOOL)deleteHitsWithIds:(id)ids error:(id*)error;
-(id)fetchHitsWithLimit:(unsigned)limit error:(id*)error;
-(void)addHit:(id)hit;
-(int)hitCount:(id*)count;
-(oneway void)setClientId:(id)anId;
-(id)fetchClientId;
-(oneway void)setHashedIdfa:(id)idfa;
-(oneway void)setIdfaChangeCount:(id)count;
-(oneway void)setLastChangeTimeStamp:(id)stamp;
-(BOOL)setProperty:(id)property stringValue:(id)value withError:(id*)error;
-(BOOL)setProperty:(id)property numberValue:(id)value withError:(id*)error;
-(id)contextWithModel:(id)model URL:(id)url;
-(id)coordinatorWithModel:(id)model URL:(id)url;
-(id)performBlockAndWait:(id)wait withError:(id*)error;
-(void)gai_performBlockHelper:(id)helper;
-(BOOL)context:(id)context removeStaleHits:(id*)hits;
-(int)context:(id)context hitCount:(id*)count;
-(BOOL)deleteExcessHits:(id*)hits;
-(id)oldHitDescription:(id)description;
-(id)requestPropertyWithName:(id)name;
-(id)requestHitsWithLimit:(unsigned)limit;
-(id)requestEntityName:(id)name;
@end

