/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface GAIEcommerceFields : NSObject {
}
+(id)promotionForIndex:(unsigned)index suffix:(id)suffix;
+(id)productImpressionForList:(id)list index:(unsigned)index suffix:(id)suffix;
+(id)impressionListForIndex:(unsigned)index;
+(id)productFieldForIndex:(unsigned)index suffix:(id)suffix;
+(id)stripAmpersandIfPresent:(id)present;
@end

