/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface GAIEcommercePromotion : NSObject {
	NSMutableDictionary* _parameters;
}
@property(retain, nonatomic) NSMutableDictionary* parameters;
-(void).cxx_destruct;
-(id)buildWithIndex:(unsigned)index;
-(id)setPosition:(id)position;
-(id)setCreative:(id)creative;
-(id)setName:(id)name;
-(id)setId:(id)anId;
-(id)setString:(id)string forKey:(id)key;
-(id)init;
@end

