/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface GAIFields : NSObject {
}
+(id)customMetricForIndex:(unsigned)index;
+(id)customDimensionForIndex:(unsigned)index;
+(id)contentGroupForIndex:(unsigned)index;
@end

