/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface GAIHitUtil : NSObject {
}
+(id)hashIdfa:(id)idfa clientId:(id)anId;
+(id)generateClientId;
+(unsigned)gaHash:(id)hash;
+(long long)millisecondsElapsedFrom:(id)from To:(id)to;
+(id)systemScreenColorDepth;
+(CGRect)swapDimensionsOfRect:(CGRect)rect;
+(id)systemScreenResolution;
+(id)deviceModelVersion;
+(id)systemCountry;
+(id)systemLanguage;
+(id)userAgentString;
+(id)userAgentStringWithProduct:(id)product version:(id)version deviceModel:(id)model systemName:(id)name systemVersion:(id)version5 systemLanguage:(id)language systemCountry:(id)country;
+(id)systemCountryFromLocale:(id)locale;
+(id)systemLanguageFromLanguages:(id)languages;
-(id)init;
@end

