/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "GAILogger.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface GAILoggerImpl : NSObject <GAILogger> {
}
@property(assign, nonatomic) unsigned logLevel;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(unsigned)gaLogLevelFromGtmLogLevel:(int)gtmLogLevel;
-(void)error:(id)error;
-(void)warning:(id)warning;
-(void)verbose:(id)verbose;
-(void)info:(id)info;
@end

