/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>

@class NSString;
@protocol GAIReachabilityDelegate;

__attribute__((visibility("hidden")))
@interface GAIReachabilityChecker : NSObject {
	const GAIReachabilityApi* reachabilityApi_;
	SCNetworkReachabilityRef reachability_;
	int reachabilityStatus_;
	NSString* host_;
	id<GAIReachabilityDelegate> delegate_;
}
@property(assign, nonatomic) SCNetworkReachabilityRef reachability;
@property(assign, nonatomic) const GAIReachabilityApi* reachabilityApi;
@property(readonly, assign, nonatomic) BOOL isActive;
@property(assign, nonatomic) id<GAIReachabilityDelegate> delegate;
@property(copy, nonatomic) NSString* host;
@property(assign, nonatomic) int reachabilityStatus;
-(void)reachabilityFlagsChanged:(unsigned)changed;
-(int)statusForFlags:(unsigned)flags;
-(void)stop;
-(BOOL)start;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate withHost:(id)host;
-(id)init;
@end

