/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface GAISqlStore : NSObject {
	NSString* _databaseName;
	sqlite3* _database;
	NSMutableDictionary* _statementCache;
	NSString* _databasePath;
}
@property(readonly, assign, nonatomic) NSString* databasePath;
@property(retain, nonatomic) NSMutableDictionary* statementCache;
@property(assign, nonatomic) sqlite3* database;
@property(readonly, copy, nonatomic) NSString* errorMessage;
@property(readonly, copy, nonatomic) NSString* databaseName;
+(id)databaseDirectoryPath;
+(id)sharedInstance;
-(void).cxx_destruct;
-(int)executeSql:(id)sql;
-(sqlite3_stmt*)prepareSql:(id)sql;
-(BOOL)dropTableWithName:(id)name;
-(BOOL)tableExists:(id)exists;
-(BOOL)closeAndDeleteDatabase;
-(id)closeDatabase;
-(BOOL)openAndValidateDatabase;
-(BOOL)ensureOpenDatabase;
-(void)finalizeAndClearStatements;
-(void)removeStatementForQuery:(id)query;
-(sqlite3_stmt*)statementForQuery:(id)query;
-(void)setStatement:(sqlite3_stmt*)statement forQuery:(id)query;
-(unsigned)rowCountForTableWithName:(id)name;
-(void)dealloc;
-(id)initWithDatabaseName:(id)databaseName;
@end

