/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "GAITracker.h"

@class NSString, GAITrackerModel, GAIUsageTracker;
@protocol GAIDispatchSender;

__attribute__((visibility("hidden")))
@interface GAITrackerImpl : NSObject <GAITracker> {
	BOOL allowIDFACollection_;
	id<GAIDispatchSender> dispatcher_;
	NSString* name_;
	GAITrackerModel* model_;
	GAIUsageTracker* _usageTracker;
	double trackingCredits_;
	double lastTrackTime_;
	unsigned long long _trackCount;
	unsigned long long _hitCount;
}
@property(assign, nonatomic) BOOL allowIDFACollection;
@property(readonly, assign, nonatomic) NSString* name;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) GAIUsageTracker* usageTracker;
@property(retain, nonatomic) GAITrackerModel* model;
@property(assign, nonatomic) double lastTrackTime;
@property(assign, nonatomic) double trackingCredits;
@property(assign, nonatomic) unsigned long long hitCount;
@property(assign, nonatomic) unsigned long long trackCount;
@property(retain, nonatomic) id<GAIDispatchSender> dispatcher;
+(id)trackerWithDispatcher:(id)dispatcher name:(id)name;
-(void)send:(id)send;
-(void)set:(id)set value:(id)value;
-(id)get:(id)get;
-(void)gai_send:(id)send;
-(void)gai_set:(id)set;
-(id)gai_get:(id)get;
-(void)gai_set:(id)set value:(id)value;
-(BOOL)shouldRateLimit;
-(void)dealloc;
-(id)initWithDispatcher:(id)dispatcher name:(id)name;
-(id)init;
@end

