//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HelperAppDelegate.h"

#import "CrashlyticsDelegate.h"

@class NSDictionary, NSString, NSTimer, UIWindow;

@interface iOSAppDelegate : HelperAppDelegate <CrashlyticsDelegate>
{
    UIWindow *window;
    NSDictionary *pushNotificationOptions;
    _Bool didDetectCrashDuringPreviousExecution;
    unsigned long long _backgroundTask;
    NSTimer *_updateTimer;
}

@property(retain, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(nonatomic) unsigned long long backgroundTask; // @synthesize backgroundTask=_backgroundTask;
- (void)setWindow:(id)arg1;
- (id)window;
- (void)handleShortcut:(id)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)crashlyticsDidDetectReportForLastExecution:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (_Bool)didDetectCrashDuringPreviousExecution;
- (id)dequeueLaunchOptions;
- (void)checkSkipBackupAttributeOnDirectory:(id)arg1;
- (_Bool)addSkipBackupAttributeToItemAtURL:(id)arg1;
- (void)addSkipBackupAttributeToDirectory:(id)arg1;
- (void)addSkipBackupAttributeToDirectories;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)tickInBg:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)dealloc;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

