/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TunePreloadData.h"


@interface MATPreloadData : TunePreloadData {
}
+(id)preloadDataWithPublisherId:(id)publisherId;
-(id)initWithPublisherId:(id)publisherId;
@end

