/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface MobileAppTracker : NSObject {
}
+(void)startMonitoringForBeaconRegion:(id)beaconRegion nameId:(id)anId majorId:(unsigned)anId3 minorId:(unsigned)anId4;
+(void)applicationDidOpenURL:(id)application sourceApplication:(id)application2;
+(void)startAppToAppTracking:(id)appTracking advertiserId:(id)anId offerId:(id)anId3 publisherId:(id)anId4 redirect:(BOOL)redirect;
+(void)setRedirectUrl:(id)url;
+(void)setUseCookieTracking:(BOOL)tracking;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state receipt:(id)receipt;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items referenceId:(id)anId;
+(void)measureActionWithEventId:(int)eventId eventItems:(id)items;
+(void)measureActionWithEventId:(int)eventId referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureActionWithEventId:(int)eventId referenceId:(id)anId;
+(void)measureActionWithEventId:(int)eventId;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state receipt:(id)receipt;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code transactionState:(int)state;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action eventItems:(id)items revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action eventItems:(id)items referenceId:(id)anId;
+(void)measureAction:(id)action eventItems:(id)items;
+(void)measureAction:(id)action referenceId:(id)anId revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action revenueAmount:(float)amount currencyCode:(id)code;
+(void)measureAction:(id)action referenceId:(id)anId;
+(void)measureAction:(id)action;
+(id)tuneEventItemFromMATEventItem:(id)mateventItem;
+(id)tuneEventFromMATEvent:(id)matevent;
+(void)measureEvent:(id)event;
+(void)measureEventId:(int)anId;
+(void)measureEventName:(id)name;
+(void)measureSession;
+(void)removeiAd;
+(void)displayiAdInView:(id)view;
+(BOOL)isPayingUser;
+(id)openLogId;
+(id)matId;
+(void)setFacebookEventLogging:(BOOL)logging limitEventAndDataUsage:(BOOL)usage;
+(void)setPreloadData:(id)data;
+(void)setPayingUser:(BOOL)user;
+(void)setBluetoothState:(int)state;
+(void)setLocationAuthorizationStatus:(int)status;
+(void)setPluginName:(id)name;
+(void)setAppAdTracking:(BOOL)tracking;
+(void)setLatitude:(double)latitude longitude:(double)longitude altitude:(double)altitude;
+(void)setLatitude:(double)latitude longitude:(double)longitude;
+(void)setGender:(int)gender;
+(void)setAge:(int)age;
+(void)setGoogleUserId:(id)anId;
+(void)setTwitterUserId:(id)anId;
+(void)setFacebookUserId:(id)anId;
+(void)setPhoneNumber:(id)number;
+(void)setUserName:(id)name;
+(void)setUserId:(id)anId;
+(void)setUserEmail:(id)email;
+(void)setTRUSTeId:(id)anId;
+(void)setSiteId:(id)anId;
+(void)setShouldAutoGenerateAppleVendorIdentifier:(BOOL)autoGenerateAppleVendorIdentifier;
+(void)setShouldAutoDetectJailbroken:(BOOL)autoDetectJailbroken;
+(void)setShouldAutoCollectDeviceLocation:(BOOL)autoCollectDeviceLocation;
+(void)setShouldAutoCollectAppleAdvertisingIdentifier:(BOOL)autoCollectAppleAdvertisingIdentifier;
+(void)setPackageName:(id)name;
+(void)setJailbroken:(BOOL)jailbroken;
+(void)setCurrencyCode:(id)code;
+(void)setAppleVendorIdentifier:(id)identifier;
+(void)setAppleAdvertisingIdentifier:(id)identifier advertisingTrackingEnabled:(BOOL)enabled;
+(void)setExistingUser:(BOOL)user;
+(void)automateIapEventMeasurement:(BOOL)measurement;
+(void)checkForDeferredDeeplink:(id)deferredDeeplink;
+(void)setDelegate:(id)delegate;
+(void)setAllowDuplicateRequests:(BOOL)requests;
+(void)setDebugMode:(BOOL)mode;
+(void)initializeWithMATAdvertiserId:(id)matadvertiserId MATConversionKey:(id)key MATPackageName:(id)name wearable:(BOOL)wearable;
+(void)initializeWithMATAdvertiserId:(id)matadvertiserId MATConversionKey:(id)key;
+(void)initialize;
@end

