/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDictionary.h>


@interface NSDictionary (FBAdUtility)
-(id)attemptRecoveryOfObject:(id)object ofClass:(Class)aClass;
-(id)objectForKeyOrNil:(id)keyOrNil ofClass:(Class)aClass;
-(id)arrayForKey:(id)key orDefault:(id)aDefault;
-(id)arrayForKeyOrNil:(id)keyOrNil;
-(id)dictionaryForKey:(id)key orDefault:(id)aDefault;
-(id)dictionaryForKeyOrNil:(id)keyOrNil;
-(BOOL)boolForKey:(id)key orDefault:(BOOL)aDefault;
-(float)CGFloatForKey:(id)key orDefault:(float)aDefault;
-(double)doubleForKey:(id)key orDefault:(double)aDefault;
-(unsigned)unsignedIntegerForKey:(id)key orDefault:(unsigned)aDefault;
-(int)integerForKey:(id)key orDefault:(int)aDefault;
-(id)numberForKey:(id)key orDefault:(id)aDefault;
-(id)numberForKeyOrNil:(id)keyOrNil;
-(id)stringForKey:(id)key orDefault:(id)aDefault;
-(id)stringForKeyOrNil:(id)keyOrNil;
-(id)objectForKey:(id)key orDefault:(id)aDefault;
-(id)objectForKeyOrNil:(id)keyOrNil;
@end

@interface NSDictionary (CBValidations)
-(BOOL)matchesPredicate:(id)predicate error:(id*)error;
-(BOOL)matchesMask:(id)mask allowExtraKeys:(BOOL)keys error:(id*)error;
@end

@interface NSDictionary (ATFunctionalCollectionExtensions)
-(id)delete:(id)aDelete;
-(id)merge:(id)merge;
-(id)objects;
-(id)keys;
-(id)inject:(id)inject initial:(id)initial;
-(id)filter:(id)filter;
-(id)map:(id)map;
-(void)each:(id)each;
@end

@interface NSDictionary (CBJSONCollectionDescriptions)
-(id)CBJSONCollectionDescriptions_descriptionWithLocale:(id)locale;
@end

