/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSNumberFormatter.h>


@interface NSNumberFormatter (FBAdUtility)
+(id)defaultFormatter;
-(id)safeNumberFromString:(id)string;
@end

