/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSString.h>


@interface NSString (FBAdUtility)
-(id)fb_URLEncodedString;
@end

@interface NSString (TuneURLEncoding)
-(id)urlEncodeUsingEncoding:(unsigned)encoding;
@end

@interface NSString (TuneGTMNSStringXMLAdditions)
-(id)Tunegtm_stringBySanitizingToXMLSpec;
-(id)Tunegtm_stringBySanitizingAndEscapingForXML;
@end

@interface NSString (TuneURLEncoding)
-(id)urlEncodeUsingEncoding:(unsigned)encoding;
@end

@interface NSString (TuneGTMNSStringXMLAdditions)
-(id)Tunegtm_stringBySanitizingToXMLSpec;
-(id)Tunegtm_stringBySanitizingAndEscapingForXML;
@end

@interface NSString (TuneURLEncoding)
-(id)urlEncodeUsingEncoding:(unsigned)encoding;
@end

@interface NSString (TuneGTMNSStringXMLAdditions)
-(id)Tunegtm_stringBySanitizingToXMLSpec;
-(id)Tunegtm_stringBySanitizingAndEscapingForXML;
@end

