//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OpenUDID.h"

@interface OpenUDIDiOS : OpenUDID
{
}

- (id)getPasteboardWithName:(id)arg1 shouldCreate:(_Bool)arg2 setPersistent:(_Bool)arg3;
- (id)getDataForPasteboard:(id)arg1;
- (void)setDict:(id)arg1 forPasteboard:(id)arg2;

@end

