//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFBaseState.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"
#import "PFBaseStateSubclass.h"

@class NSDictionary, NSString;

@interface PFACLState : PFBaseState <PFBaseStateSubclass, NSCopying, NSMutableCopying>
{
    NSDictionary *_permissions;
    _Bool _shared;
}

+ (id)stateWithState:(id)arg1 mutatingBlock:(CDUnknownBlockType)arg2;
+ (id)stateWithState:(id)arg1;
+ (id)propertyAttributes;
@property(nonatomic, getter=isShared) _Bool shared; // @synthesize shared=_shared;
@property(copy, nonatomic) NSDictionary *permissions; // @synthesize permissions=_permissions;
- (void).cxx_destruct;
- (id)copyByMutatingWithBlock:(CDUnknownBlockType)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithState:(id)arg1 mutatingBlock:(CDUnknownBlockType)arg2;
- (id)initWithState:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

