/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFFieldOperation.h"

@class NSArray;

@interface PFAddUniqueOperation : PFFieldOperation {
	NSArray* _objects;
}
@property(readonly, assign, nonatomic) NSArray* objects;
+(id)addUniqueWithObjects:(id)objects;
-(void).cxx_destruct;
-(id)applyToValue:(id)value forKey:(id)key;
-(id)mergeWithPrevious:(id)previous;
-(id)encodeWithObjectEncoder:(id)objectEncoder;
-(id)description;
-(id)initWithObjects:(id)objects;
@end

