//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PFAnalytics : NSObject
{
}

+ (void)trackEventInBackground:(id)arg1 dimensions:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (id)trackEvent:(id)arg1 dimensions:(id)arg2;
+ (void)trackEventInBackground:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)trackEvent:(id)arg1;
+ (void)trackAppOpenedWithRemoteNotificationPayloadInBackground:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)trackAppOpenedWithRemoteNotificationPayload:(id)arg1;
+ (void)trackAppOpenedWithLaunchOptionsInBackground:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)trackAppOpenedWithLaunchOptions:(id)arg1;

@end

