/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class PFEventuallyQueue;
@protocol PFEventuallyQueueProvider;

@interface PFAnalyticsController : NSObject {
	id<PFEventuallyQueueProvider> _dataSource;
}
@property(readonly, assign, nonatomic) __weak PFEventuallyQueue* eventuallyQueue;
@property(readonly, assign, nonatomic) __weak id<PFEventuallyQueueProvider> dataSource;
+(id)controllerWithDataSource:(id)dataSource;
-(void).cxx_destruct;
-(id)trackEventAsyncWithName:(id)name dimensions:(id)dimensions sessionToken:(id)token;
-(id)trackAppOpenedEventAsyncWithRemoteNotificationPayload:(id)remoteNotificationPayload sessionToken:(id)token;
-(id)initWithDataSource:(id)dataSource;
-(id)init;
@end

