/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFAnalytics : NSObject {
}
+(void)trackEventInBackground:(id)background dimensions:(id)dimensions block:(id)block;
+(id)trackEvent:(id)event dimensions:(id)dimensions;
+(void)trackEventInBackground:(id)background block:(id)block;
+(id)trackEvent:(id)event;
+(void)trackAppOpenedWithRemoteNotificationPayloadInBackground:(id)background block:(id)block;
+(id)trackAppOpenedWithRemoteNotificationPayload:(id)remoteNotificationPayload;
+(void)trackAppOpenedWithLaunchOptionsInBackground:(id)background block:(id)block;
+(id)trackAppOpenedWithLaunchOptions:(id)launchOptions;
@end

