/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFAnonymousUtils : NSObject {
}
+(id)_lazyLogIn;
+(void)_clearAuthenticationProvider;
+(id)_authenticationProvider;
+(id)_providerAccessQueue;
+(BOOL)isLinkedWithUser:(id)user;
+(void)logInWithTarget:(id)target selector:(SEL)selector;
+(void)logInWithBlock:(id)block;
+(id)logInInBackground;
@end

