/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class BFTask;
@protocol OS_dispatch_queue;

@interface PFAsyncTaskQueue : NSObject {
	NSObject<OS_dispatch_queue>* _syncQueue;
	BFTask* _tail;
}
@property(retain, nonatomic) BFTask* tail;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* syncQueue;
+(id)taskQueue;
-(void).cxx_destruct;
-(id)enqueue:(id)enqueue;
-(id)init;
@end

