/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFKeyValueCacheProvider.h"
#import "PFInstallationIdentifierStoreProvider.h"
#import "PFCommandRunnerProvider.h"
#import "PFKeychainStoreProvider.h"
#import "PFFileManagerProvider.h"
#import "PFOfflineStoreProvider.h"

@class PFInstallationIdentifierStore;

@protocol PFCoreManagerDataSource <PFCommandRunnerProvider, PFKeychainStoreProvider, PFFileManagerProvider, PFOfflineStoreProvider, PFKeyValueCacheProvider, PFInstallationIdentifierStoreProvider>
@property(readonly, assign, nonatomic) PFInstallationIdentifierStore* installationIdentifierStore;
@end

