//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFCancellationToken, BFTask, NSString, NSURL, PFRESTCommand;

@protocol PFCommandRunning <NSObject>
+ (id)commandRunnerWithDataSource:(id <PFInstallationIdentifierStoreProvider>)arg1 applicationId:(NSString *)arg2 clientKey:(NSString *)arg3;
@property(nonatomic) double initialRetryDelay;
@property(readonly, copy, nonatomic) NSString *clientKey;
@property(readonly, copy, nonatomic) NSString *applicationId;
@property(readonly, nonatomic) __weak id <PFInstallationIdentifierStoreProvider> dataSource;
- (BFTask *)runFileDownloadCommandAsyncWithFileURL:(NSURL *)arg1 targetFilePath:(NSString *)arg2 cancellationToken:(BFCancellationToken *)arg3 progressBlock:(void (^)(int))arg4;
- (BFTask *)runFileUploadCommandAsync:(PFRESTCommand *)arg1 withContentType:(NSString *)arg2 contentSourceFilePath:(NSString *)arg3 options:(unsigned long long)arg4 cancellationToken:(BFCancellationToken *)arg5 progressBlock:(void (^)(int))arg6;
- (BFTask *)runCommandAsync:(PFRESTCommand *)arg1 withOptions:(unsigned long long)arg2 cancellationToken:(BFCancellationToken *)arg3;
- (BFTask *)runCommandAsync:(PFRESTCommand *)arg1 withOptions:(unsigned long long)arg2;
- (id)initWithDataSource:(id <PFInstallationIdentifierStoreProvider>)arg1 applicationId:(NSString *)arg2 clientKey:(NSString *)arg3;
@end

