/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@protocol PFInstallationIdentifierStoreProvider;

@interface PFCommandURLRequestConstructor : NSObject {
	id<PFInstallationIdentifierStoreProvider> _dataSource;
}
@property(readonly, assign, nonatomic) __weak id<PFInstallationIdentifierStoreProvider> dataSource;
+(id)defaultURLRequestHeadersForApplicationId:(id)applicationId clientKey:(id)key bundle:(id)bundle;
+(id)constructorWithDataSource:(id)dataSource;
-(void).cxx_destruct;
-(id)_URLRequestHeadersForCommand:(id)command;
-(id)fileUploadURLRequestForCommand:(id)command withContentType:(id)contentType contentSourceFilePath:(id)path;
-(id)dataURLRequestForCommand:(id)command;
-(id)initWithDataSource:(id)dataSource;
-(id)init;
@end

