//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHTTPURLResponse, NSString;

@interface PFCommandResult : NSObject
{
    id _result;
    NSString *_resultString;
    NSHTTPURLResponse *_httpResponse;
}

+ (id)commandResultWithResult:(id)arg1 resultString:(id)arg2 httpResponse:(id)arg3;
@property(readonly, nonatomic) NSHTTPURLResponse *httpResponse; // @synthesize httpResponse=_httpResponse;
@property(readonly, copy, nonatomic) NSString *resultString; // @synthesize resultString=_resultString;
@property(readonly, nonatomic) id result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)initWithResult:(id)arg1 resultString:(id)arg2 httpResponse:(id)arg3;
- (id)init;

@end

