/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFEventuallyQueueSubclass.h"
#import "PFEventuallyQueue.h"

@class NSString;

@interface PFCommandCache : PFEventuallyQueue <PFEventuallyQueueSubclass> {
	unsigned _fileCounter;
	NSString* _diskCachePath;
	unsigned long long _diskCacheSize;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned long long diskCacheSize;
@property(readonly, copy, nonatomic) NSString* diskCachePath;
+(id)newDefaultCommandCacheWithCommandRunner:(id)commandRunner cacheFolderPath:(id)path;
-(void).cxx_destruct;
-(void)_createDiskCachePathIfNeeded;
-(id)_filePathForCommandWithIdentifier:(id)identifier;
-(id)_removeFileForCommandWithIdentifier:(id)identifier;
-(id)_saveCommandToCacheInBackground:(id)background object:(id)object identifier:(id)identifier;
-(void)_setDiskCacheSize:(unsigned long long)size;
-(id)_cleanupDiskCacheWithRequiredFreeSize:(unsigned)requiredFreeSize;
-(id)_waitForOperationSet:(id)operationSet eventuallyPin:(id)pin;
-(id)_didFinishRunningCommand:(id)command withIdentifier:(id)identifier resultTask:(id)task;
-(id)_enqueueCommandInBackground:(id)background object:(id)object identifier:(id)identifier;
-(id)_commandWithIdentifier:(id)identifier error:(id*)error;
-(id)_pendingCommandIdentifiers;
-(id)_newIdentifierForCommand:(id)command;
-(void)_simulateReboot;
-(void)removeAllCommands;
-(id)initWithCommandRunner:(id)commandRunner maxAttemptsCount:(unsigned)count retryInterval:(double)interval diskCachePath:(id)path diskCacheSize:(unsigned long long)size;
-(id)initWithCommandRunner:(id)commandRunner maxAttemptsCount:(unsigned)count retryInterval:(double)interval;
@end

