/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;
@protocol PFInstallationIdentifierStoreProvider;

@protocol PFCommandRunning <NSObject>
@property(assign, nonatomic) double initialRetryDelay;
@property(readonly, copy, nonatomic) NSString* clientKey;
@property(readonly, copy, nonatomic) NSString* applicationId;
@property(readonly, assign, nonatomic) __weak id<PFInstallationIdentifierStoreProvider> dataSource;
+(id)commandRunnerWithDataSource:(id)dataSource applicationId:(id)anId clientKey:(id)key;
-(id)runFileDownloadCommandAsyncWithFileURL:(id)fileURL targetFilePath:(id)path cancellationToken:(id)token progressBlock:(id)block;
-(id)runFileUploadCommandAsync:(id)async withContentType:(id)contentType contentSourceFilePath:(id)path options:(unsigned)options cancellationToken:(id)token progressBlock:(id)block;
-(id)runCommandAsync:(id)async withOptions:(unsigned)options cancellationToken:(id)token;
-(id)runCommandAsync:(id)async withOptions:(unsigned)options;
-(id)initWithDataSource:(id)dataSource applicationId:(id)anId clientKey:(id)key;
@end

