//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFExecutor, NSObject<OS_dispatch_queue>, NSString, PFConfig, PFFileManager;

@interface PFCurrentConfigController : NSObject
{
    NSObject<OS_dispatch_queue> *_dataQueue;
    BFExecutor *_dataExecutor;
    PFConfig *_currentConfig;
    PFFileManager *_fileManager;
}

+ (id)controllerWithFileManager:(id)arg1;
@property(readonly, nonatomic) PFFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *configFilePath;
- (id)clearMemoryCachedCurrentConfigAsync;
- (id)clearCurrentConfigAsync;
- (id)setCurrentConfigAsync:(id)arg1;
- (id)getCurrentConfigAsync;
- (id)initWithFileManager:(id)arg1;
- (id)init;

@end

