/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface PFDevice : NSObject {
}
@property(readonly, assign, nonatomic, getter=isJailbroken) BOOL jailbroken;
@property(readonly, copy, nonatomic) NSString* operatingSystemBuild;
@property(readonly, copy, nonatomic) NSString* operatingSystemVersion;
@property(readonly, copy, nonatomic) NSString* operatingSystemFullVersion;
@property(readonly, copy, nonatomic) NSString* detailedModel;
+(id)currentDevice;
@end

