/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFDecoder : NSObject {
}
+(id)objectDecoder;
-(id)decodeObject:(id)object;
-(id)decodeArray:(id)array;
-(id)_decodePointerForClassName:(id)className localId:(id)anId;
-(id)_decodePointerForClassName:(id)className objectId:(id)anId;
-(id)decodeDictionary:(id)dictionary;
@end

