/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PFEventuallyQueueSubclass <NSObject>
-(id)_waitForOperationSet:(id)operationSet eventuallyPin:(id)pin;
-(id)_enqueueCommandInBackground:(id)background object:(id)object identifier:(id)identifier;
-(id)_commandWithIdentifier:(id)identifier error:(id*)error;
-(id)_pendingCommandIdentifiers;
-(id)_newIdentifierForCommand:(id)command;
@end

