/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFObject.h"
#import "PFSubclassing.h"

@class NSString;
@protocol PFNetworkCommand;

@interface PFEventuallyPin : PFObject <PFSubclassing> {
}
@property(readonly, assign, nonatomic) id<PFNetworkCommand> command;
@property(readonly, copy, nonatomic) NSString* sessionToken;
@property(readonly, copy, nonatomic) NSString* operationSetUUID;
@property(readonly, assign, nonatomic) PFObject* object;
@property(readonly, assign, nonatomic) unsigned type;
@property(readonly, copy, nonatomic) NSString* uuid;
+(unsigned)_pinTypeForCommand:(id)command;
+(id)_pinEventually:(id)eventually type:(unsigned)type uuid:(id)uuid operationSetUUID:(id)uuid4 sessionToken:(id)token commandDictionary:(id)dictionary;
+(id)findAllEventuallyPinWithExcludeUUIDs:(id)excludeUUIDs;
+(id)findAllEventuallyPin;
+(id)pinEventually:(id)eventually forCommand:(id)command withUUID:(id)uuid;
+(id)pinEventually:(id)eventually forCommand:(id)command;
+(void)_assertValidInstanceClassName:(id)name;
+(id)parseClassName;
-(BOOL)needsDefaultACL;
@end

