//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFObject.h"

#import "PFSubclassing.h"

@class NSString;

@interface PFEventuallyPin : PFObject <PFSubclassing>
{
}

+ (unsigned long long)_pinTypeForCommand:(id)arg1;
+ (id)_pinEventually:(id)arg1 type:(unsigned long long)arg2 uuid:(id)arg3 operationSetUUID:(id)arg4 sessionToken:(id)arg5 commandDictionary:(id)arg6;
+ (id)findAllEventuallyPinWithExcludeUUIDs:(id)arg1;
+ (id)findAllEventuallyPin;
+ (id)pinEventually:(id)arg1 forCommand:(id)arg2 withUUID:(id)arg3;
+ (id)pinEventually:(id)arg1 forCommand:(id)arg2;
+ (void)_assertValidInstanceClassName:(id)arg1;
+ (id)parseClassName;
@property(readonly, nonatomic) id <PFNetworkCommand> command;
@property(readonly, copy, nonatomic) NSString *sessionToken;
@property(readonly, copy, nonatomic) NSString *operationSetUUID;
@property(readonly, nonatomic) PFObject *object;
@property(readonly, nonatomic) unsigned long long type;
@property(readonly, copy, nonatomic) NSString *uuid;
- (_Bool)needsDefaultACL;

@end

