/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@protocol OS_dispatch_semaphore;

@interface PFEventuallyQueueTestHelper : NSObject {
	NSObject<OS_dispatch_semaphore>* events[6];
}
-(void).cxx_destruct;
-(BOOL)waitFor:(int)aFor;
-(void)notify:(int)notify;
-(void)clear;
-(id)init;
@end

