//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_semaphore>;

@interface PFEventuallyQueueTestHelper : NSObject
{
    NSObject<OS_dispatch_semaphore> *events[6];
}

- (void).cxx_destruct;
- (_Bool)waitFor:(int)arg1;
- (void)notify:(int)arg1;
- (void)clear;
- (id)init;

@end

