/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary;

@interface PFFieldOperationDecoder : NSObject {
	NSMutableDictionary* _operationDecoders;
}
+(id)defaultDecoder;
-(void).cxx_destruct;
-(id)decode:(id)decode withDecoder:(id)decoder;
-(void)_registerDefaultOperationDecoders;
-(void)_registerDecoderForOperationWithName:(id)name block:(id)block;
-(id)init;
@end

