/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "NSCopying.h"
#import "NSCoding.h"
#import "wotblitz-Structs.h"


@interface PFGeoPoint : NSObject <NSCopying, NSCoding> {
	double _latitude;
	double _longitude;
}
@property(assign, nonatomic) double longitude;
@property(assign, nonatomic) double latitude;
+(id)geoPointWithDictionary:(id)dictionary;
+(void)geoPointForCurrentLocationInBackground:(id)background;
+(id)geoPointWithLatitude:(double)latitude longitude:(double)longitude;
+(id)geoPointWithLocation:(id)location;
+(id)geoPoint;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)initWithEncodedDictionary:(id)encodedDictionary;
-(id)encodeIntoDictionary;
-(double)distanceInKilometersTo:(id)to;
-(double)distanceInMilesTo:(id)to;
-(double)distanceInRadiansTo:(id)to;
@end

