//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString, PFFileManager;

@interface PFInstallationIdentifierStore : NSObject
{
    NSObject<OS_dispatch_queue> *_synchronizationQueue;
    PFFileManager *_fileManager;
    NSString *_installationIdentifier;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *installationIdentifierFilePath;
- (void)_clearCachedInstallationIdentifier;
- (void)_loadInstallationIdentifier;
- (void)clearInstallationIdentifier;
@property(copy, nonatomic) NSString *installationIdentifier; // @synthesize installationIdentifier=_installationIdentifier;
- (id)initWithFileManager:(id)arg1;
- (id)init;

@end

