//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFInstallation.h"

@interface PFInstallation (Private)
+ (id)_currentInstallationController;
+ (void)_assertValidInstanceClassName:(id)arg1;
+ (void)initialize;
- (id)handleSaveResultAsync:(id)arg1;
- (id)displayClassName;
- (void)_markAllFieldsDirty;
- (_Bool)_isCurrentInstallation;
- (id)_validateDeleteAsync;
- (void)_clearDeviceToken;
@end

