/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSDictionary;
@protocol OS_dispatch_queue;

@interface PFKeychainStore : NSObject {
	NSObject<OS_dispatch_queue>* _synchronizationQueue;
	NSString* _service;
	NSDictionary* _keychainQueryTemplate;
}
@property(readonly, copy, nonatomic) NSDictionary* keychainQueryTemplate;
@property(readonly, copy, nonatomic) NSString* service;
+(id)_keychainQueryTemplateForService:(id)service;
-(void).cxx_destruct;
-(BOOL)removeAllObjects;
-(BOOL)_removeObjectForKey:(id)key;
-(BOOL)removeObjectForKey:(id)key;
-(BOOL)setObject:(id)object forKeyedSubscript:(id)keyedSubscript;
-(BOOL)setObject:(id)object forKey:(id)key;
-(id)_dataForKey:(id)key;
-(id)objectForKeyedSubscript:(id)keyedSubscript;
-(id)objectForKey:(id)key;
-(id)initWithService:(id)service;
-(id)init;
@end

