/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFDecoder.h"

@class NSDictionary;

@interface PFKnownParseObjectDecoder : PFDecoder {
	NSDictionary* _fetchedObjects;
}
@property(copy, nonatomic) NSDictionary* fetchedObjects;
+(id)decoderWithFetchedObjects:(id)fetchedObjects;
-(void).cxx_destruct;
-(id)_decodePointerForClassName:(id)className objectId:(id)anId;
@end

