//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSBundle, NSMutableSet, NSString, UIApplication;

@interface PFLocationManager : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_locationManager;
    NSBundle *_bundle;
    UIApplication *_application;
    NSMutableSet *_blockSet;
}

+ (id)_newSystemLocationManager;
@property(retain, nonatomic) NSMutableSet *blockSet; // @synthesize blockSet=_blockSet;
@property(retain, nonatomic) UIApplication *application; // @synthesize application=_application;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void).cxx_destruct;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)addBlockForCurrentLocation:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithSystemLocationManager:(id)arg1 application:(id)arg2 bundle:(id)arg3;
- (id)initWithSystemLocationManager:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

