//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFUserState.h"

@class NSDictionary, NSString;

@interface PFMutableUserState : PFUserState
{
}


// Remaining properties
@property(copy, nonatomic) NSDictionary *authData; // @dynamic authData;
@property(nonatomic) _Bool isNew; // @dynamic isNew;
@property(copy, nonatomic) NSString *sessionToken; // @dynamic sessionToken;
@end

