//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSLocking.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface PFMultiProcessFileLock : NSObject <NSLocking>
{
    NSObject<OS_dispatch_queue> *_synchronizationQueue;
    int _fileDescriptor;
    NSString *_filePath;
    NSString *_lockFilePath;
}

+ (id)lockForFileWithPath:(id)arg1;
@property(copy, nonatomic) NSString *lockFilePath; // @synthesize lockFilePath=_lockFilePath;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (void).cxx_destruct;
- (_Bool)_tryLock;
- (void)unlock;
- (void)lock;
- (void)dealloc;
- (id)initForFileWithPath:(id)arg1;
- (id)init;

@end

