//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSTimer;

@interface PFNetworkActivityIndicatorManager : NSObject
{
    NSObject<OS_dispatch_queue> *_networkActivityAccessQueue;
    _Bool _enabled;
    unsigned long long _networkActivityCount;
    NSTimer *_activityIndicatorVisibilityTimer;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSTimer *activityIndicatorVisibilityTimer; // @synthesize activityIndicatorVisibilityTimer=_activityIndicatorVisibilityTimer;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)_handleDidReceiveURLResponseNotification:(id)arg1;
- (void)_handleWillSendURLRequestNotification:(id)arg1;
- (void)_updateNetworkActivityIndicatorVisibility;
- (void)_updateNetworkActivityIndicatorVisibilityAfterDelay;
- (void)decrementActivityCount;
- (void)incrementActivityCount;
@property(readonly, nonatomic, getter=isNetworkActivityIndicatorVisible) _Bool networkActivityIndicatorVisible;
@property(nonatomic) unsigned long long networkActivityCount; // @synthesize networkActivityCount=_networkActivityCount;
- (void)dealloc;
- (id)init;

@end

