//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol PFNetworkCommand <NSObject>
+ (_Bool)isValidDictionaryRepresentation:(NSDictionary *)arg1;
+ (id)commandFromDictionaryRepresentation:(NSDictionary *)arg1;
@property(copy, nonatomic) NSString *localId;
@property(readonly, copy, nonatomic) NSString *operationSetUUID;
@property(readonly, copy, nonatomic) NSString *sessionToken;
- (void)resolveLocalIds;
- (NSDictionary *)dictionaryRepresentation;
@end

