/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFObjectUtilities : NSObject {
}
+(BOOL)isObject:(id)object equalToObject:(id)object2;
+(void)applyOperationSet:(id)set toDictionary:(id)dictionary;
+(id)newValueByApplyingFieldOperation:(id)operation toDictionary:(id)dictionary forKey:(id)key;
@end

