/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface PFObjectSubclassInfo : NSObject {
	NSObject<OS_dispatch_queue>* _dataAccessQueue;
	NSMutableDictionary* _knownProperties;
	NSMutableDictionary* _knownMethodSignatures;
	Class _subclass;
}
@property(retain) Class subclass;
+(id)subclassInfoWithSubclass:(Class)subclass;
-(void).cxx_destruct;
-(id)_rawPropertyInfoForSelector:(SEL)selector;
-(id)forwardingMethodSignatureForSelector:(SEL)selector;
-(id)propertyInfoForSelector:(SEL)selector isSetter:(BOOL*)setter;
-(id)initWithSubclass:(Class)subclass;
-(id)init;
@end

