//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PFObjectLocalIdStoreMapEntry : NSObject
{
    int _referenceCount;
    NSString *_objectId;
}

@property int referenceCount; // @synthesize referenceCount=_referenceCount;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
- (void).cxx_destruct;
- (void)writeToFile:(id)arg1;
- (id)initWithFile:(id)arg1;
- (id)init;

@end

