/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PFObjectPrivateSubclass <NSObject>
+(id)_newObjectStateWithParseClassName:(id)parseClassName objectId:(id)anId isComplete:(BOOL)complete;
@optional
-(void)_objectWillSave;
@end

