/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"
#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSMutableDictionary, NSDate, NSString, NSDictionary;

@interface PFObjectState : NSObject <NSCopying, NSMutableCopying> {
	NSString* _parseClassName;
	NSString* _objectId;
	NSDate* _createdAt;
	NSDate* _updatedAt;
	NSMutableDictionary* _serverData;
	BOOL _complete;
	BOOL _deleted;
}
@property(assign, nonatomic, getter=isDeleted) BOOL deleted;
@property(assign, nonatomic, getter=isComplete) BOOL complete;
@property(copy, nonatomic) NSDictionary* serverData;
@property(retain, nonatomic) NSDate* updatedAt;
@property(retain, nonatomic) NSDate* createdAt;
@property(copy, nonatomic) NSString* objectId;
@property(copy, nonatomic) NSString* parseClassName;
+(id)stateWithParseClassName:(id)parseClassName objectId:(id)anId isComplete:(BOOL)complete;
+(id)stateWithParseClassName:(id)parseClassName;
+(id)stateWithState:(id)state;
-(void).cxx_destruct;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)copyWithZone:(NSZone*)zone;
-(void)applyOperationSet:(id)set;
-(void)applyState:(id)state;
-(void)setUpdatedAtFromString:(id)string;
-(void)setCreatedAtFromString:(id)string;
-(void)removeServerDataObjectsForKeys:(id)keys;
-(void)removeServerDataObjectForKey:(id)key;
-(void)setServerDataObject:(id)object forKey:(id)key;
-(id)dictionaryRepresentationWithObjectEncoder:(id)objectEncoder;
-(id)initWithParseClassName:(id)parseClassName objectId:(id)anId isComplete:(BOOL)complete;
-(id)initWithParseClassName:(id)parseClassName;
-(id)initWithState:(id)state;
-(id)init;
@end

