/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@protocol PFFileManagerProvider;

@interface PFObjectFilePersistenceController : NSObject {
	id<PFFileManagerProvider> _dataSource;
}
@property(readonly, assign, nonatomic) __weak id<PFFileManagerProvider> dataSource;
+(id)controllerWithDataSource:(id)dataSource;
-(void).cxx_destruct;
-(id)persistObjectAsync:(id)async forKey:(id)key;
-(id)loadPersistentObjectAsyncForKey:(id)key;
-(id)initWithDataSource:(id)dataSource;
-(id)init;
@end

