/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PFObjectControlling <NSObject>
-(id)processDeleteResultAsync:(id)async forObject:(id)object;
-(id)deleteObjectAsync:(id)async withSessionToken:(id)sessionToken;
-(id)processFetchResultAsync:(id)async forObject:(id)object;
-(id)fetchObjectAsync:(id)async withSessionToken:(id)sessionToken;
@end

