//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface PFObjectLocalIdStore : NSObject
{
    NSString *_diskPath;
    NSObject *_lock;
    NSMutableDictionary *_inMemoryCache;
    id <PFFileManagerProvider> _dataSource;
}

+ (_Bool)isLocalId:(id)arg1;
+ (id)storeWithDataSource:(id)arg1;
@property(readonly, nonatomic) __weak id <PFFileManagerProvider> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)clearInMemoryCache;
- (_Bool)clear;
- (id)objectIdForLocalId:(id)arg1;
- (void)setObjectId:(id)arg1 forLocalId:(id)arg2;
- (void)releaseLocalIdOnDisk:(id)arg1;
- (void)retainLocalIdOnDisk:(id)arg1;
- (id)createLocalId;
- (void)removeMapEntry:(id)arg1;
- (void)putMapEntry:(id)arg1 forLocalId:(id)arg2;
- (id)getMapEntry:(id)arg1;
- (id)initWithDataSource:(id)arg1;
- (id)init;

@end

