/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "NSObject.h"

@class PFObjectBatchController;
@protocol PFCommandRunnerProvider;

@protocol PFObjectBatchController <NSObject>
@property(readonly, assign, nonatomic) PFObjectBatchController* objectBatchController;
@end

@interface PFObjectBatchController : NSObject {
	id<PFCommandRunnerProvider> _dataSource;
}
@property(readonly, assign, nonatomic) __weak id<PFCommandRunnerProvider> dataSource;
+(id)uniqueObjectsArrayFromArray:(id)array usingFilter:(id)filter;
+(id)uniqueObjectsArrayFromArray:(id)array omitObjectsWithData:(BOOL)data;
+(id)controllerWithDataSource:(id)dataSource;
-(void).cxx_destruct;
-(id)_processDeleteResultsAsync:(id)async forObjects:(id)objects;
-(id)_deleteCommandForObjects:(id)objects withSessionToken:(id)sessionToken;
-(id)deleteObjectsAsync:(id)async withSessionToken:(id)sessionToken;
-(id)_processFetchResultAsync:(id)async forObjects:(id)objects;
-(id)_fetchCommandForObjects:(id)objects withSessionToken:(id)sessionToken;
-(id)fetchObjectsAsync:(id)async withSessionToken:(id)sessionToken;
-(id)initWithDataSource:(id)dataSource;
-(id)init;
@end

