/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFDecoder.h"

@class NSDictionary;

@interface PFOfflineDecoder : PFDecoder {
	NSDictionary* _offlineObjects;
}
@property(copy, nonatomic) NSDictionary* offlineObjects;
+(id)decoderWithOfflineObjects:(id)offlineObjects;
-(void).cxx_destruct;
-(id)decodeObject:(id)object;
@end

