//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFQueryController.h"

#import "PFQueryControllerSubclass.h"

@class NSString, PFOfflineStore;

@interface PFOfflineQueryController : PFQueryController <PFQueryControllerSubclass>
{
    PFOfflineStore *_offlineStore;
    id <PFPinningObjectStoreProvider> _coreDataSource;
}

+ (id)controllerWithCommonDataSource:(id)arg1 coreDataSource:(id)arg2;
@property(readonly, nonatomic) __weak id <PFPinningObjectStoreProvider> coreDataSource; // @synthesize coreDataSource=_coreDataSource;
- (void).cxx_destruct;
- (id)runNetworkCommandAsync:(id)arg1 withCancellationToken:(id)arg2 forQueryState:(id)arg3;
- (id)_countObjectsFromLocalDatastoreAsyncForQueryState:(id)arg1 withCancellationToken:(id)arg2 user:(id)arg3;
- (id)countObjectsAsyncForQueryState:(id)arg1 withCancellationToken:(id)arg2 user:(id)arg3;
- (id)_findObjectsFromLocalDatastoreAsyncForQueryState:(id)arg1 withCancellationToken:(id)arg2 user:(id)arg3;
- (id)_findObjectsAsyncInRelation:(id)arg1 ofObject:(id)arg2 forQueryState:(id)arg3 withCancellationToken:(id)arg4 user:(id)arg5;
- (id)findObjectsAsyncForQueryState:(id)arg1 withCancellationToken:(id)arg2 user:(id)arg3;
- (id)initWithCommonDataSource:(id)arg1 coreDataSource:(id)arg2;
- (id)initWithCommonDataSource:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) __weak id <PFCommandRunnerProvider><PFOfflineStoreProvider> commonDataSource; // @dynamic commonDataSource;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

