/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSFastEnumeration.h"
#import </libobjc.A.h>
#import "wotblitz-Structs.h"
#import "NSCopying.h"

@class NSMutableDictionary, NSDate, NSString;

@interface PFOperationSet : NSObject <NSCopying, NSFastEnumeration> {
	BOOL _saveEventually;
	NSString* _uuid;
	NSDate* _updatedAt;
	NSMutableDictionary* _dictionary;
}
@property(retain, nonatomic) NSMutableDictionary* dictionary;
@property(copy, nonatomic) NSDate* updatedAt;
@property(readonly, copy, nonatomic) NSString* uuid;
@property(assign, nonatomic, getter=isSaveEventually) BOOL saveEventually;
+(id)operationSetFromRESTDictionary:(id)restdictionary usingDecoder:(id)decoder;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)removeAllObjects;
-(void)removeObjectForKey:(id)key;
-(void)setObject:(id)object forKeyedSubscript:(id)keyedSubscript;
-(void)setObject:(id)object forKey:(id)key;
-(void)enumerateKeysAndObjectsUsingBlock:(id)block;
-(id)keyEnumerator;
-(unsigned)count;
-(id)objectForKeyedSubscript:(id)keyedSubscript;
-(id)objectForKey:(id)key;
-(id)RESTDictionaryUsingObjectEncoder:(id)encoder operationSetUUIDs:(id*)uuids;
-(void)mergeOperationSet:(id)set;
-(id)initWithUUID:(id)uuid;
-(id)init;
@end

