/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFEncoder.h"


@interface PFPointerOrLocalIdObjectEncoder : PFEncoder {
}
+(id)objectEncoder;
-(id)encodeParseObject:(id)object;
@end

