/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSString;

@interface PFPropertyInfo : NSObject {
	unsigned char _associationType;
	BOOL _object;
	NSString* _name;
	Class _sourceClass;
	NSString* _typeEncoding;
	objc_ivar* _ivar;
	SEL _getterSelector;
	SEL _setterSelector;
}
@property(readonly, assign) SEL setterSelector;
@property(readonly, assign) SEL getterSelector;
@property(readonly, assign) objc_ivar* ivar;
@property(readonly, copy) NSString* typeEncoding;
@property(readonly, assign, getter=isObject) BOOL object;
@property(readonly, assign) Class sourceClass;
@property(readonly, assign, nonatomic) unsigned char associationType;
@property(readonly, copy, nonatomic) NSString* name;
+(id)propertyInfoWithClass:(Class)aClass name:(id)name associationType:(unsigned char)type;
+(id)propertyInfoWithClass:(Class)aClass name:(id)name;
-(void).cxx_destruct;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)takeValueFrom:(id)from toObject:(id)object;
-(void)setWrappedValue:(id)value forObject:(id)object;
-(id)getWrappedValueFrom:(id)from;
-(id)initWithClass:(Class)aClass name:(id)name associationType:(unsigned char)type;
-(id)initWithClass:(Class)aClass name:(id)name;
-(id)init;
@end

