/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFPropertyAttributes : NSObject {
	unsigned char _associationType;
}
@property(readonly, assign, nonatomic) unsigned char associationType;
+(id)attributesWithAssociationType:(unsigned char)associationType;
+(id)attributes;
-(id)initWithAssociationType:(unsigned char)associationType;
-(id)init;
@end

