//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PFCurrentInstallationController;

@interface PFPushChannelsController : NSObject
{
    id <PFCurrentInstallationControllerProvider> _dataSource;
}

+ (id)controllerWithDataSource:(id)arg1;
@property(readonly, nonatomic) __weak id <PFCurrentInstallationControllerProvider> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
@property(readonly, nonatomic) PFCurrentInstallationController *currentInstallationController;
- (id)_getCurrentObjectAsync;
- (id)unsubscribeFromChannelAsyncWithName:(id)arg1;
- (id)subscribeToChannelAsyncWithName:(id)arg1;
- (id)getSubscribedChannelsAsync;
- (id)initWithDataSource:(id)arg1;
- (id)init;

@end

