//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PFPurchase : NSObject
{
}

+ (id)_purchaseController;
+ (id)assetContentPathForProduct:(id)arg1;
+ (void)downloadAssetForTransaction:(id)arg1 completion:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
+ (void)downloadAssetForTransaction:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)restore;
+ (void)buyProduct:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)addObserverForProduct:(id)arg1 block:(CDUnknownBlockType)arg2;

@end

