/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PFPushInternalUtils <NSObject>
@optional
+(void)playAudioWithName:(id)name;
+(void)playVibrate;
+(void)showAlertViewWithTitle:(id)title message:(id)message;
+(void)clearDeviceToken;
+(id)getDeviceTokenFromKeychain;
+(id)convertDeviceTokenToString:(id)string;
@end

