//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle, PFFileManager, PFPaymentTransactionObserver, PFProductsRequestHandler, SKPaymentQueue;

@interface PFPurchaseController : NSObject
{
    PFProductsRequestHandler *_currentProductsRequestHandler;
    SKPaymentQueue *_paymentQueue;
    PFPaymentTransactionObserver *_transactionObserver;
    id <PFCommandRunning> _commandRunner;
    PFFileManager *_fileManager;
    NSBundle *_bundle;
    Class _productsRequestClass;
}

+ (id)controllerWithCommandRunner:(id)arg1 fileManager:(id)arg2 bundle:(id)arg3;
@property(nonatomic) Class productsRequestClass; // @synthesize productsRequestClass=_productsRequestClass;
@property(readonly, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(readonly, nonatomic) PFFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(readonly, nonatomic) id <PFCommandRunning> commandRunner; // @synthesize commandRunner=_commandRunner;
@property(retain, nonatomic) SKPaymentQueue *paymentQueue; // @synthesize paymentQueue=_paymentQueue;
- (void).cxx_destruct;
@property(readonly, nonatomic) PFPaymentTransactionObserver *transactionObserver; // @synthesize transactionObserver=_transactionObserver;
- (_Bool)canPurchase;
- (id)assetContentPathForProductWithIdentifier:(id)arg1 fileName:(id)arg2;
- (id)downloadAssetAsyncForTransaction:(id)arg1 withProgressBlock:(CDUnknownBlockType)arg2 sessionToken:(id)arg3;
- (id)buyProductAsyncWithIdentifier:(id)arg1;
- (id)findProductsAsyncWithIdentifiers:(id)arg1;
- (void)dealloc;
- (id)initWithCommandRunner:(id)arg1 fileManager:(id)arg2 bundle:(id)arg3;
- (id)init;

@end

