//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PFQueryControllerSubclass.h"

@class NSString;

@interface PFQueryController : NSObject <PFQueryControllerSubclass>
{
    id <PFCommandRunnerProvider> _commonDataSource;
}

+ (id)controllerWithCommonDataSource:(id)arg1;
@property(readonly, nonatomic) __weak id <PFCommandRunnerProvider> commonDataSource; // @synthesize commonDataSource=_commonDataSource;
- (void).cxx_destruct;
- (id)runNetworkCommandAsync:(id)arg1 withCancellationToken:(id)arg2 forQueryState:(id)arg3;
- (void)clearAllCachedResults;
- (void)clearCachedResultForQueryState:(id)arg1 sessionToken:(id)arg2;
- (_Bool)hasCachedResultForQueryState:(id)arg1 sessionToken:(id)arg2;
- (id)cacheKeyForQueryState:(id)arg1 sessionToken:(id)arg2;
- (id)countObjectsAsyncForQueryState:(id)arg1 withCancellationToken:(id)arg2 user:(id)arg3;
- (id)findObjectsAsyncForQueryState:(id)arg1 withCancellationToken:(id)arg2 user:(id)arg3;
- (id)initWithCommonDataSource:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

