//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFCancellationToken, BFTask, PFQueryState, PFRESTCommand;

@protocol PFQueryControllerSubclass <NSObject>
- (BFTask *)runNetworkCommandAsync:(PFRESTCommand *)arg1 withCancellationToken:(BFCancellationToken *)arg2 forQueryState:(PFQueryState *)arg3;
@end

