/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFQueryUtilities : NSObject {
}
+(id)objectNotFoundError;
+(id)regexStringForString:(id)string;
+(id)_hoistCommonPredicates:(id)predicates;
+(id)_normalizeToDNF:(id)dnf;
+(void)assertNoPredicateModifiers:(id)modifiers;
+(id)asOrOfAnds:(id)ands;
+(id)reverseYodaConditions:(id)conditions;
+(id)removeBetween:(id)between;
+(id)removeNegation:(id)negation;
+(id)_negatePredicate:(id)predicate;
+(id)_mapPredicate:(id)predicate compoundBlock:(id)block comparisonBlock:(id)block3;
+(id)predicateByNormalizingPredicate:(id)predicate;
@end

