/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFRESTCommand.h"


@interface PFRESTObjectCommand : PFRESTCommand {
}
+(id)deleteObjectCommandForObjectState:(id)objectState withSessionToken:(id)sessionToken;
+(id)updateObjectCommandForObjectState:(id)objectState changes:(id)changes operationSetUUID:(id)uuid sessionToken:(id)token;
+(id)createObjectCommandForObjectState:(id)objectState changes:(id)changes operationSetUUID:(id)uuid sessionToken:(id)token;
+(id)fetchObjectCommandForObjectState:(id)objectState withSessionToken:(id)sessionToken;
@end

