/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFFieldOperation.h"

@class NSString, NSMutableSet;

@interface PFRelationOperation : PFFieldOperation {
	NSString* targetClass;
	NSMutableSet* _relationsToAdd;
	NSMutableSet* _relationsToRemove;
}
@property(retain, nonatomic) NSMutableSet* relationsToRemove;
@property(retain, nonatomic) NSMutableSet* relationsToAdd;
@property(copy, nonatomic) NSString* targetClass;
+(id)removeRelationToObjects:(id)objects;
+(id)addRelationToObjects:(id)objects;
-(void).cxx_destruct;
-(id)applyToValue:(id)value forKey:(id)key;
-(id)mergeWithPrevious:(id)previous;
-(id)encodeWithObjectEncoder:(id)objectEncoder;
-(id)_convertToArrayInSet:(id)set withObjectEncoder:(id)objectEncoder;
-(id)description;
-(id)init;
@end

