/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface PFReachability : NSObject {
	NSObject<OS_dispatch_queue>* _synchronizationQueue;
	NSMutableArray* _listenersArray;
	SCNetworkReachabilityRef _networkReachability;
	unsigned _flags;
}
@property(assign, nonatomic) unsigned flags;
@property(readonly, assign, nonatomic) unsigned char currentState;
+(id)sharedParseReachability;
+(BOOL)_reachabilityStateForFlags:(unsigned)flags;
-(void).cxx_destruct;
-(void)_startMonitoringReachabilityWithURL:(id)url;
-(void)_notifyAllListeners;
-(void)removeAllListeners;
-(void)removeListener:(id)listener;
-(void)addListener:(id)listener;
-(void)dealloc;
-(id)initWithURL:(id)url;
-(id)init;
@end

