//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFObject.h"

#import "PFSubclassing.h"

@class NSString, PFRelation;

@interface PFRole : PFObject <PFSubclassing>
{
}

+ (id)parseClassName;
+ (void)_assertValidInstanceClassName:(id)arg1;
+ (id)roleWithName:(id)arg1 acl:(id)arg2;
+ (id)roleWithName:(id)arg1;
- (id)saveInBackground;
- (void)setObject:(id)arg1 forKey:(id)arg2;
@property(readonly, nonatomic) PFRelation *users;
@property(readonly, nonatomic) PFRelation *roles;
- (id)initWithName:(id)arg1 acl:(id)arg2;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *name; // @dynamic name;

@end

