/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@protocol PFCommandRunnerProvider;

@interface PFSessionController : NSObject {
	id<PFCommandRunnerProvider> _dataSource;
}
@property(readonly, assign, nonatomic) __weak id<PFCommandRunnerProvider> dataSource;
+(id)controllerWithDataSource:(id)dataSource;
-(void).cxx_destruct;
-(id)getCurrentSessionAsyncWithSessionToken:(id)sessionToken;
-(id)initWithDataSource:(id)dataSource;
@end

