/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFFieldOperation.h"


@interface PFSetOperation : PFFieldOperation {
	id _value;
}
@property(readonly, assign, nonatomic) id value;
+(id)setWithValue:(id)value;
-(void).cxx_destruct;
-(id)applyToValue:(id)value forKey:(id)key;
-(id)mergeWithPrevious:(id)previous;
-(id)encodeWithObjectEncoder:(id)objectEncoder;
-(id)description;
-(id)initWithValue:(id)value;
-(id)init;
@end

