//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFExecutor, BFTask, BFTaskCompletionSource, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface PFSQLiteDatabase : NSObject
{
    BFTaskCompletionSource *_databaseClosedTaskCompletionSource;
    NSObject<OS_dispatch_queue> *_databaseQueue;
    BFExecutor *_databaseExecutor;
    NSMutableDictionary *_cachedStatements;
    struct sqlite3 *_database;
    NSString *_databasePath;
}

+ (id)databaseWithPath:(id)arg1;
@property(copy, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
@property(nonatomic) struct sqlite3 *database; // @synthesize database=_database;
- (void).cxx_destruct;
@property(readonly, nonatomic) BFTask *databaseClosedTask;
- (id)_errorWithErrorCode:(int)arg1 errorMessage:(id)arg2 domain:(id)arg3;
- (id)_errorWithErrorCode:(int)arg1 errorMessage:(id)arg2;
- (id)_errorWithErrorCode:(int)arg1;
- (void)_cacheStatement:(id)arg1 forQuery:(id)arg2;
- (id)_cachedStatementForQuery:(id)arg1;
- (void)_clearCachedStatements;
- (void)_bindObject:(id)arg1 toColumn:(int)arg2 inStatement:(id)arg3;
- (id)executeSQLAsync:(id)arg1 withArgumentsInArray:(id)arg2;
- (id)executeQueryAsync:(id)arg1 withArgumentsInArray:(id)arg2;
- (id)executeCachedQueryAsync:(id)arg1 withArgumentsInArray:(id)arg2;
- (id)_executeQueryAsync:(id)arg1 withArgumentsInArray:(id)arg2 cachingEnabled:(_Bool)arg3;
- (id)rollbackAsync;
- (id)commitAsync;
- (id)beginTransactionAsync;
- (id)closeAsync;
- (id)openAsync;
- (id)isOpenAsync;
- (id)initWithPath:(id)arg1;

@end

