//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFTask;

@interface PFTaskQueue : NSObject
{
    NSObject *_mutex;
    BFTask *_tail;
}

@property(retain, nonatomic) BFTask *tail; // @synthesize tail=_tail;
@property(retain, nonatomic) NSObject *mutex; // @synthesize mutex=_mutex;
- (void).cxx_destruct;
- (id)enqueue:(CDUnknownBlockType)arg1;
- (id)init;

@end

