/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "NSURLSessionDelegate.h"
#import "NSURLSessionTaskDelegate.h"

@class NSString, NSMutableDictionary, NSURLSession;
@protocol OS_dispatch_queue, PFURLSessionDelegate;

@interface PFURLSession : NSObject <NSURLSessionDelegate, NSURLSessionTaskDelegate> {
	NSObject<OS_dispatch_queue>* _sessionTaskQueue;
	NSURLSession* _urlSession;
	NSMutableDictionary* _delegatesDictionary;
	NSObject<OS_dispatch_queue>* _delegatesAccessQueue;
	id<PFURLSessionDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) __weak id<PFURLSessionDelegate> delegate;
+(id)sessionWithURLSession:(id)urlsession delegate:(id)delegate;
+(id)sessionWithConfiguration:(id)configuration delegate:(id)delegate;
-(void).cxx_destruct;
-(void)URLSession:(id)session dataTask:(id)task willCacheResponse:(id)response completionHandler:(id)handler;
-(void)URLSession:(id)session dataTask:(id)task didReceiveData:(id)data;
-(void)URLSession:(id)session dataTask:(id)task didReceiveResponse:(id)response completionHandler:(id)handler;
-(void)URLSession:(id)session task:(id)task didCompleteWithError:(id)error;
-(void)URLSession:(id)session task:(id)task didSendBodyData:(long long)data totalBytesSent:(long long)sent totalBytesExpectedToSend:(long long)send;
-(void)_removeDelegateForTaskWithIdentifier:(id)identifier;
-(void)setDelegate:(id)delegate forDataTask:(id)dataTask;
-(id)_taskDelegateForDataTask:(id)dataTask;
-(id)_performDataTask:(id)task withDelegate:(id)delegate;
-(id)performFileDownloadURLRequestAsync:(id)async toFileAtPath:(id)path withCancellationToken:(id)cancellationToken progressBlock:(id)block;
-(id)performFileUploadURLRequestAsync:(id)async forCommand:(id)command withContentSourceFilePath:(id)contentSourceFilePath cancellationToken:(id)token progressBlock:(id)block;
-(id)performDataURLRequestAsync:(id)async forCommand:(id)command cancellationToken:(id)token;
-(void)invalidateAndCancel;
-(id)initWithURLSession:(id)urlsession delegate:(id)delegate;
-(id)initWithConfiguration:(id)configuration delegate:(id)delegate;
-(id)init;
@end

