//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLRequest, NSURLResponse, PFURLSession;

@protocol PFURLSessionDelegate <NSObject>
- (void)urlSession:(PFURLSession *)arg1 didPerformURLRequest:(NSURLRequest *)arg2 withURLResponse:(NSURLResponse *)arg3 responseString:(NSString *)arg4;
- (void)urlSession:(PFURLSession *)arg1 willPerformURLRequest:(NSURLRequest *)arg2;
@end

