/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PFObjectFileCodingLogic.h"


@interface PFUserFileCodingLogic : PFObjectFileCodingLogic {
}
-(void)updateObject:(id)object fromDictionary:(id)dictionary usingDecoder:(id)decoder;
@end

