//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFUser.h"

@interface PFUser (Private)
+ (id)userController;
+ (id)authenticationController;
+ (id)objectFileCodingLogic;
+ (id)_upgradeToRevocableSessionInBackground;
+ (void)_setRevocableSessionEnabled:(_Bool)arg1;
+ (_Bool)_isRevocableSessionEnabled;
+ (id)_revocableSessionSynchronizationQueue;
+ (id)logInLazyUserWithAuthType:(id)arg1 authData:(id)arg2;
+ (void)_assertValidInstanceClassName:(id)arg1;
+ (id)_getCurrentUserSessionTokenAsync;
+ (id)currentSessionToken;
- (id)_upgradeToRevocableSessionInBackground;
- (id)RESTDictionaryWithObjectEncoder:(id)arg1 operationSetUUIDs:(id *)arg2 state:(id)arg3 operationSetQueue:(id)arg4;
- (void)mergeFromRESTDictionary:(id)arg1 withDecoder:(id)arg2;
- (id)_constructSaveCommandForChanges:(id)arg1 sessionToken:(id)arg2 objectEncoder:(id)arg3;
- (void)restoreAnonymity:(id)arg1;
- (void)stripAnonymity;
- (id)signUpAsync:(id)arg1;
- (id)_logOutAsyncWithAuthType:(id)arg1;
- (id)resolveLazinessAsync:(id)arg1;
- (void)synchronizeAllAuthData;
- (void)synchronizeAuthDataWithAuthType:(id)arg1;
- (void)_mergeFromServerWithResult:(id)arg1 decoder:(id)arg2 completeData:(_Bool)arg3;
- (id)mergeFromObject:(id)arg1;
- (void)cleanUpAuthData;
- (id)handleSignUpResultAsync:(id)arg1;
- (id)_handleServiceLoginCommandResult:(id)arg1;
- (id)_currentServiceLoginCommandForChanges:(id)arg1;
- (id)_currentSignUpCommandForChanges:(id)arg1;
- (id)handleSaveResultAsync:(id)arg1;
- (id)_convertToDictionaryForSaving:(id)arg1 withObjectEncoder:(id)arg2;
- (id)_validateSignUpAsync;
- (void)_checkSaveParametersWithCurrentUser:(id)arg1;
- (id)displayClassName;
- (id)_validateSaveEventuallyAsync;
- (id)_validateDeleteAsync;
- (_Bool)needsDefaultACL;
- (void)setDefaultValues;
@end

