//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFObject.h"

#import "PFObjectPrivateSubclass.h"
#import "PFSubclassing.h"

@class NSMutableDictionary, NSMutableSet, NSString, PFUserState;

@interface PFUser : PFObject <PFObjectPrivateSubclass, PFSubclassing>
{
    _Bool isCurrentUser;
    NSMutableDictionary *authData;
    NSMutableSet *linkedServiceNames;
    _Bool isLazy;
}

+ (id)_newObjectStateWithParseClassName:(id)arg1 objectId:(id)arg2 isComplete:(_Bool)arg3;
+ (void)enableAutomaticUser;
+ (id)user;
+ (void)logOutInBackgroundWithBlock:(CDUnknownBlockType)arg1;
+ (id)logOutInBackground;
+ (void)logOut;
+ (void)requestPasswordResetForEmailInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+ (void)requestPasswordResetForEmailInBackground:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)requestPasswordResetForEmailInBackground:(id)arg1;
+ (_Bool)requestPasswordResetForEmail:(id)arg1 error:(id *)arg2;
+ (_Bool)requestPasswordResetForEmail:(id)arg1;
+ (void)enableRevocableSessionInBackgroundWithBlock:(CDUnknownBlockType)arg1;
+ (id)enableRevocableSessionInBackground;
+ (void)becomeInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+ (void)becomeInBackground:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)becomeInBackground:(id)arg1;
+ (id)become:(id)arg1 error:(id *)arg2;
+ (id)become:(id)arg1;
+ (void)_unregisterAuthenticationDelegateForAuthType:(id)arg1;
+ (id)logInWithAuthTypeInBackground:(id)arg1 authData:(id)arg2;
+ (void)registerAuthenticationDelegate:(id)arg1 forAuthType:(id)arg2;
+ (void)logInWithUsernameInBackground:(id)arg1 password:(id)arg2 target:(id)arg3 selector:(SEL)arg4;
+ (void)logInWithUsernameInBackground:(id)arg1 password:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (id)logInWithUsernameInBackground:(id)arg1 password:(id)arg2;
+ (id)logInWithUsername:(id)arg1 password:(id)arg2 error:(id *)arg3;
+ (id)logInWithUsername:(id)arg1 password:(id)arg2;
+ (id)currentUser;
+ (id)parseClassName;
- (void).cxx_destruct;
- (void)signUpInBackgroundWithBlock:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSString *sessionToken;
@property(readonly) _Bool isNew;
- (_Bool)_isAuthenticatedWithCurrentUser:(id)arg1;
- (_Bool)isAuthenticated;
- (void)signUpInBackgroundWithTarget:(id)arg1 selector:(SEL)arg2;
- (id)signUpInBackground;
- (_Bool)signUp:(id *)arg1;
- (_Bool)signUp;
- (void)fetchInBackgroundWithBlock:(CDUnknownBlockType)arg1;
- (id)fetch:(id *)arg1;
- (id)fetchAsync:(id)arg1;
- (id)saveAsync:(id)arg1;
@property(readonly, nonatomic) NSMutableSet *linkedServiceNames; // @dynamic linkedServiceNames;
@property(readonly, nonatomic) NSMutableDictionary *authData; // @dynamic authData;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)_logOutAsync;
- (_Bool)isLinkedWithAuthType:(id)arg1;
- (id)unlinkWithAuthTypeInBackground:(id)arg1;
- (id)linkWithAuthTypeInBackground:(id)arg1 authData:(id)arg2;
@property(nonatomic) _Bool isCurrentUser;

// Remaining properties
@property(copy, nonatomic) PFUserState *_state; // @dynamic _state;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSString *email; // @dynamic email;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isLazy; // @dynamic isLazy;
@property(retain, nonatomic) NSString *password; // @dynamic password;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *username; // @dynamic username;

@end

