/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface PFWeakValue : NSObject {
	id _weakObject;
}
@property(assign, nonatomic) __weak id weakObject;
+(id)valueWithWeakObject:(id)weakObject;
-(void).cxx_destruct;
@end

