/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>

@class NSTimer;

__attribute__((visibility("hidden")))
@interface RenderView : UIView {
	BOOL animating;
	BOOL displayLinkSupported;
	int animationFrameInterval;
	id displayLink;
	NSTimer* animationTimer;
	bool isLoading;
	bool isLoaded;
	int currFPS;
	bool blockDrawView;
	bool limitKeyboardFps;
}
@property(assign, nonatomic) int animationFrameInterval;
@property(readonly, assign, nonatomic, getter=isAnimating) BOOL animating;
-(void)keyboardDidFrameChanged:(id)keyboard;
-(void)unblockDrawing;
-(void)blockDrawing;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)process:(int)process touch:(id)touch withEvent:(id)event;
-(void)stopAnimation;
-(void)startAnimation;
-(void)drawView:(id)view;
-(id)initWithFrame:(CGRect)frame;
@end

