/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class RenderView, BackgroundView;

__attribute__((visibility("hidden")))
@interface RenderViewController : UIViewController {
	RenderView* renderView;
	BackgroundView* backgroundView;
}
@property(readonly, assign, nonatomic) RenderView* renderView;
@property(readonly, assign, nonatomic) BackgroundView* backgroundView;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(id)createMetalView;
-(id)createGLView;
-(id)init;
@end

