/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class AdmobSettings, UASettings;

__attribute__((visibility("hidden")))
@interface Settings : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) UASettings* uaSettings;
@property(assign, nonatomic) BOOL hasUaSettings;
@property(retain, nonatomic) AdmobSettings* admobSettings;
@property(assign, nonatomic) BOOL hasAdmobSettings;
+(id)descriptor;
@end

