/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, SingularSqliteHandler;

@interface SingularKeyValueStore : NSObject {
	SingularSqliteHandler* sqliteHandler;
	long maximumEventRecordsCount;
	NSString* _namespaceValue;
}
@property(retain, nonatomic) NSString* namespaceValue;
-(void).cxx_destruct;
-(id)allItems;
-(BOOL)removeNamespace:(id)aNamespace;
-(BOOL)removeForKey:(id)key;
-(BOOL)boolForKey:(id)key;
-(int)integerForKey:(id)key;
-(id)stringForKey:(id)key;
-(BOOL)setBool:(BOOL)aBool forKey:(id)key;
-(BOOL)setString:(id)string forKey:(id)key;
-(BOOL)setInteger:(int)integer forKey:(id)key;
-(id)valueForKey:(id)key withType:(int)type;
-(BOOL)setValue:(id)value forKey:(id)key withType:(int)type;
-(id)initWithNamespace:(id)aNamespace;
-(id)init;
@end

