/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>

@class NSString, SingularCollector, SingularSessionManager, SingularEventStore, SingularEventReporter, SingularCountersStore;

@interface SingularController : NSObject {
	SingularSessionManager* sessionManager;
	SingularEventStore* eventStore;
	SingularCountersStore* countersStore;
	SingularEventReporter* eventReporter;
	SingularCollector* collector;
	unsigned singlePostEventLimit;
	BOOL exponentialBackoff;
	unsigned exponentialBackoffExponent;
	NSString* _apiKey;
	NSString* _appId;
	dispatch_queue_s* networking_queue;
	dispatch_queue_s* networking_aggregation_queue;
	dispatch_queue_s* data_queue;
	dispatch_semaphore_s* initWithApiKeySem;
	BOOL initialized;
	BOOL is_device_tracking_disabled;
	BOOL is_sandbox_enabled;
	BOOL disableSender;
	BOOL isDebugBuild;
	SingularCollector* _collector;
	SingularEventReporter* _eventReporter;
	SingularCountersStore* _counterStore;
	SingularEventStore* _eventStore;
}
@property(retain, nonatomic) SingularEventStore* eventStore;
@property(retain, nonatomic) SingularCountersStore* counterStore;
@property(retain, nonatomic) SingularEventReporter* eventReporter;
@property(retain, nonatomic) SingularCollector* collector;
-(void).cxx_destruct;
-(id)getSessionManager;
-(long long)queuedEventsCount;
-(void)setSandboxMode:(BOOL)mode;
-(void)setDeviceTrackingDisabled:(BOOL)disabled;
-(void)postEventInner;
-(void)postEvent:(id)event withAttributes:(id)attributes isSpecialEvent:(BOOL)event3 skipAggregation:(BOOL)aggregation;
-(void)filterAndHandleNonSerializableFields:(id)fields andDepth:(unsigned)depth andMaxDepth:(unsigned)depth3;
-(id)filterAndHandleNonSerializableFields:(id)fields;
-(BOOL)isJsonSerializable:(id)serializable;
-(id)mutableContainerFromImmutable:(id)immutable;
-(id)singularId;
-(void)initWithApiKey:(id)apiKey andAppId:(id)anId;
-(id)init;
@end

