/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class SingularCountersStore, SingularSqliteHandler;

@interface SingularEventStore : NSObject {
	SingularSqliteHandler* sqliteHandler;
	SingularCountersStore* countersStore;
}
+(id)sharedStorage;
-(void).cxx_destruct;
-(id)eventsWithLimit:(unsigned)limit;
-(id)eventsRecord;
-(long long)eventCount;
-(long long)oldestEventId;
-(BOOL)deleteAllEvents;
-(BOOL)deleteEventWithIdSmallerThan:(long long)idSmallerThan;
-(BOOL)deleteEventWithId:(long long)anId;
-(BOOL)addEvent:(id)event;
-(BOOL)createEventTable;
-(int)maxEventsStored;
-(id)init;
-(id)initWithSqlHandler:(id)sqlHandler;
@end

