/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, SingularController, SingularKeyValueStore, SingularCountersStore;

@interface SingularSessionManager : NSObject {
	NSString* sessionId;
	double sessionStart;
	double sessionPause;
	SingularKeyValueStore* keyValueStore;
	SingularCountersStore* countersStore;
	id _sessionPostBlock;
	SingularController* _controller;
}
@property(retain, nonatomic) SingularController* controller;
@property(copy, nonatomic) id sessionPostBlock;
-(void).cxx_destruct;
-(id)currentSessionId;
-(void)sendSessionEndEvent;
-(void)startNewSession;
-(void)deleteSession;
-(void)startNewSessionOrContinueSavedSession;
-(void)applicationWillEnterForeground;
-(void)applicationDidEnterBackground;
-(void)registerNotificationObservers;
-(void)dealloc;
-(id)initWithSessionPostBlock:(id)sessionPostBlock andController:(id)controller;
-(id)init;
@end

