/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"


@interface SingularSqliteHandler : NSObject {
	void* sqliteFrameworkHandle;
	sqlite3* _databaseHandler;
}
@property(readonly, assign) sqlite3* databaseHandler;
+(id)sharedHandler;
-(void)printSqliteError;
-(BOOL)executeQuery:(id)query withStepBlock:(id)stepBlock completionBlock:(id)block withArguments:(id)arguments;
-(BOOL)dropAllTables;
-(BOOL)createTableWithQuery:(id)query;
-(BOOL)openDatabaseWithFilepath:(id)filepath;
-(id)fallbackDbLocation;
-(id)defaultDbLocation;
-(void)deleteDbFile;
-(BOOL)initializeDb;
-(id)init;
-(void)dynamicLoadFrameworkWithMethods;
-(id)initWithDatabaseFileName:(id)databaseFileName;
@end

