/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGAddRemoveSetPopulator.h"
#import </libobjc.A.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface TAGAddRemoveMacrosPopulator : NSObject <TAGAddRemoveSetPopulator> {
	NSDictionary* _addMacros;
	NSDictionary* _removeMacros;
}
@property(retain, nonatomic) NSDictionary* removeMacros;
@property(retain, nonatomic) NSDictionary* addMacros;
-(void).cxx_destruct;
-(void)rulePassed:(id)passed add:(id)add remove:(id)remove;
-(id)initWithAddMacros:(id)addMacros removeMacros:(id)macros;
@end

