/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "TAGAdIdAccess.h"
#import "NSObject.h"

@class NSString;

@protocol TAGAdIdAccess <NSObject>
+(BOOL)retrieveTrackingFlag;
+(id)retrieveId;
@end

__attribute__((visibility("hidden")))
@interface TAGAdIdAccess : NSObject <TAGAdIdAccess> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(BOOL)retrieveTrackingFlag;
+(id)retrieveId;
+(void)load;
@end

