/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGAddRemoveSetPopulator.h"
#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface TAGAddRemoveTagsPopulator : NSObject <TAGAddRemoveSetPopulator> {
}
-(void)rulePassed:(id)passed add:(id)add remove:(id)remove;
@end

