/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface TAGDispatchUtil : NSObject {
}
+(id)systemCountryFromLocale:(id)locale;
+(id)systemLanguageFromLanguages:(id)languages;
+(id)userAgentStringWithProduct:(id)product version:(id)version deviceModel:(id)model systemName:(id)name systemVersion:(id)version5 systemLanguage:(id)language systemCountry:(id)country;
+(id)userAgentString;
+(id)thread;
+(void)threadMain:(id)main;
+(id)databaseFullURL:(id)url;
+(id)databaseFullPath:(id)path;
+(void)background:(id)background wait:(BOOL)wait;
@end

