/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGFunctionCallImplementation.h"

@class TAGRuntime;

__attribute__((visibility("hidden")))
@interface TAGEventMacro : TAGFunctionCallImplementation {
	TAGRuntime* _runtime;
}
@property(readonly, assign) __weak TAGRuntime* runtime;
+(id)functionId;
-(void).cxx_destruct;
-(id)evaluate:(id)evaluate;
-(BOOL)isCacheable;
-(id)initWithRuntime:(id)runtime;
@end

