/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, TAGPValue;

__attribute__((visibility("hidden")))
@interface TAGExpandedFunctionCallBuilder : NSObject {
	NSMutableDictionary* _propertiesMap;
	TAGPValue* _pushAfterEvaluate;
}
@property(retain, nonatomic) TAGPValue* pushAfterEvaluate;
@property(retain, nonatomic) NSMutableDictionary* propertiesMap;
-(void).cxx_destruct;
-(id)build;
-(void)addPropertyWithValue:(id)value forKey:(id)key;
-(id)init;
@end

