/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSDate;

__attribute__((visibility("hidden")))
@interface TAGHit : NSManagedObject {
}
@property(retain, nonatomic) NSDate* lastDispatchTime;
@property(retain, nonatomic) NSDate* dispatchTime;
@property(retain, nonatomic) NSNumber* retryCount;
@property(retain, nonatomic) NSDate* timestamp;
@property(retain, nonatomic) NSString* dispatchURL;
@end

