/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGFunctionCallImplementation.h"


__attribute__((visibility("hidden")))
@interface TAGJoinerMacro : TAGFunctionCallImplementation {
}
+(id)functionId;
-(id)escape:(id)escape escapeType:(int)type charsToBackslashEscape:(id)backslashEscape;
-(void)addTo:(id)to charsInString:(id)string;
-(id)evaluate:(id)evaluate;
-(BOOL)isCacheable;
-(id)init;
@end

