/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, NSString, TAGDataLayer;
@protocol TAGLogger;

__attribute__((visibility("hidden")))
@interface TAGManager : NSObject {
	NSString* _ctfeServerAddress;
	int _refreshMode;
	TAGDataLayer* _dataLayer;
	NSMutableDictionary* _containers;
}
@property(retain) NSMutableDictionary* containers;
@property(copy) NSString* ctfeServerAddress;
@property(assign, nonatomic) double dispatchInterval;
@property(readonly, assign, nonatomic) TAGDataLayer* dataLayer;
@property(assign, nonatomic) int refreshMode;
@property(retain, nonatomic) id<TAGLogger> logger;
+(void)notCalled;
+(void)clearManagerInstance;
+(id)instance;
-(void).cxx_destruct;
-(void)dispatchWithCompletionHandler:(id)completionHandler;
-(void)dispatch;
-(void)refreshTagsInAllContainers:(id)allContainers;
-(id)containerById:(id)anId;
-(void)removeContainerById:(id)anId;
-(BOOL)previewWithUrl:(id)url;
-(id)getContainerById:(id)anId;
-(id)openContainerById:(id)anId callback:(id)callback;
-(id)initWithSameInstance:(BOOL)sameInstance;
-(id)init;
@end

