/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface TAGModel : NSObject {
}
+(id)requestHitsWithLimit:(unsigned)limit lastDispatchedBefore:(id)before;
+(id)requestHitsWithLimit:(unsigned)limit;
+(id)model;
+(id)contextWithURL:(id)url;
+(id)coordinatorWithURL:(id)url;
+(BOOL)migrateToCurrentVersion:(id)currentVersion;
+(id)previousModelDescription;
+(id)modelDescription;
+(id)modelWithDescription:(id)description;
+(id)entityWithDescription:(id)description;
@end

