/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSData;

__attribute__((visibility("hidden")))
@interface TAGPBCodedInputStream : NSObject {
	NSData* buffer_;
	TAGPBInputBufferState state_;
	int lastTag_;
	unsigned recursionDepth_;
}
+(id)streamWithData:(id)data;
-(BOOL)isAtEnd;
-(unsigned long)bytesUntilLimit;
-(void)popLimit:(unsigned long)limit;
-(unsigned long)pushLimit:(unsigned long)limit;
-(long long)readSInt64;
-(int)readSInt32;
-(long long)readSFixed64;
-(int)readSFixed32;
-(int)readEnum;
-(unsigned)readUInt32;
-(id)readData;
-(void)readMessage:(id)message extensionRegistry:(id)registry;
-(void)readUnknownGroup:(int)group builder:(id)builder;
-(void)readGroup:(int)group builder:(id)builder extensionRegistry:(id)registry;
-(id)readString;
-(BOOL)readBool;
-(unsigned)readFixed32;
-(unsigned long long)readFixed64;
-(int)readInt32;
-(long long)readInt64;
-(unsigned long long)readUInt64;
-(float)readFloat;
-(double)readDouble;
-(void)skipMessage;
-(BOOL)skipField:(int)field;
-(void)checkLastTagWas:(int)was;
-(int)readTag;
-(void)dealloc;
-(id)initWithData:(id)data;
@end

