/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGFunctionCallImplementation.h"


__attribute__((visibility("hidden")))
@interface TAGPredicate : TAGFunctionCallImplementation {
}
+(id)arg1Key;
+(id)arg0Key;
-(BOOL)evaluateNoDefaultValues:(id)values arg1:(id)a1 parameters:(id)parameters;
-(BOOL)isCacheable;
-(id)evaluate:(id)evaluate;
-(id)initWithFunctionId:(id)functionId;
@end

