/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPBFieldOptions : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBMutableArray* uninterpretedOptionArray;
@property(assign, nonatomic) BOOL hasUninterpretedOptionArray;
@property(assign, nonatomic) BOOL deprecatedRawMessage;
@property(assign, nonatomic) BOOL hasDeprecatedRawMessage;
@property(retain, nonatomic) TAGPBMutableArray* upgradedOptionArray;
@property(assign, nonatomic) BOOL hasUpgradedOptionArray;
@property(assign, nonatomic) BOOL weak;
@property(assign, nonatomic) BOOL hasWeak;
@property(assign, nonatomic) BOOL deprecated;
@property(assign, nonatomic) BOOL hasDeprecated;
@property(assign, nonatomic) BOOL lazy;
@property(assign, nonatomic) BOOL hasLazy;
@property(assign, nonatomic) int jstype;
@property(assign, nonatomic) BOOL hasJstype;
@property(assign, nonatomic) int jtype;
@property(assign, nonatomic) BOOL hasJtype;
@property(assign, nonatomic) BOOL packed;
@property(assign, nonatomic) BOOL hasPacked;
@property(assign, nonatomic) int ctype;
@property(assign, nonatomic) BOOL hasCtype;
+(id)descriptor;
@end

