/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import "TAGPBArray.h"

@protocol TAGPBMutableArrayDelegate;

__attribute__((visibility("hidden")))
@interface TAGPBMutableArray : TAGPBArray {
	unsigned long _mutationCount;
	id<TAGPBMutableArrayDelegate> _delegate;
}
@property(assign, nonatomic) id<TAGPBMutableArrayDelegate> delegate;
+(id)arrayWithValueType:(int)valueType capacity:(unsigned)capacity;
-(void)removeAllValues;
-(void)appendValues:(const void*)values valueType:(int)type count:(unsigned)count;
-(void)appendArray:(id)array;
-(void)setArray:(id)array;
-(void)replaceDoubleAtIndex:(unsigned)index withDouble:(double)aDouble;
-(void)replaceFloatAtIndex:(unsigned)index withFloat:(float)aFloat;
-(void)replaceUInt64AtIndex:(unsigned)index withUInt64:(unsigned long long)uint64;
-(void)replaceInt64AtIndex:(unsigned)index withInt64:(long long)int64;
-(void)replaceUInt32AtIndex:(unsigned)index withUInt32:(unsigned)uint32;
-(void)replaceInt32AtIndex:(unsigned)index withInt32:(int)int32;
-(void)replaceBoolAtIndex:(unsigned)index withBool:(BOOL)aBool;
-(void)setObject:(id)object atIndexedSubscript:(unsigned)indexedSubscript;
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
-(void)addDouble:(double)aDouble;
-(void)addFloat:(float)aFloat;
-(void)addUInt64:(unsigned long long)a64;
-(void)addInt64:(long long)a64;
-(void)addUInt32:(unsigned)a32;
-(void)addInt32:(int)a32;
-(void)addBool:(BOOL)aBool;
-(void)addObject:(id)object;
-(void)ensureAdditionalCapacity:(unsigned)capacity;
-(void)enumerateInt32sUsingBlock:(id)block;
-(void)enumerateObjectsUsingBlock:(id)block;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithValueType:(int)valueType capacity:(unsigned)capacity;
-(void)dealloc;
@end

