/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class TAGPBFieldOptions, NSString;

__attribute__((visibility("hidden")))
@interface TAGPBFieldDescriptorProto : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBFieldOptions* options;
@property(assign, nonatomic) BOOL hasOptions;
@property(assign, nonatomic) int oneofIndex;
@property(assign, nonatomic) BOOL hasOneofIndex;
@property(retain, nonatomic) NSString* defaultValue;
@property(assign, nonatomic) BOOL hasDefaultValue;
@property(retain, nonatomic) NSString* extendee;
@property(assign, nonatomic) BOOL hasExtendee;
@property(retain, nonatomic) NSString* typeName;
@property(assign, nonatomic) BOOL hasTypeName;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) BOOL hasType;
@property(assign, nonatomic) int label;
@property(assign, nonatomic) BOOL hasLabel;
@property(assign, nonatomic) int number;
@property(assign, nonatomic) BOOL hasNumber;
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

