/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPBStreamOptions : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBMutableArray* uninterpretedOptionArray;
@property(assign, nonatomic) BOOL hasUninterpretedOptionArray;
@property(assign, nonatomic) BOOL deprecated;
@property(assign, nonatomic) BOOL hasDeprecated;
@property(assign, nonatomic) int logLevel;
@property(assign, nonatomic) BOOL hasLogLevel;
@property(assign, nonatomic) BOOL endUserCredsRequested;
@property(assign, nonatomic) BOOL hasEndUserCredsRequested;
@property(assign, nonatomic) BOOL failFast;
@property(assign, nonatomic) BOOL hasFailFast;
@property(assign, nonatomic) double deadline;
@property(assign, nonatomic) BOOL hasDeadline;
@property(assign, nonatomic) int serverLogging;
@property(assign, nonatomic) BOOL hasServerLogging;
@property(assign, nonatomic) int clientLogging;
@property(assign, nonatomic) BOOL hasClientLogging;
@property(retain, nonatomic) NSString* securityLabel;
@property(assign, nonatomic) BOOL hasSecurityLabel;
@property(assign, nonatomic) int securityLevel;
@property(assign, nonatomic) BOOL hasSecurityLevel;
@property(assign, nonatomic) int tokenUnit;
@property(assign, nonatomic) BOOL hasTokenUnit;
@property(assign, nonatomic) long long serverInitialTokens;
@property(assign, nonatomic) BOOL hasServerInitialTokens;
@property(assign, nonatomic) long long clientInitialTokens;
@property(assign, nonatomic) BOOL hasClientInitialTokens;
+(id)descriptor;
@end

