/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString, NSData, TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPBUninterpretedOption : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* aggregateValue;
@property(assign, nonatomic) BOOL hasAggregateValue;
@property(retain, nonatomic) NSData* stringValue;
@property(assign, nonatomic) BOOL hasStringValue;
@property(assign, nonatomic) double doubleValue;
@property(assign, nonatomic) BOOL hasDoubleValue;
@property(assign, nonatomic) long long negativeIntValue;
@property(assign, nonatomic) BOOL hasNegativeIntValue;
@property(assign, nonatomic) unsigned long long positiveIntValue;
@property(assign, nonatomic) BOOL hasPositiveIntValue;
@property(retain, nonatomic) NSString* identifierValue;
@property(assign, nonatomic) BOOL hasIdentifierValue;
@property(retain, nonatomic) TAGPBMutableArray* nameArray;
@property(assign, nonatomic) BOOL hasNameArray;
+(id)descriptor;
@end

