/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TAGPBUninterpretedOption_NamePart : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) BOOL isExtension;
@property(assign, nonatomic) BOOL hasIsExtension;
@property(retain, nonatomic) NSString* namePart;
@property(assign, nonatomic) BOOL hasNamePart;
+(id)descriptor;
@end

