/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TAGPBFieldOptions_UpgradedOption : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* value;
@property(assign, nonatomic) BOOL hasValue;
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

