/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class TAGPBEnumOptions, NSString, TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPBEnumDescriptorProto : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBEnumOptions* options;
@property(assign, nonatomic) BOOL hasOptions;
@property(retain, nonatomic) TAGPBMutableArray* valueArray;
@property(assign, nonatomic) BOOL hasValueArray;
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

