/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPGaServerSideExperimentWeightBucket : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBMutableArray* combinationWeightSumArray;
@property(assign, nonatomic) BOOL hasCombinationWeightSumArray;
+(id)descriptor;
@end

