/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"


__attribute__((visibility("hidden")))
@interface TAGPProperty : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) int value;
@property(assign, nonatomic) BOOL hasValue;
@property(assign, nonatomic) int key;
@property(assign, nonatomic) BOOL hasKey;
+(id)descriptor;
@end

