/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class TAGPSupplementedResource, TAGPResource;

__attribute__((visibility("hidden")))
@interface TAGPResourceWithMetadata : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPSupplementedResource* supplementedResource;
@property(assign, nonatomic) BOOL hasSupplementedResource;
@property(retain, nonatomic) TAGPResource* resource;
@property(assign, nonatomic) BOOL hasResource;
@property(assign, nonatomic) long long timeStamp;
@property(assign, nonatomic) BOOL hasTimeStamp;
+(id)descriptor;
@end

