/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>

@class NSMutableData;

__attribute__((visibility("hidden")))
@interface TAGPBCodedOutputStream : NSObject {
	TAGPBOutputBufferState state_;
	NSMutableData* buffer_;
}
+(id)streamWithData:(id)data;
+(id)streamWithOutputStream:(id)outputStream;
+(id)streamWithOutputStream:(id)outputStream bufferSize:(unsigned long)size;
-(void)writeRawLittleEndian64:(long long)a64;
-(void)writeRawLittleEndian32:(int)a32;
-(void)writeRawVarint64:(long long)a64;
-(void)writeRawVarintSizeTAs32:(unsigned long)a32;
-(void)writeRawVarint32:(int)a32;
-(void)writeTag:(unsigned)tag format:(int)format;
-(void)writeRawPtr:(const void*)ptr offset:(unsigned long)offset length:(unsigned long)length;
-(void)writeRawData:(id)data;
-(void)writeRawByte:(unsigned char)byte;
-(void)flush;
-(void)writeRawMessageSetExtension:(int)extension value:(id)value;
-(void)writeMessageSetExtension:(int)extension value:(id)value;
-(void)writeUnknownGroups:(int)groups values:(id)values;
-(void)writeGroups:(int)groups values:(id)values;
-(void)writeDatas:(int)datas values:(id)values;
-(void)writeMessages:(int)messages values:(id)values;
-(void)writeStrings:(int)strings values:(id)values;
-(void)writeEnums:(int)enums values:(id)values tag:(unsigned)tag;
-(void)writeBools:(int)bools values:(id)values tag:(unsigned)tag;
-(void)writeSFixed32s:(int)a32s values:(id)values tag:(unsigned)tag;
-(void)writeSFixed64s:(int)a64s values:(id)values tag:(unsigned)tag;
-(void)writeSInt64s:(int)a64s values:(id)values tag:(unsigned)tag;
-(void)writeSInt32s:(int)a32s values:(id)values tag:(unsigned)tag;
-(void)writeFixed32s:(int)a32s values:(id)values tag:(unsigned)tag;
-(void)writeFixed64s:(int)a64s values:(id)values tag:(unsigned)tag;
-(void)writeUInt32s:(int)a32s values:(id)values tag:(unsigned)tag;
-(void)writeInt32s:(int)a32s values:(id)values tag:(unsigned)tag;
-(void)writeInt64s:(int)a64s values:(id)values tag:(unsigned)tag;
-(void)writeUInt64s:(int)a64s values:(id)values tag:(unsigned)tag;
-(void)writeFloats:(int)floats values:(id)values tag:(unsigned)tag;
-(void)writeDoubles:(int)doubles values:(id)values tag:(unsigned)tag;
-(void)writeSInt64:(int)a64 value:(long long)value;
-(void)writeSInt64NoTag:(long long)tag;
-(void)writeSInt32:(int)a32 value:(int)value;
-(void)writeSInt32NoTag:(int)tag;
-(void)writeSFixed64:(int)a64 value:(long long)value;
-(void)writeSFixed64NoTag:(long long)tag;
-(void)writeSFixed32:(int)a32 value:(int)value;
-(void)writeSFixed32NoTag:(int)tag;
-(void)writeEnum:(int)anEnum value:(int)value;
-(void)writeEnumNoTag:(int)tag;
-(void)writeUInt32:(int)a32 value:(unsigned)value;
-(void)writeUInt32NoTag:(unsigned)tag;
-(void)writeData:(int)data value:(id)value;
-(void)writeDataNoTag:(id)tag;
-(void)writeMessage:(int)message value:(id)value;
-(void)writeMessageNoTag:(id)tag;
-(void)writeUnknownGroup:(int)group value:(id)value;
-(void)writeUnknownGroupNoTag:(int)tag value:(id)value;
-(void)writeGroup:(int)group value:(id)value;
-(void)writeGroupNoTag:(int)tag value:(id)value;
-(void)writeString:(int)string value:(id)value;
-(void)writeStringNoTag:(id)tag;
-(void)writeBool:(int)aBool value:(BOOL)value;
-(void)writeBoolNoTag:(BOOL)tag;
-(void)writeFixed32:(int)a32 value:(unsigned)value;
-(void)writeFixed32NoTag:(unsigned)tag;
-(void)writeFixed64:(int)a64 value:(unsigned long long)value;
-(void)writeFixed64NoTag:(unsigned long long)tag;
-(void)writeInt32:(int)a32 value:(int)value;
-(void)writeInt32NoTag:(int)tag;
-(void)writeInt64:(int)a64 value:(long long)value;
-(void)writeInt64NoTag:(long long)tag;
-(void)writeUInt64:(int)a64 value:(unsigned long long)value;
-(void)writeUInt64NoTag:(unsigned long long)tag;
-(void)writeFloat:(int)aFloat value:(float)value;
-(void)writeFloatNoTag:(float)tag;
-(void)writeDouble:(int)aDouble value:(double)value;
-(void)writeDoubleNoTag:(double)tag;
-(id)initWithOutputStream:(id)outputStream data:(id)data;
-(id)initWithOutputStream:(id)outputStream bufferSize:(unsigned long)size;
-(id)initWithData:(id)data;
-(id)initWithOutputStream:(id)outputStream;
-(void)dealloc;
@end

