/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPFunctionCall : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) BOOL serverSide;
@property(assign, nonatomic) BOOL hasServerSide;
@property(assign, nonatomic) BOOL liveOnly;
@property(assign, nonatomic) BOOL hasLiveOnly;
@property(assign, nonatomic) int name;
@property(assign, nonatomic) BOOL hasName;
@property(assign, nonatomic) int function;
@property(assign, nonatomic) BOOL hasFunction;
@property(retain, nonatomic) TAGPBMutableArray* propertyArray;
@property(assign, nonatomic) BOOL hasPropertyArray;
+(id)descriptor;
@end

