/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPBMethodOptions : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBMutableArray* uninterpretedOptionArray;
@property(assign, nonatomic) BOOL hasUninterpretedOptionArray;
@property(assign, nonatomic) BOOL deprecated;
@property(assign, nonatomic) BOOL hasDeprecated;
@property(assign, nonatomic) int logLevel;
@property(assign, nonatomic) BOOL hasLogLevel;
@property(assign, nonatomic) long long legacyServerInitialTokens;
@property(assign, nonatomic) BOOL hasLegacyServerInitialTokens;
@property(assign, nonatomic) long long legacyClientInitialTokens;
@property(assign, nonatomic) BOOL hasLegacyClientInitialTokens;
@property(retain, nonatomic) NSString* legacyResultType;
@property(assign, nonatomic) BOOL hasLegacyResultType;
@property(retain, nonatomic) NSString* legacyStreamType;
@property(assign, nonatomic) BOOL hasLegacyStreamType;
@property(assign, nonatomic) BOOL serverStreaming;
@property(assign, nonatomic) BOOL hasServerStreaming;
@property(assign, nonatomic) BOOL clientStreaming;
@property(assign, nonatomic) BOOL hasClientStreaming;
@property(retain, nonatomic) NSString* securityLabel;
@property(assign, nonatomic) BOOL hasSecurityLabel;
@property(retain, nonatomic) NSString* streamType;
@property(assign, nonatomic) BOOL hasStreamType;
@property(assign, nonatomic) int requestFormat;
@property(assign, nonatomic) BOOL hasRequestFormat;
@property(assign, nonatomic) int responseFormat;
@property(assign, nonatomic) BOOL hasResponseFormat;
@property(assign, nonatomic) int securityLevel;
@property(assign, nonatomic) BOOL hasSecurityLevel;
@property(assign, nonatomic) int serverLogging;
@property(assign, nonatomic) BOOL hasServerLogging;
@property(assign, nonatomic) int clientLogging;
@property(assign, nonatomic) BOOL hasClientLogging;
@property(assign, nonatomic) BOOL endUserCredsRequested;
@property(assign, nonatomic) BOOL hasEndUserCredsRequested;
@property(assign, nonatomic) BOOL failFast;
@property(assign, nonatomic) BOOL hasFailFast;
@property(assign, nonatomic) BOOL duplicateSuppression;
@property(assign, nonatomic) BOOL hasDuplicateSuppression;
@property(assign, nonatomic) double deadline;
@property(assign, nonatomic) BOOL hasDeadline;
@property(assign, nonatomic) int protocol;
@property(assign, nonatomic) BOOL hasProtocol;
+(id)descriptor;
@end

