/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBMutableArrayDelegate.h"
#import "NSCopying.h"
#import "NSCoding.h"
#import "NSMutableCopying.h"
#import "wotblitz-Structs.h"
#import "TAGPBRootObject.h"

@class NSMutableDictionary, TAGPBFieldDescriptor, TAGPBExtensionField, NSString, TAGPBUnknownFieldSet;

__attribute__((visibility("hidden")))
@interface TAGPBGeneratedMessage : TAGPBRootObject <TAGPBMutableArrayDelegate, NSCoding, NSCopying, NSMutableCopying> {
	TAGPBUnknownFieldSet* unknownFields_;
	NSMutableDictionary* extensionMap_;
	NSMutableDictionary* autocreatedExtensionMap_;
	TAGPBGeneratedMessage* autocreator_;
	TAGPBFieldDescriptor* autocreatorField_;
	TAGPBExtensionField* autocreatorExtension_;
	TAGPBGeneratedMessage_StorageRef messageStorage_;
	int readOnlyMutex_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic, getter=isInitialized) BOOL initialized;
@property(retain, nonatomic) TAGPBUnknownFieldSet* unknownFields;
+(id)builder;
+(BOOL)accessInstanceVariablesDirectly;
+(BOOL)resolveInstanceMethod:(SEL)method;
+(id)parseDelimitedFromCodedInputStream:(id)codedInputStream extensionRegistry:(id)registry;
+(id)parseFromCodedInputStream:(id)codedInputStream extensionRegistry:(id)registry;
+(id)parseFromData:(id)data extensionRegistry:(id)registry;
+(id)parseFromData:(id)data;
+(id)newMessageWithAutocreator:(id)autocreator extension:(id)extension;
+(id)newMessageWithAutocreator:(id)autocreator field:(id)field;
+(id)message;
+(id)descriptor;
+(id)alloc;
+(id)allocWithZone:(NSZone*)zone;
+(void)initialize;
-(id)build;
-(id)builder;
-(void)pbMutableArray:(id)array willAddElements:(unsigned)elements;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(unsigned long)serializedSize;
-(BOOL)isEqual:(id)equal;
-(void)mergeFrom:(id)from;
-(void)mergeFromCodedInputStream:(id)codedInputStream extensionRegistry:(id)registry;
-(BOOL)parseUnknownField:(id)field extensionRegistry:(id)registry tag:(unsigned)tag;
-(void)parseMessageSet:(id)set extensionRegistry:(id)registry;
-(void)mergeUnknownFields:(id)fields;
-(id)mutableUnknownFields;
-(void)mergeDelimitedFromCodedInputStream:(id)codedInputStream extensionRegistry:(id)registry;
-(void)mergeFromData:(id)data extensionRegistry:(id)registry;
-(BOOL)wasAutocreatedBy:(id)by;
-(void)clearAutocreator;
-(void)clearExtension:(id)extension;
-(void)setExtension:(id)extension index:(unsigned)index value:(id)value;
-(void)addExtension:(id)extension value:(id)value;
-(void)setExtension:(id)extension value:(id)value;
-(unsigned long)extensionsSerializedSize;
-(id)sortedExtensionsInUse;
-(void)writeExtensionsToCodedOutputStream:(id)codedOutputStream range:(id)range;
-(id)extensionsCurrentlySet;
-(BOOL)hasExtension:(id)extension;
-(id)getExistingExtension:(id)extension;
-(id)getExtension:(id)extension;
-(BOOL)isInitialized:(id)initialized;
-(void)writeField:(id)field toCodedOutputStream:(id)codedOutputStream;
-(void)writeDelimitedToCodedOutputStream:(id)codedOutputStream;
-(void)writeDelimitedToOutputStream:(id)outputStream;
-(void)writeToCodedOutputStream:(id)codedOutputStream;
-(void)writeToOutputStream:(id)outputStream;
-(id)delimitedData;
-(id)data;
-(id)descriptor;
-(void)internalClear;
-(void)clear;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)copyWithZone:(NSZone*)zone;
-(void)copyFieldsInto:(id)into zone:(NSZone*)zone;
-(void)dealloc;
-(id)init;
@end

