/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPBMutableArray, TAGPBMessageOptions;

__attribute__((visibility("hidden")))
@interface TAGPBDescriptorProto : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBMessageOptions* options;
@property(assign, nonatomic) BOOL hasOptions;
@property(retain, nonatomic) TAGPBMutableArray* oneofDeclArray;
@property(assign, nonatomic) BOOL hasOneofDeclArray;
@property(retain, nonatomic) TAGPBMutableArray* extensionRangeArray;
@property(assign, nonatomic) BOOL hasExtensionRangeArray;
@property(retain, nonatomic) TAGPBMutableArray* enumTypeArray;
@property(assign, nonatomic) BOOL hasEnumTypeArray;
@property(retain, nonatomic) TAGPBMutableArray* nestedTypeArray;
@property(assign, nonatomic) BOOL hasNestedTypeArray;
@property(retain, nonatomic) TAGPBMutableArray* extensionArray;
@property(assign, nonatomic) BOOL hasExtensionArray;
@property(retain, nonatomic) TAGPBMutableArray* fieldArray;
@property(assign, nonatomic) BOOL hasFieldArray;
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

