/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>

@class NSString, TAGPBEnumDescriptor, TAGPBFieldOptions;

__attribute__((visibility("hidden")))
@interface TAGPBFieldDescriptor : NSObject {
	TAGPBMessageFieldDescription* description_;
	SEL getSel_;
	SEL setSel_;
	SEL hasSel_;
	SEL setHasSel_;
	XXUnion_EJvwPD defaultValue_;
	TAGPBFieldOptions* fieldOptions_;
	Class msgClass_;
	union {
		TAGPBEnumDescriptor* enumDescriptor_;
		/*function-pointer*/ void* enumVerifier_;
	} enumHandling_;
}
@property(readonly, retain, nonatomic) TAGPBEnumDescriptor* enumDescriptor;
@property(readonly, assign, nonatomic) Class msgClass;
@property(readonly, assign, nonatomic) unsigned hasIndex;
@property(readonly, assign, nonatomic) SEL setHasSel;
@property(readonly, assign, nonatomic) SEL hasSel;
@property(readonly, assign, nonatomic) TAGPBFieldOptions* fieldOptions;
@property(readonly, assign, nonatomic) SEL setSel;
@property(readonly, assign, nonatomic) unsigned tag;
@property(readonly, assign, nonatomic) unsigned long offset;
@property(readonly, assign, nonatomic) SEL getSel;
@property(readonly, assign, nonatomic, getter=isMessage) BOOL message;
@property(readonly, assign, nonatomic, getter=isPackable) BOOL packable;
@property(readonly, assign, nonatomic, getter=isRepeated) BOOL repeated;
@property(readonly, assign, nonatomic, getter=isOptional) BOOL optional;
@property(readonly, assign, nonatomic, getter=isRequired) BOOL required;
@property(readonly, assign, nonatomic) XXUnion_oE8oiC defaultValue;
@property(readonly, assign, nonatomic) BOOL hasDefaultValue;
@property(readonly, assign, nonatomic) int type;
@property(readonly, assign, nonatomic) unsigned number;
@property(readonly, retain, nonatomic) NSString* name;
-(id)textFormatName;
-(BOOL)isValidEnumValue:(int)value;
-(void)dealloc;
-(id)initWithFieldDescription:(TAGPBMessageFieldDescription*)fieldDescription rootClass:(Class)aClass;
-(id)init;
@end

