/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"


__attribute__((visibility("hidden")))
@interface TAGPCacheOption : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) int gcacheExpirationSeconds;
@property(assign, nonatomic) BOOL hasGcacheExpirationSeconds;
@property(assign, nonatomic) int expirationSeconds;
@property(assign, nonatomic) BOOL hasExpirationSeconds;
@property(assign, nonatomic) int level;
@property(assign, nonatomic) BOOL hasLevel;
+(id)descriptor;
@end

