/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPBStreamOptions;

__attribute__((visibility("hidden")))
@interface TAGPBStreamDescriptorProto : TAGPBGeneratedMessage {
}
@property(retain, nonatomic) TAGPBStreamOptions* options;
@property(assign, nonatomic) BOOL hasOptions;
@property(retain, nonatomic) NSString* serverMessageType;
@property(assign, nonatomic) BOOL hasServerMessageType;
@property(retain, nonatomic) NSString* clientMessageType;
@property(assign, nonatomic) BOOL hasClientMessageType;
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

