/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TAGPBObjectiveCFileOptions : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) BOOL camelcaseOutputFilename;
@property(assign, nonatomic) BOOL hasCamelcaseOutputFilename;
@property(retain, nonatomic) NSString* classPrefix;
@property(assign, nonatomic) BOOL hasClassPrefix;
@property(retain, nonatomic) NSString* package;
@property(assign, nonatomic) BOOL hasPackage;
+(id)descriptor;
@end

