/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPBMutableArray;

__attribute__((visibility("hidden")))
@interface TAGPValue : TAGPBGeneratedMessage {
}
@property(assign, nonatomic) BOOL containsReferences;
@property(assign, nonatomic) BOOL hasContainsReferences;
@property(retain, nonatomic) TAGPBMutableArray* escapingArray;
@property(assign, nonatomic) BOOL hasEscapingArray;
@property(retain, nonatomic) NSString* tagReference;
@property(assign, nonatomic) BOOL hasTagReference;
@property(retain, nonatomic) TAGPBMutableArray* templateTokenArray;
@property(assign, nonatomic) BOOL hasTemplateTokenArray;
@property(assign, nonatomic) BOOL boolean;
@property(assign, nonatomic) BOOL hasBoolean;
@property(assign, nonatomic) long long integer;
@property(assign, nonatomic) BOOL hasInteger;
@property(retain, nonatomic) NSString* functionId;
@property(assign, nonatomic) BOOL hasFunctionId;
@property(retain, nonatomic) NSString* macroReference;
@property(assign, nonatomic) BOOL hasMacroReference;
@property(retain, nonatomic) TAGPBMutableArray* mapValueArray;
@property(assign, nonatomic) BOOL hasMapValueArray;
@property(retain, nonatomic) TAGPBMutableArray* mapKeyArray;
@property(assign, nonatomic) BOOL hasMapKeyArray;
@property(retain, nonatomic) TAGPBMutableArray* listItemArray;
@property(assign, nonatomic) BOOL hasListItemArray;
@property(retain, nonatomic) NSString* string;
@property(assign, nonatomic) BOOL hasString;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) BOOL hasType;
+(id)descriptor;
-(unsigned)hash;
@end

