/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TAGFunctionCallImplementation.h"


__attribute__((visibility("hidden")))
@interface TAGRegexGroup : TAGFunctionCallImplementation {
}
+(id)groupKey;
+(id)ignoreCaseKey;
+(id)regexKey;
+(id)toMatchKey;
+(id)functionId;
-(id)evaluate:(id)evaluate;
-(BOOL)isCacheable;
-(id)init;
@end

