/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface TAGSerialization : NSObject {
}
+(id)deserializedObjectToNSObject:(id)nsobject;
+(id)expandedResourceFromDeserializedObject:(id)deserializedObject;
+(id)deserializedObjectToValue:(id)value;
+(id)expandResourceFromData:(id)data;
+(void)initialize;
@end

