/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface TAGValueEscapeUtil : NSObject {
}
+(BOOL)isValidStringType:(id)type;
+(id)escapeUri:(id)uri;
+(id)urlDecode:(id)decode;
+(id)urlEncode:(id)encode;
+(id)applyEscaping:(int)escaping toValue:(id)value;
+(id)applyEscapings:(id)escapings toValue:(id)value;
@end

