/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSNumber, NSDate;

@interface TuneLocation : NSObject {
	NSNumber* _altitude;
	NSNumber* _latitude;
	NSNumber* _longitude;
	NSNumber* _horizontalAccuracy;
	NSDate* _timestamp;
	NSNumber* _verticalAccuracy;
}
@property(copy, nonatomic) NSNumber* verticalAccuracy;
@property(copy, nonatomic) NSDate* timestamp;
@property(copy, nonatomic) NSNumber* horizontalAccuracy;
@property(copy, nonatomic) NSNumber* longitude;
@property(copy, nonatomic) NSNumber* latitude;
@property(copy, nonatomic) NSNumber* altitude;
-(void).cxx_destruct;
@end

