//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TuneDateUtils : NSObject
{
}

+ (int)daysBetween:(id)arg1 and:(id)arg2;
+ (_Bool)date:(id)arg1 isBetweenDate:(id)arg2 andEndDate:(id)arg3;
+ (id)dateFormatterIso8601UTC;
+ (id)dateFormatterIso8601;

@end

