//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TuneBaseSlideInMessageView.h"

@interface TuneiOS8SlideInMessageView : TuneBaseSlideInMessageView
{
}

- (id)buildViewForOrientation:(int)arg1;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)dismissOrientation:(long long)arg1;
- (void)showOrientation:(long long)arg1;
- (int)getTransitionByOrientation:(long long)arg1;
- (int)getCurrentTuneOrientationForUIDeviceOrientation:(long long)arg1;
- (void)buildMessageContainerForOrientation:(long long)arg1;
- (void)addBackgroundColorForDeviceOrientation:(long long)arg1;
- (void)layoutBackgroundImageForDeviceOrientation:(long long)arg1;
- (id)buildBackgroundImageViewFromImage:(id)arg1 andContainerSize:(struct CGSize)arg2;
- (void)addMessageClickOverlayActionForDeviceOrientation:(long long)arg1;
- (void)layoutCloseButtonForDeviceOrientation:(long long)arg1;
- (void)layoutCTAForDeviceOrientation:(long long)arg1;
- (void)layoutMessageForDeviceOrientation:(long long)arg1;

@end

