/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface TuneAdParams : NSObject {
}
+(id)identifierInfo:(id)info;
+(id)orientationInfo:(id)info metadata:(id)metadata orientations:(unsigned)orientations adType:(int)type;
+(id)userInfo:(id)info metadata:(id)metadata;
+(id)screenInfo:(id)info;
+(id)appInfo:(id)info;
+(id)deviceInfo:(id)info metadata:(id)metadata;
+(id)jsonForAdType:(int)adType placement:(id)placement metadata:(id)metadata orientations:(unsigned)orientations ad:(id)ad;
+(id)jsonForAdType:(int)adType placement:(id)placement metadata:(id)metadata orientations:(unsigned)orientations;
@end

