//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"

@class NSString;

@interface TuneUserAgentCollector : NSObject <UIWebViewDelegate>
{
    _Bool _hasStarted;
    id _webView;
    NSString *_userAgent;
}

+ (id)userAgent;
+ (void)startCollection;
+ (void)initialize;
@property(copy, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(retain, nonatomic) id webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool hasStarted; // @synthesize hasStarted=_hasStarted;
- (void).cxx_destruct;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

