//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TuneManager;

@interface TuneModule : NSObject
{
    TuneManager *_tuneManager;
}

+ (id)moduleWithTuneManager:(id)arg1;
@property(nonatomic) __weak TuneManager *tuneManager; // @synthesize tuneManager=_tuneManager;
- (void).cxx_destruct;
- (id)name;
- (void)unregisterSkyhooks;
- (void)registerSkyhooks;
- (void)bringDown;
- (void)bringUp;
- (void)dealloc;
- (id)initWithTuneManager:(id)arg1;

@end

