/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface TuneEncrypter : NSObject {
}
+(id)hexEncode:(id)encode;
+(id)aesEncryptData:(id)data withKey:(id)key;
+(id)encryptString:(id)string withKey:(id)key;
@end

