/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import </libobjc.A.h>


@interface TuneUtils : NSObject {
}
+(CGRect)screenBoundsForStatusBarOrientation;
+(CGSize)screenSize;
+(id)urlEncodeQueryParamValue:(id)value;
+(void)addUrlQueryParamValue:(id)value forKey:(id)key queryParams:(id)params;
+(id)hashSha256:(id)a256;
+(id)hashSha1:(id)a1;
+(id)hashMd5:(id)a5;
+(id)tuneBase64EncodedStringFromData:(id)data;
+(id)tuneDataFromBase64String:(id)base64String;
+(id)jsonSerialize:(id)serialize;
+(BOOL)addSkipBackupAttributeToItemAtURL:(id)url;
+(float)numericiOSSystemVersion;
+(float)numericiOSVersion:(id)version;
+(BOOL)isNetworkReachable;
+(int)networkReachabilityStatus;
+(id)installDate;
+(id)bundleId;
+(BOOL)checkJailBreak;
+(void)synchronizeUserDefaults;
+(void)setUserDefaultValue:(id)value forKey:(id)key;
+(id)userDefaultValueforKey:(id)key;
+(id)getStringForKey:(id)key fromPasteBoard:(id)pasteBoard;
+(id)parseXmlString:(id)string forTag:(id)tag;
+(id)getUUID;
+(id)generateFBCookieIdString;
+(int)daysBetweenDate:(id)date andDate:(id)date2;
+(void)initialize;
@end

