//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TuneLabelUtils : NSObject
{
}

+ (void)adjustFrameHeightToTextHeightOnLabel:(id)arg1;
+ (struct CGSize)actualTextSizeConstrainedByWidth:(double)arg1 andHeight:(double)arg2 onLabel:(id)arg3;
+ (struct CGSize)actualTextSizeOnLabel:(id)arg1;

@end

