//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface TuneAppToAppTracker : NSObject
{
    NSOperationQueue *sendQueue;
    CDUnknownBlockType completionHandler;
    id <TuneEventQueueDelegate> _delegate;
}

+ (id)getTrackingId;
+ (id)getCampaignId;
+ (id)getAdvertiserId;
+ (id)getSessionDateTime;
+ (id)getPublisherBundleId;
@property(nonatomic) __weak id <TuneEventQueueDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)storeToPasteBoardTrackingId:(id)arg1;
- (void)failedToRequestTrackingId:(id)arg1 withError:(id)arg2;
- (void)startMeasurementSessionForTargetBundleId:(id)arg1 publisherBundleId:(id)arg2 advertiserId:(id)arg3 campaignId:(id)arg4 publisherId:(id)arg5 redirect:(_Bool)arg6 domainName:(id)arg7;
- (id)init;

@end

