//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TuneArrayUtils : NSObject
{
}

+ (_Bool)array:(id)arg1 containsString:(id)arg2;
+ (_Bool)areAllElementsOfArray:(id)arg1 ofType:(Class)arg2;

@end

