//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TuneXmlUtils : NSObject
{
}

+ (id)Tunegtm_stringBySanitizingToXMLSpec:(id)arg1;
+ (id)Tunegtm_stringBySanitizingAndEscapingForXML:(id)arg1;

@end

