//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate, NSNumber;

@interface TuneLocation : NSObject <NSCoding>
{
    NSNumber *_altitude;
    NSNumber *_latitude;
    NSNumber *_longitude;
    NSNumber *_horizontalAccuracy;
    NSDate *_timestamp;
    NSNumber *_verticalAccuracy;
}

@property(copy, nonatomic) NSNumber *verticalAccuracy; // @synthesize verticalAccuracy=_verticalAccuracy;
@property(copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSNumber *horizontalAccuracy; // @synthesize horizontalAccuracy=_horizontalAccuracy;
@property(copy, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(copy, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSNumber *altitude; // @synthesize altitude=_altitude;
- (void).cxx_destruct;
- (id)debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

