//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TuneExperimentDetails.h"

@class NSDate, NSString;

@interface TunePowerHookExperimentDetails : TuneExperimentDetails
{
    NSString *_hookId;
    NSDate *_experimentStartDate;
    NSDate *_experimentEndDate;
}

@property(readonly, nonatomic) NSDate *experimentEndDate; // @synthesize experimentEndDate=_experimentEndDate;
@property(readonly, nonatomic) NSDate *experimentStartDate; // @synthesize experimentStartDate=_experimentStartDate;
@property(readonly, nonatomic) NSString *hookId; // @synthesize hookId=_hookId;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)description;
@property(readonly, nonatomic, getter=isRunning) _Bool running;
- (id)initWithDetailsDictionary:(id)arg1 andPowerHookValue:(id)arg2 andHookId:(id)arg3;

@end

