//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface TuneJSONPlayer : NSObject
{
    long long counter;
    NSArray *_files;
}

@property(copy, nonatomic) NSArray *files; // @synthesize files=_files;
- (void).cxx_destruct;
- (id)getDictionaryFromJSONFile:(id)arg1;
- (id)buildArrayWithFilenames:(id)arg1;
- (id)getNext;
- (void)incrementDownload;
- (id)init;

@end

