//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TuneFileManager : NSObject
{
}

+ (id)getImageStorageDirectory;
+ (id)getStorageDirectory;
+ (id)getImageFilePathForImageNamed:(id)arg1;
+ (id)getLocalConfigurationPath;
+ (id)getPlaylistFilePath;
+ (id)getRemoteConfigurationFilePath;
+ (id)getPathToAnalytics;
+ (_Bool)deleteDictionaryAtPath:(id)arg1 withFileLock:(id)arg2;
+ (_Bool)saveDictionary:(id)arg1 toPath:(id)arg2 withFileLock:(id)arg3;
+ (id)loadDictionaryAtPath:(id)arg1 withFileLock:(id)arg2;
+ (_Bool)saveImageData:(id)arg1 toDiskWithName:(id)arg2;
+ (id)loadImageFromDiskNamed:(id)arg1;
+ (_Bool)deletePlaylistFromDisk;
+ (_Bool)savePlaylistToDisk:(id)arg1;
+ (id)loadPlaylistFromDisk;
+ (id)loadLocalConfigurationFromDisk;
+ (_Bool)deleteRemoteConfigurationFromDisk;
+ (_Bool)saveRemoteConfigurationToDisk:(id)arg1;
+ (id)loadRemoteConfigurationFromDisk;
+ (_Bool)deleteAnalyticsFromDisk;
+ (_Bool)deleteAnalyticsEventsFromDisk:(id)arg1;
+ (_Bool)saveAnalyticsToDisk:(id)arg1;
+ (_Bool)saveAnalyticsEventToDisk:(id)arg1 withId:(id)arg2;
+ (id)loadAnalyticsFromDisk;
+ (void)initialize;

@end

