/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "wotblitz-Structs.h"
#import <UIKit/UIView.h>
#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"

@class NSMutableDictionary, NSError, TuneAdPlacementManager, TuneAdSKStoreProductViewController, UIViewController, UIWebView, NSString, TuneAd, UIActivityIndicatorView;
@protocol TuneAdDelegate;

@interface TuneAdView : UIView <UIWebViewDelegate, UIScrollViewDelegate, SKStoreProductViewControllerDelegate> {
	int adType;
	NSMutableDictionary* placementAds;
	UIWebView* webview1;
	UIWebView* webview2;
	TuneAd* adCurrent;
	TuneAd* adNext;
	BOOL adReadyForDisplay;
	BOOL appStoreVisible;
	NSError* adError;
	UIViewController* parentViewController;
	TuneAdSKStoreProductViewController* storeVC;
	UIActivityIndicatorView* activity;
	int viewIndex;
	TuneAdPlacementManager* pm;
	BOOL waitingForAd;
	BOOL _ready;
	id<TuneAdDelegate> _delegate;
	unsigned _adOrientations;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isReady) BOOL ready;
@property(assign, nonatomic, setter=setAllowedOrientations:) unsigned adOrientations;
@property(assign, nonatomic) id<TuneAdDelegate> delegate;
+(unsigned)defaultAdOrientation;
-(void).cxx_destruct;
-(void)notifyAdRequestWithUrl:(id)url data:(id)data;
-(void)notifyFailedWithError:(id)error;
-(void)notifyClose;
-(void)notifyClickActionEnd;
-(void)notifyClickActionStart:(BOOL)start;
-(void)notifyDidFetchAd:(id)notify;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(void)handleAppWillResignActive:(id)handleApp;
-(void)handleAppBecameActive:(id)active;
-(void)handleNetworkChange:(id)change;
-(void)statusBarOrientationWillChange:(id)statusBarOrientation;
-(void)dismissActivityOverlay;
-(void)handleStoreViewClosing;
-(void)showInAppStoreForAppId:(id)appId campaignToken:(id)token affiliateToken:(id)token3 requestUrl:(id)url;
-(BOOL)handleAdClickWithUrl:(id)url;
-(void)updateWebViewFrameForOrientation:(int)orientation;
-(id)viewForZoomingInScrollView:(id)scrollView;
-(void)preloadAd:(id)ad;
-(void)clearWebview:(id)webview;
-(void)toggleWebviews;
-(void)getNextAd:(id)ad metadata:(id)metadata;
-(void)internalInitForAdType:(int)adType;
-(id)initForAdType:(int)adType delegate:(id)delegate orientations:(unsigned)orientations;
@end

