//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface TuneCallbackBlock : NSObject
{
    NSTimer *timer;
    double delay;
    NSObject *lock;
    _Bool fireOnce;
    _Bool blockFired;
    _Bool canceled;
    CDUnknownBlockType block;
}

- (void).cxx_destruct;
- (_Bool)isCanceled;
- (void)stopTimer;
- (void)startTimer:(double)arg1;
- (void)executeBlock;
- (double)getDelay;
- (id)initWithCallbackBlock:(CDUnknownBlockType)arg1 fireOnce:(_Bool)arg2;

@end

