//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TuneBaseInAppMessageView.h"

@class TuneMessageAction, TuneMessageButton, TuneMessageLabel, UIButton, UIColor, UIImageView, UILabel, UIView;

@interface TunePopUpMessageView : TuneBaseInAppMessageView
{
    int _tunePopUpMessageEdgeStyle;
    int _transitionType;
    UIButton *_backgroundMaskButton;
    UIView *_backgroundMaskView;
    int _backgroundMaskType;
    _Bool _showDropShadow;
    UIColor *_messageBackgroundColor;
    UIImageView *_messageBackgroundImageView;
    UIView *_messageContainer;
    UIView *_backgroundView;
    UIView *_buttonContainerView;
    int _horizontalPadding;
    int _verticalPadding;
    TuneMessageLabel *_headlineLabelModel;
    UILabel *_headlineLabel;
    TuneMessageLabel *_bodyLabelModel;
    UILabel *_bodyLabel;
    TuneMessageAction *_contentAreaAction;
    UIButton *_contentAreaButton;
    UIImageView *_messageImageView;
    int _buttonCount;
    UIColor *_buttonTopSeparatorColor;
    UIColor *_buttonMiddleSeparatorColor;
    TuneMessageButton *_ctaButtonModel;
    TuneMessageButton *_cancelButtonModel;
    _Bool _showCloseButton;
    int _closeButtonColor;
    UIImageView *_closeButtonImageView;
    UIButton *_closeButtonOverlay;
}

- (void).cxx_destruct;
- (void)removePopUpMessageFromWindow;
- (void)dismiss;
- (void)handleCancelButtonPressed;
- (void)handleCTAButtonPressed;
- (void)handleContentAreaButtonPressed;
- (void)handleCloseButtonPressed;
- (void)show;
- (void)setCloseButtonColor:(int)arg1;
- (void)showCloseButton;
- (void)setButtonMiddleSeparatorColor:(id)arg1;
- (void)setButtonTopSeparatorColor:(id)arg1;
- (void)setCancelbutton:(id)arg1;
- (void)setCTAButton:(id)arg1;
- (void)setMessageBackgroundColor:(id)arg1;
- (id)getBackgroundImageView;
- (void)setBackgroundImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setContentAreaAction:(id)arg1;
- (void)setBodyLabel:(id)arg1;
- (void)setHeadlineLabel:(id)arg1;
- (void)resizeView;
- (void)applyBackgroundMaskColor;
- (void)showDropShadow;
- (void)setBackgroundMaskType:(int)arg1;
- (void)setVerticalPadding:(double)arg1;
- (void)setHorizontalPadding:(double)arg1;
- (void)addCloseButtonOverlayToContainer;
- (void)layoutPopUpView;
- (void)setTransitionType:(int)arg1;
- (void)adjustBackgroundMaskSizeToFitFrame;
- (void)initBackgroundMask;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithPopUpMessageEdgeStyle:(int)arg1;

@end

