/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface TunePreloadData : NSObject {
	NSString* _publisherId;
	NSString* _offerId;
	NSString* _agencyId;
	NSString* _publisherReferenceId;
	NSString* _publisherSub1;
	NSString* _publisherSub2;
	NSString* _publisherSub3;
	NSString* _publisherSub4;
	NSString* _publisherSub5;
	NSString* _publisherSubAd;
	NSString* _publisherSubAdgroup;
	NSString* _publisherSubCampaign;
	NSString* _publisherSubKeyword;
	NSString* _publisherSubPublisher;
	NSString* _publisherSubSite;
	NSString* _advertiserSubAd;
	NSString* _advertiserSubAdgroup;
	NSString* _advertiserSubCampaign;
	NSString* _advertiserSubKeyword;
	NSString* _advertiserSubPublisher;
	NSString* _advertiserSubSite;
}
@property(copy, nonatomic) NSString* advertiserSubSite;
@property(copy, nonatomic) NSString* advertiserSubPublisher;
@property(copy, nonatomic) NSString* advertiserSubKeyword;
@property(copy, nonatomic) NSString* advertiserSubCampaign;
@property(copy, nonatomic) NSString* advertiserSubAdgroup;
@property(copy, nonatomic) NSString* advertiserSubAd;
@property(copy, nonatomic) NSString* publisherSubSite;
@property(copy, nonatomic) NSString* publisherSubPublisher;
@property(copy, nonatomic) NSString* publisherSubKeyword;
@property(copy, nonatomic) NSString* publisherSubCampaign;
@property(copy, nonatomic) NSString* publisherSubAdgroup;
@property(copy, nonatomic) NSString* publisherSubAd;
@property(copy, nonatomic) NSString* publisherSub5;
@property(copy, nonatomic) NSString* publisherSub4;
@property(copy, nonatomic) NSString* publisherSub3;
@property(copy, nonatomic) NSString* publisherSub2;
@property(copy, nonatomic) NSString* publisherSub1;
@property(copy, nonatomic) NSString* publisherReferenceId;
@property(copy, nonatomic) NSString* agencyId;
@property(copy, nonatomic) NSString* offerId;
@property(copy, nonatomic) NSString* publisherId;
+(id)preloadDataWithPublisherId:(id)publisherId;
-(void).cxx_destruct;
-(id)initWithPublisherId:(id)publisherId;
@end

