//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, TuneAnalyticsManager, TuneCampaignStateManager, TuneConfiguration, TuneConnectedModeManager, TuneDeepActionManager, TuneExperimentManager, TuneJSONPlayer, TunePlaylistManager, TunePowerHookManager, TuneSessionManager, TuneState, TuneTriggerManager, TuneUserProfile;

@interface TuneManager : NSObject
{
    TuneAnalyticsManager *_analyticsManager;
    TuneConfiguration *_configuration;
    TunePowerHookManager *_powerHookManager;
    TuneState *_state;
    TuneUserProfile *_userProfile;
    TunePlaylistManager *_playlistManager;
    TuneJSONPlayer *_playlistPlayer;
    TuneJSONPlayer *_configurationPlayer;
    TuneSessionManager *_sessionManager;
    TuneTriggerManager *_triggerManager;
    TuneCampaignStateManager *_campaignStateManager;
    TuneExperimentManager *_experimentManager;
    TuneDeepActionManager *_deepActionManager;
    TuneConnectedModeManager *_connectedModeManager;
    NSObject<OS_dispatch_queue> *_concurrentQueue;
}

+ (void)instantiateTMAModules;
+ (void)instantiateModules;
+ (id)currentManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *concurrentQueue; // @synthesize concurrentQueue=_concurrentQueue;
@property(retain, nonatomic) TuneConnectedModeManager *connectedModeManager; // @synthesize connectedModeManager=_connectedModeManager;
@property(retain, nonatomic) TuneDeepActionManager *deepActionManager; // @synthesize deepActionManager=_deepActionManager;
@property(retain, nonatomic) TuneExperimentManager *experimentManager; // @synthesize experimentManager=_experimentManager;
@property(retain, nonatomic) TuneCampaignStateManager *campaignStateManager; // @synthesize campaignStateManager=_campaignStateManager;
@property(retain, nonatomic) TuneTriggerManager *triggerManager; // @synthesize triggerManager=_triggerManager;
@property(retain, nonatomic) TuneSessionManager *sessionManager; // @synthesize sessionManager=_sessionManager;
@property(retain, nonatomic) TuneJSONPlayer *configurationPlayer; // @synthesize configurationPlayer=_configurationPlayer;
@property(retain, nonatomic) TuneJSONPlayer *playlistPlayer; // @synthesize playlistPlayer=_playlistPlayer;
@property(retain, nonatomic) TunePlaylistManager *playlistManager; // @synthesize playlistManager=_playlistManager;
@property(retain, nonatomic) TuneUserProfile *userProfile; // @synthesize userProfile=_userProfile;
@property(retain, nonatomic) TuneState *state; // @synthesize state=_state;
@property(retain, nonatomic) TunePowerHookManager *powerHookManager; // @synthesize powerHookManager=_powerHookManager;
@property(retain, nonatomic) TuneConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) TuneAnalyticsManager *analyticsManager; // @synthesize analyticsManager=_analyticsManager;
- (void).cxx_destruct;
- (void)handleSaveUserDefaults:(id)arg1;
- (void)handleTMADisable:(id)arg1;
- (void)handleTMAEnable:(id)arg1;
- (void)registerSkyhooks;

@end

