/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "NSXMLParserDelegate.h"

@class NSString, NSMutableArray;

@interface TuneRequestsQueue : NSObject <NSXMLParserDelegate> {
	NSMutableArray* queueParts_;
	NSString* pathOld;
	NSString* pathStorageDir;
	NSString* pathStorageFile;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* pathOld;
@property(retain, nonatomic) NSString* pathStorageFile;
@property(retain, nonatomic) NSString* pathStorageDir;
@property(retain, nonatomic) NSMutableArray* queueParts;
@property(readonly, assign) unsigned queuedRequestsCount;
+(BOOL)exists;
-(void).cxx_destruct;
-(void)fixForiCloud;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(BOOL)load;
-(void)save;
-(id)pop;
-(void)pushToHead:(id)head;
-(void)push:(id)push;
-(unsigned)getSmallestPartFreeIndex;
-(BOOL)removePart:(id)part;
-(id)addNewPart;
-(id)getFirstPart;
-(id)getLastPart;
-(void)closedown;
-(id)init;
@end

