//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface TuneSwizzleBlacklist : NSObject
{
    NSSet *_blackList;
}

+ (_Bool)classIsOnBlackList:(id)arg1;
+ (void)reset;
+ (id)sharedBlacklist;
- (void).cxx_destruct;
- (id)buildBaseBlacklist;
- (void)updateBlacklistsFromUserDefaults;
- (void)buildBaseBlacklistsFromPlist;
- (_Bool)classIsOnBlackList:(id)arg1;
- (void)_reset;
- (id)init;

@end

