/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>


@interface UIView (FindUIViewController)
-(id)traverseResponderChainForUIViewController;
-(id)firstAvailableUIViewController;
@end

@interface UIView (LRAdDebugging)
-(id)fb_whyIsThisViewNotInteractable;
-(id)fb_whyIsThisViewNotVisible;
-(id)fb_firstDescendentScrollView;
-(id)fb_firstDescendentScrollViewWithRecurseLimit:(unsigned)recurseLimit;
-(id)fb_ancestorHierarchyDescription;
@end

