/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import </libobjc.A.h>
#import "wotblitz-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WebViewURLDelegate : NSObject <UIWebViewDelegate> {
	IUIWebViewDelegate* delegate;
	UIWebView* webView;
	WebViewControl* webViewControl;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)setDAVAWebViewControl:(WebViewControl*)control;
-(void)setDAVAUIWebView:(UIWebView*)view;
-(void)onExecuteJScript:(id)script;
-(id)renderUIViewToImage:(id)image;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)setDelegate:(IUIWebViewDelegate*)delegate andWebView:(UIWebView*)view;
-(void)rightGesture;
-(void)leftGesture;
-(id)init;
@end

