//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"

@class NSString;

@interface WebViewURLDelegate : NSObject <UIWebViewDelegate>
{
    struct IUIWebViewDelegate *delegate;
    struct UIWebView *webView;
    struct WebViewControl *webViewControl;
}

- (void)setDAVAWebViewControl:(struct WebViewControl *)arg1;
- (void)setDAVAUIWebView:(struct UIWebView *)arg1;
- (void)onExecuteJScript:(id)arg1;
- (id)renderUIViewToImage:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)setDelegate:(struct IUIWebViewDelegate *)arg1 andWebView:(struct UIWebView *)arg2;
- (void)rightGesture;
- (void)leftGesture;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

